// Code generated by protoc-gen-go. DO NOT EDIT.
// source: huawei-driver.proto

package huawei_driver

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HwBoardFail struct {
	EntPhysicalIndex     uint32   `protobuf:"varint,1,opt,name=EntPhysicalIndex,proto3" json:"EntPhysicalIndex,omitempty"`
	EntPhysicalName      string   `protobuf:"bytes,2,opt,name=EntPhysicalName,proto3" json:"EntPhysicalName,omitempty"`
	EntityPhysicalIndex  uint32   `protobuf:"varint,3,opt,name=EntityPhysicalIndex,proto3" json:"EntityPhysicalIndex,omitempty"`
	EntityTrapFaultID    uint32   `protobuf:"varint,4,opt,name=EntityTrapFaultID,proto3" json:"EntityTrapFaultID,omitempty"`
	EntityType           uint32   `protobuf:"varint,5,opt,name=EntityType,proto3" json:"EntityType,omitempty"`
	Reason               string   `protobuf:"bytes,6,opt,name=Reason,proto3" json:"Reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HwBoardFail) Reset()         { *m = HwBoardFail{} }
func (m *HwBoardFail) String() string { return proto.CompactTextString(m) }
func (*HwBoardFail) ProtoMessage()    {}
func (*HwBoardFail) Descriptor() ([]byte, []int) {
	return fileDescriptor_0877d8595b410822, []int{0}
}

func (m *HwBoardFail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HwBoardFail.Unmarshal(m, b)
}
func (m *HwBoardFail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HwBoardFail.Marshal(b, m, deterministic)
}
func (m *HwBoardFail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HwBoardFail.Merge(m, src)
}
func (m *HwBoardFail) XXX_Size() int {
	return xxx_messageInfo_HwBoardFail.Size(m)
}
func (m *HwBoardFail) XXX_DiscardUnknown() {
	xxx_messageInfo_HwBoardFail.DiscardUnknown(m)
}

var xxx_messageInfo_HwBoardFail proto.InternalMessageInfo

func (m *HwBoardFail) GetEntPhysicalIndex() uint32 {
	if m != nil {
		return m.EntPhysicalIndex
	}
	return 0
}

func (m *HwBoardFail) GetEntPhysicalName() string {
	if m != nil {
		return m.EntPhysicalName
	}
	return ""
}

func (m *HwBoardFail) GetEntityPhysicalIndex() uint32 {
	if m != nil {
		return m.EntityPhysicalIndex
	}
	return 0
}

func (m *HwBoardFail) GetEntityTrapFaultID() uint32 {
	if m != nil {
		return m.EntityTrapFaultID
	}
	return 0
}

func (m *HwBoardFail) GetEntityType() uint32 {
	if m != nil {
		return m.EntityType
	}
	return 0
}

func (m *HwBoardFail) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type HwBoardFailResume struct {
	EntPhysicalIndex     uint32   `protobuf:"varint,1,opt,name=EntPhysicalIndex,proto3" json:"EntPhysicalIndex,omitempty"`
	EntPhysicalName      string   `protobuf:"bytes,2,opt,name=EntPhysicalName,proto3" json:"EntPhysicalName,omitempty"`
	EntityPhysicalIndex  uint32   `protobuf:"varint,3,opt,name=EntityPhysicalIndex,proto3" json:"EntityPhysicalIndex,omitempty"`
	EntityTrapFaultID    uint32   `protobuf:"varint,4,opt,name=EntityTrapFaultID,proto3" json:"EntityTrapFaultID,omitempty"`
	EntityType           uint32   `protobuf:"varint,5,opt,name=EntityType,proto3" json:"EntityType,omitempty"`
	Reason               string   `protobuf:"bytes,6,opt,name=Reason,proto3" json:"Reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HwBoardFailResume) Reset()         { *m = HwBoardFailResume{} }
func (m *HwBoardFailResume) String() string { return proto.CompactTextString(m) }
func (*HwBoardFailResume) ProtoMessage()    {}
func (*HwBoardFailResume) Descriptor() ([]byte, []int) {
	return fileDescriptor_0877d8595b410822, []int{1}
}

func (m *HwBoardFailResume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HwBoardFailResume.Unmarshal(m, b)
}
func (m *HwBoardFailResume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HwBoardFailResume.Marshal(b, m, deterministic)
}
func (m *HwBoardFailResume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HwBoardFailResume.Merge(m, src)
}
func (m *HwBoardFailResume) XXX_Size() int {
	return xxx_messageInfo_HwBoardFailResume.Size(m)
}
func (m *HwBoardFailResume) XXX_DiscardUnknown() {
	xxx_messageInfo_HwBoardFailResume.DiscardUnknown(m)
}

var xxx_messageInfo_HwBoardFailResume proto.InternalMessageInfo

func (m *HwBoardFailResume) GetEntPhysicalIndex() uint32 {
	if m != nil {
		return m.EntPhysicalIndex
	}
	return 0
}

func (m *HwBoardFailResume) GetEntPhysicalName() string {
	if m != nil {
		return m.EntPhysicalName
	}
	return ""
}

func (m *HwBoardFailResume) GetEntityPhysicalIndex() uint32 {
	if m != nil {
		return m.EntityPhysicalIndex
	}
	return 0
}

func (m *HwBoardFailResume) GetEntityTrapFaultID() uint32 {
	if m != nil {
		return m.EntityTrapFaultID
	}
	return 0
}

func (m *HwBoardFailResume) GetEntityType() uint32 {
	if m != nil {
		return m.EntityType
	}
	return 0
}

func (m *HwBoardFailResume) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type HwBoardInvalid struct {
	EntPhysicalIndex     uint32   `protobuf:"varint,1,opt,name=EntPhysicalIndex,proto3" json:"EntPhysicalIndex,omitempty"`
	EntPhysicalName      string   `protobuf:"bytes,2,opt,name=EntPhysicalName,proto3" json:"EntPhysicalName,omitempty"`
	EntityPhysicalIndex  uint32   `protobuf:"varint,3,opt,name=EntityPhysicalIndex,proto3" json:"EntityPhysicalIndex,omitempty"`
	EntityTrapFaultID    uint32   `protobuf:"varint,4,opt,name=EntityTrapFaultID,proto3" json:"EntityTrapFaultID,omitempty"`
	EntityType           uint32   `protobuf:"varint,5,opt,name=EntityType,proto3" json:"EntityType,omitempty"`
	Reason               string   `protobuf:"bytes,6,opt,name=Reason,proto3" json:"Reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HwBoardInvalid) Reset()         { *m = HwBoardInvalid{} }
func (m *HwBoardInvalid) String() string { return proto.CompactTextString(m) }
func (*HwBoardInvalid) ProtoMessage()    {}
func (*HwBoardInvalid) Descriptor() ([]byte, []int) {
	return fileDescriptor_0877d8595b410822, []int{2}
}

func (m *HwBoardInvalid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HwBoardInvalid.Unmarshal(m, b)
}
func (m *HwBoardInvalid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HwBoardInvalid.Marshal(b, m, deterministic)
}
func (m *HwBoardInvalid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HwBoardInvalid.Merge(m, src)
}
func (m *HwBoardInvalid) XXX_Size() int {
	return xxx_messageInfo_HwBoardInvalid.Size(m)
}
func (m *HwBoardInvalid) XXX_DiscardUnknown() {
	xxx_messageInfo_HwBoardInvalid.DiscardUnknown(m)
}

var xxx_messageInfo_HwBoardInvalid proto.InternalMessageInfo

func (m *HwBoardInvalid) GetEntPhysicalIndex() uint32 {
	if m != nil {
		return m.EntPhysicalIndex
	}
	return 0
}

func (m *HwBoardInvalid) GetEntPhysicalName() string {
	if m != nil {
		return m.EntPhysicalName
	}
	return ""
}

func (m *HwBoardInvalid) GetEntityPhysicalIndex() uint32 {
	if m != nil {
		return m.EntityPhysicalIndex
	}
	return 0
}

func (m *HwBoardInvalid) GetEntityTrapFaultID() uint32 {
	if m != nil {
		return m.EntityTrapFaultID
	}
	return 0
}

func (m *HwBoardInvalid) GetEntityType() uint32 {
	if m != nil {
		return m.EntityType
	}
	return 0
}

func (m *HwBoardInvalid) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type HwBoardInvalidResume struct {
	EntPhysicalIndex     uint32   `protobuf:"varint,1,opt,name=EntPhysicalIndex,proto3" json:"EntPhysicalIndex,omitempty"`
	EntPhysicalName      string   `protobuf:"bytes,2,opt,name=EntPhysicalName,proto3" json:"EntPhysicalName,omitempty"`
	EntityPhysicalIndex  uint32   `protobuf:"varint,3,opt,name=EntityPhysicalIndex,proto3" json:"EntityPhysicalIndex,omitempty"`
	EntityTrapFaultID    uint32   `protobuf:"varint,4,opt,name=EntityTrapFaultID,proto3" json:"EntityTrapFaultID,omitempty"`
	EntityType           uint32   `protobuf:"varint,5,opt,name=EntityType,proto3" json:"EntityType,omitempty"`
	Reason               string   `protobuf:"bytes,6,opt,name=Reason,proto3" json:"Reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HwBoardInvalidResume) Reset()         { *m = HwBoardInvalidResume{} }
func (m *HwBoardInvalidResume) String() string { return proto.CompactTextString(m) }
func (*HwBoardInvalidResume) ProtoMessage()    {}
func (*HwBoardInvalidResume) Descriptor() ([]byte, []int) {
	return fileDescriptor_0877d8595b410822, []int{3}
}

func (m *HwBoardInvalidResume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HwBoardInvalidResume.Unmarshal(m, b)
}
func (m *HwBoardInvalidResume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HwBoardInvalidResume.Marshal(b, m, deterministic)
}
func (m *HwBoardInvalidResume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HwBoardInvalidResume.Merge(m, src)
}
func (m *HwBoardInvalidResume) XXX_Size() int {
	return xxx_messageInfo_HwBoardInvalidResume.Size(m)
}
func (m *HwBoardInvalidResume) XXX_DiscardUnknown() {
	xxx_messageInfo_HwBoardInvalidResume.DiscardUnknown(m)
}

var xxx_messageInfo_HwBoardInvalidResume proto.InternalMessageInfo

func (m *HwBoardInvalidResume) GetEntPhysicalIndex() uint32 {
	if m != nil {
		return m.EntPhysicalIndex
	}
	return 0
}

func (m *HwBoardInvalidResume) GetEntPhysicalName() string {
	if m != nil {
		return m.EntPhysicalName
	}
	return ""
}

func (m *HwBoardInvalidResume) GetEntityPhysicalIndex() uint32 {
	if m != nil {
		return m.EntityPhysicalIndex
	}
	return 0
}

func (m *HwBoardInvalidResume) GetEntityTrapFaultID() uint32 {
	if m != nil {
		return m.EntityTrapFaultID
	}
	return 0
}

func (m *HwBoardInvalidResume) GetEntityType() uint32 {
	if m != nil {
		return m.EntityType
	}
	return 0
}

func (m *HwBoardInvalidResume) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type HwEntityInvalid struct {
	BaseTrapEventType    uint32   `protobuf:"varint,1,opt,name=BaseTrapEventType,proto3" json:"BaseTrapEventType,omitempty"`
	BaseTrapSeverity     uint32   `protobuf:"varint,2,opt,name=BaseTrapSeverity,proto3" json:"BaseTrapSeverity,omitempty"`
	EntContainedIn       uint32   `protobuf:"varint,3,opt,name=EntContainedIn,proto3" json:"EntContainedIn,omitempty"`
	EntPhysicalName      string   `protobuf:"bytes,4,opt,name=EntPhysicalName,proto3" json:"EntPhysicalName,omitempty"`
	EntityPhysicalIndex  uint32   `protobuf:"varint,5,opt,name=EntityPhysicalIndex,proto3" json:"EntityPhysicalIndex,omitempty"`
	ProbableCause        uint32   `protobuf:"varint,6,opt,name=ProbableCause,proto3" json:"ProbableCause,omitempty"`
	ReasonDescription    string   `protobuf:"bytes,7,opt,name=ReasonDescription,proto3" json:"ReasonDescription,omitempty"`
	RelativeResource     string   `protobuf:"bytes,8,opt,name=RelativeResource,proto3" json:"RelativeResource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HwEntityInvalid) Reset()         { *m = HwEntityInvalid{} }
func (m *HwEntityInvalid) String() string { return proto.CompactTextString(m) }
func (*HwEntityInvalid) ProtoMessage()    {}
func (*HwEntityInvalid) Descriptor() ([]byte, []int) {
	return fileDescriptor_0877d8595b410822, []int{4}
}

func (m *HwEntityInvalid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HwEntityInvalid.Unmarshal(m, b)
}
func (m *HwEntityInvalid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HwEntityInvalid.Marshal(b, m, deterministic)
}
func (m *HwEntityInvalid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HwEntityInvalid.Merge(m, src)
}
func (m *HwEntityInvalid) XXX_Size() int {
	return xxx_messageInfo_HwEntityInvalid.Size(m)
}
func (m *HwEntityInvalid) XXX_DiscardUnknown() {
	xxx_messageInfo_HwEntityInvalid.DiscardUnknown(m)
}

var xxx_messageInfo_HwEntityInvalid proto.InternalMessageInfo

func (m *HwEntityInvalid) GetBaseTrapEventType() uint32 {
	if m != nil {
		return m.BaseTrapEventType
	}
	return 0
}

func (m *HwEntityInvalid) GetBaseTrapSeverity() uint32 {
	if m != nil {
		return m.BaseTrapSeverity
	}
	return 0
}

func (m *HwEntityInvalid) GetEntContainedIn() uint32 {
	if m != nil {
		return m.EntContainedIn
	}
	return 0
}

func (m *HwEntityInvalid) GetEntPhysicalName() string {
	if m != nil {
		return m.EntPhysicalName
	}
	return ""
}

func (m *HwEntityInvalid) GetEntityPhysicalIndex() uint32 {
	if m != nil {
		return m.EntityPhysicalIndex
	}
	return 0
}

func (m *HwEntityInvalid) GetProbableCause() uint32 {
	if m != nil {
		return m.ProbableCause
	}
	return 0
}

func (m *HwEntityInvalid) GetReasonDescription() string {
	if m != nil {
		return m.ReasonDescription
	}
	return ""
}

func (m *HwEntityInvalid) GetRelativeResource() string {
	if m != nil {
		return m.RelativeResource
	}
	return ""
}

type HwEntityResume struct {
	BaseTrapEventType    uint32   `protobuf:"varint,1,opt,name=BaseTrapEventType,proto3" json:"BaseTrapEventType,omitempty"`
	BaseTrapSeverity     uint32   `protobuf:"varint,2,opt,name=BaseTrapSeverity,proto3" json:"BaseTrapSeverity,omitempty"`
	EntContainedIn       uint32   `protobuf:"varint,3,opt,name=EntContainedIn,proto3" json:"EntContainedIn,omitempty"`
	EntPhysicalName      string   `protobuf:"bytes,4,opt,name=EntPhysicalName,proto3" json:"EntPhysicalName,omitempty"`
	EntityPhysicalIndex  uint32   `protobuf:"varint,5,opt,name=EntityPhysicalIndex,proto3" json:"EntityPhysicalIndex,omitempty"`
	ProbableCause        uint32   `protobuf:"varint,6,opt,name=ProbableCause,proto3" json:"ProbableCause,omitempty"`
	ReasonDescription    string   `protobuf:"bytes,7,opt,name=ReasonDescription,proto3" json:"ReasonDescription,omitempty"`
	RelativeResource     string   `protobuf:"bytes,8,opt,name=RelativeResource,proto3" json:"RelativeResource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HwEntityResume) Reset()         { *m = HwEntityResume{} }
func (m *HwEntityResume) String() string { return proto.CompactTextString(m) }
func (*HwEntityResume) ProtoMessage()    {}
func (*HwEntityResume) Descriptor() ([]byte, []int) {
	return fileDescriptor_0877d8595b410822, []int{5}
}

func (m *HwEntityResume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HwEntityResume.Unmarshal(m, b)
}
func (m *HwEntityResume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HwEntityResume.Marshal(b, m, deterministic)
}
func (m *HwEntityResume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HwEntityResume.Merge(m, src)
}
func (m *HwEntityResume) XXX_Size() int {
	return xxx_messageInfo_HwEntityResume.Size(m)
}
func (m *HwEntityResume) XXX_DiscardUnknown() {
	xxx_messageInfo_HwEntityResume.DiscardUnknown(m)
}

var xxx_messageInfo_HwEntityResume proto.InternalMessageInfo

func (m *HwEntityResume) GetBaseTrapEventType() uint32 {
	if m != nil {
		return m.BaseTrapEventType
	}
	return 0
}

func (m *HwEntityResume) GetBaseTrapSeverity() uint32 {
	if m != nil {
		return m.BaseTrapSeverity
	}
	return 0
}

func (m *HwEntityResume) GetEntContainedIn() uint32 {
	if m != nil {
		return m.EntContainedIn
	}
	return 0
}

func (m *HwEntityResume) GetEntPhysicalName() string {
	if m != nil {
		return m.EntPhysicalName
	}
	return ""
}

func (m *HwEntityResume) GetEntityPhysicalIndex() uint32 {
	if m != nil {
		return m.EntityPhysicalIndex
	}
	return 0
}

func (m *HwEntityResume) GetProbableCause() uint32 {
	if m != nil {
		return m.ProbableCause
	}
	return 0
}

func (m *HwEntityResume) GetReasonDescription() string {
	if m != nil {
		return m.ReasonDescription
	}
	return ""
}

func (m *HwEntityResume) GetRelativeResource() string {
	if m != nil {
		return m.RelativeResource
	}
	return ""
}

type HwOpticalInvalid struct {
	EntPhysicalIndex     uint32   `protobuf:"varint,1,opt,name=EntPhysicalIndex,proto3" json:"EntPhysicalIndex,omitempty"`
	EntPhysicalName      string   `protobuf:"bytes,2,opt,name=EntPhysicalName,proto3" json:"EntPhysicalName,omitempty"`
	EntityPhysicalIndex  uint32   `protobuf:"varint,3,opt,name=EntityPhysicalIndex,proto3" json:"EntityPhysicalIndex,omitempty"`
	EntityTrapFaultID    uint32   `protobuf:"varint,4,opt,name=EntityTrapFaultID,proto3" json:"EntityTrapFaultID,omitempty"`
	ReasonDescription    string   `protobuf:"bytes,5,opt,name=ReasonDescription,proto3" json:"ReasonDescription,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HwOpticalInvalid) Reset()         { *m = HwOpticalInvalid{} }
func (m *HwOpticalInvalid) String() string { return proto.CompactTextString(m) }
func (*HwOpticalInvalid) ProtoMessage()    {}
func (*HwOpticalInvalid) Descriptor() ([]byte, []int) {
	return fileDescriptor_0877d8595b410822, []int{6}
}

func (m *HwOpticalInvalid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HwOpticalInvalid.Unmarshal(m, b)
}
func (m *HwOpticalInvalid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HwOpticalInvalid.Marshal(b, m, deterministic)
}
func (m *HwOpticalInvalid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HwOpticalInvalid.Merge(m, src)
}
func (m *HwOpticalInvalid) XXX_Size() int {
	return xxx_messageInfo_HwOpticalInvalid.Size(m)
}
func (m *HwOpticalInvalid) XXX_DiscardUnknown() {
	xxx_messageInfo_HwOpticalInvalid.DiscardUnknown(m)
}

var xxx_messageInfo_HwOpticalInvalid proto.InternalMessageInfo

func (m *HwOpticalInvalid) GetEntPhysicalIndex() uint32 {
	if m != nil {
		return m.EntPhysicalIndex
	}
	return 0
}

func (m *HwOpticalInvalid) GetEntPhysicalName() string {
	if m != nil {
		return m.EntPhysicalName
	}
	return ""
}

func (m *HwOpticalInvalid) GetEntityPhysicalIndex() uint32 {
	if m != nil {
		return m.EntityPhysicalIndex
	}
	return 0
}

func (m *HwOpticalInvalid) GetEntityTrapFaultID() uint32 {
	if m != nil {
		return m.EntityTrapFaultID
	}
	return 0
}

func (m *HwOpticalInvalid) GetReasonDescription() string {
	if m != nil {
		return m.ReasonDescription
	}
	return ""
}

type HwOpticalInvalidResume struct {
	EntPhysicalIndex     uint32   `protobuf:"varint,1,opt,name=EntPhysicalIndex,proto3" json:"EntPhysicalIndex,omitempty"`
	EntPhysicalName      string   `protobuf:"bytes,2,opt,name=EntPhysicalName,proto3" json:"EntPhysicalName,omitempty"`
	EntityPhysicalIndex  uint32   `protobuf:"varint,3,opt,name=EntityPhysicalIndex,proto3" json:"EntityPhysicalIndex,omitempty"`
	EntityTrapFaultID    uint32   `protobuf:"varint,4,opt,name=EntityTrapFaultID,proto3" json:"EntityTrapFaultID,omitempty"`
	ReasonDescription    string   `protobuf:"bytes,5,opt,name=ReasonDescription,proto3" json:"ReasonDescription,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HwOpticalInvalidResume) Reset()         { *m = HwOpticalInvalidResume{} }
func (m *HwOpticalInvalidResume) String() string { return proto.CompactTextString(m) }
func (*HwOpticalInvalidResume) ProtoMessage()    {}
func (*HwOpticalInvalidResume) Descriptor() ([]byte, []int) {
	return fileDescriptor_0877d8595b410822, []int{7}
}

func (m *HwOpticalInvalidResume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HwOpticalInvalidResume.Unmarshal(m, b)
}
func (m *HwOpticalInvalidResume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HwOpticalInvalidResume.Marshal(b, m, deterministic)
}
func (m *HwOpticalInvalidResume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HwOpticalInvalidResume.Merge(m, src)
}
func (m *HwOpticalInvalidResume) XXX_Size() int {
	return xxx_messageInfo_HwOpticalInvalidResume.Size(m)
}
func (m *HwOpticalInvalidResume) XXX_DiscardUnknown() {
	xxx_messageInfo_HwOpticalInvalidResume.DiscardUnknown(m)
}

var xxx_messageInfo_HwOpticalInvalidResume proto.InternalMessageInfo

func (m *HwOpticalInvalidResume) GetEntPhysicalIndex() uint32 {
	if m != nil {
		return m.EntPhysicalIndex
	}
	return 0
}

func (m *HwOpticalInvalidResume) GetEntPhysicalName() string {
	if m != nil {
		return m.EntPhysicalName
	}
	return ""
}

func (m *HwOpticalInvalidResume) GetEntityPhysicalIndex() uint32 {
	if m != nil {
		return m.EntityPhysicalIndex
	}
	return 0
}

func (m *HwOpticalInvalidResume) GetEntityTrapFaultID() uint32 {
	if m != nil {
		return m.EntityTrapFaultID
	}
	return 0
}

func (m *HwOpticalInvalidResume) GetReasonDescription() string {
	if m != nil {
		return m.ReasonDescription
	}
	return ""
}

type HwRATEOFTRAFFICResume struct {
	EntPhysicalIndex     uint32   `protobuf:"varint,1,opt,name=EntPhysicalIndex,proto3" json:"EntPhysicalIndex,omitempty"`
	EntPhysicalName      string   `protobuf:"bytes,2,opt,name=EntPhysicalName,proto3" json:"EntPhysicalName,omitempty"`
	EntityPhysicalIndex  uint32   `protobuf:"varint,3,opt,name=EntityPhysicalIndex,proto3" json:"EntityPhysicalIndex,omitempty"`
	EntityTrapFaultID    uint32   `protobuf:"varint,4,opt,name=EntityTrapFaultID,proto3" json:"EntityTrapFaultID,omitempty"`
	Reason               string   `protobuf:"bytes,5,opt,name=Reason,proto3" json:"Reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HwRATEOFTRAFFICResume) Reset()         { *m = HwRATEOFTRAFFICResume{} }
func (m *HwRATEOFTRAFFICResume) String() string { return proto.CompactTextString(m) }
func (*HwRATEOFTRAFFICResume) ProtoMessage()    {}
func (*HwRATEOFTRAFFICResume) Descriptor() ([]byte, []int) {
	return fileDescriptor_0877d8595b410822, []int{8}
}

func (m *HwRATEOFTRAFFICResume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HwRATEOFTRAFFICResume.Unmarshal(m, b)
}
func (m *HwRATEOFTRAFFICResume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HwRATEOFTRAFFICResume.Marshal(b, m, deterministic)
}
func (m *HwRATEOFTRAFFICResume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HwRATEOFTRAFFICResume.Merge(m, src)
}
func (m *HwRATEOFTRAFFICResume) XXX_Size() int {
	return xxx_messageInfo_HwRATEOFTRAFFICResume.Size(m)
}
func (m *HwRATEOFTRAFFICResume) XXX_DiscardUnknown() {
	xxx_messageInfo_HwRATEOFTRAFFICResume.DiscardUnknown(m)
}

var xxx_messageInfo_HwRATEOFTRAFFICResume proto.InternalMessageInfo

func (m *HwRATEOFTRAFFICResume) GetEntPhysicalIndex() uint32 {
	if m != nil {
		return m.EntPhysicalIndex
	}
	return 0
}

func (m *HwRATEOFTRAFFICResume) GetEntPhysicalName() string {
	if m != nil {
		return m.EntPhysicalName
	}
	return ""
}

func (m *HwRATEOFTRAFFICResume) GetEntityPhysicalIndex() uint32 {
	if m != nil {
		return m.EntityPhysicalIndex
	}
	return 0
}

func (m *HwRATEOFTRAFFICResume) GetEntityTrapFaultID() uint32 {
	if m != nil {
		return m.EntityTrapFaultID
	}
	return 0
}

func (m *HwRATEOFTRAFFICResume) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type HwRATEOFTRAFFICRising struct {
	EntPhysicalIndex     uint32   `protobuf:"varint,1,opt,name=EntPhysicalIndex,proto3" json:"EntPhysicalIndex,omitempty"`
	EntPhysicalName      string   `protobuf:"bytes,2,opt,name=EntPhysicalName,proto3" json:"EntPhysicalName,omitempty"`
	EntityPhysicalIndex  uint32   `protobuf:"varint,3,opt,name=EntityPhysicalIndex,proto3" json:"EntityPhysicalIndex,omitempty"`
	EntityTrapFaultID    uint32   `protobuf:"varint,4,opt,name=EntityTrapFaultID,proto3" json:"EntityTrapFaultID,omitempty"`
	Reason               string   `protobuf:"bytes,5,opt,name=Reason,proto3" json:"Reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HwRATEOFTRAFFICRising) Reset()         { *m = HwRATEOFTRAFFICRising{} }
func (m *HwRATEOFTRAFFICRising) String() string { return proto.CompactTextString(m) }
func (*HwRATEOFTRAFFICRising) ProtoMessage()    {}
func (*HwRATEOFTRAFFICRising) Descriptor() ([]byte, []int) {
	return fileDescriptor_0877d8595b410822, []int{9}
}

func (m *HwRATEOFTRAFFICRising) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HwRATEOFTRAFFICRising.Unmarshal(m, b)
}
func (m *HwRATEOFTRAFFICRising) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HwRATEOFTRAFFICRising.Marshal(b, m, deterministic)
}
func (m *HwRATEOFTRAFFICRising) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HwRATEOFTRAFFICRising.Merge(m, src)
}
func (m *HwRATEOFTRAFFICRising) XXX_Size() int {
	return xxx_messageInfo_HwRATEOFTRAFFICRising.Size(m)
}
func (m *HwRATEOFTRAFFICRising) XXX_DiscardUnknown() {
	xxx_messageInfo_HwRATEOFTRAFFICRising.DiscardUnknown(m)
}

var xxx_messageInfo_HwRATEOFTRAFFICRising proto.InternalMessageInfo

func (m *HwRATEOFTRAFFICRising) GetEntPhysicalIndex() uint32 {
	if m != nil {
		return m.EntPhysicalIndex
	}
	return 0
}

func (m *HwRATEOFTRAFFICRising) GetEntPhysicalName() string {
	if m != nil {
		return m.EntPhysicalName
	}
	return ""
}

func (m *HwRATEOFTRAFFICRising) GetEntityPhysicalIndex() uint32 {
	if m != nil {
		return m.EntityPhysicalIndex
	}
	return 0
}

func (m *HwRATEOFTRAFFICRising) GetEntityTrapFaultID() uint32 {
	if m != nil {
		return m.EntityTrapFaultID
	}
	return 0
}

func (m *HwRATEOFTRAFFICRising) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterType((*HwBoardFail)(nil), "huawei_driver.HwBoardFail")
	proto.RegisterType((*HwBoardFailResume)(nil), "huawei_driver.HwBoardFailResume")
	proto.RegisterType((*HwBoardInvalid)(nil), "huawei_driver.HwBoardInvalid")
	proto.RegisterType((*HwBoardInvalidResume)(nil), "huawei_driver.HwBoardInvalidResume")
	proto.RegisterType((*HwEntityInvalid)(nil), "huawei_driver.HwEntityInvalid")
	proto.RegisterType((*HwEntityResume)(nil), "huawei_driver.HwEntityResume")
	proto.RegisterType((*HwOpticalInvalid)(nil), "huawei_driver.HwOpticalInvalid")
	proto.RegisterType((*HwOpticalInvalidResume)(nil), "huawei_driver.HwOpticalInvalidResume")
	proto.RegisterType((*HwRATEOFTRAFFICResume)(nil), "huawei_driver.HwRATEOFTRAFFICResume")
	proto.RegisterType((*HwRATEOFTRAFFICRising)(nil), "huawei_driver.HwRATEOFTRAFFICRising")
}

func init() { proto.RegisterFile("huawei-driver.proto", fileDescriptor_0877d8595b410822) }

var fileDescriptor_0877d8595b410822 = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x96, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0xc7, 0x49, 0xdc, 0x56, 0x7d, 0x92, 0xdd, 0xed, 0xac, 0x2e, 0x39, 0xc9, 0x52, 0x44, 0x8a,
	0xac, 0x22, 0xf8, 0x09, 0x76, 0xbb, 0x09, 0xcd, 0xc5, 0x5d, 0xc6, 0xde, 0x65, 0xda, 0x3c, 0xdc,
	0x81, 0xec, 0x4c, 0x98, 0x99, 0x24, 0xf6, 0x28, 0xf8, 0x55, 0xbd, 0xea, 0xcd, 0x8b, 0x22, 0x92,
	0x99, 0x2c, 0xb6, 0x4d, 0xf6, 0xd0, 0x83, 0x87, 0x5a, 0x8f, 0xfd, 0xbd, 0xc7, 0xe3, 0xfd, 0x7f,
	0x4c, 0x1f, 0x81, 0xa3, 0xeb, 0x82, 0x55, 0xc8, 0x5f, 0xa6, 0x8a, 0x97, 0xa8, 0x5e, 0xe5, 0x4a,
	0x1a, 0x49, 0x02, 0x07, 0xdf, 0x3b, 0x38, 0xfc, 0xe1, 0xc1, 0xa3, 0x49, 0x75, 0x2e, 0x99, 0x4a,
	0x63, 0xc6, 0x33, 0xf2, 0x02, 0x0e, 0x23, 0x61, 0xae, 0xae, 0x17, 0x9a, 0xcf, 0x59, 0x96, 0x88,
	0x14, 0x3f, 0x86, 0xde, 0x89, 0x37, 0x0a, 0x68, 0x8b, 0x93, 0x11, 0x1c, 0x2c, 0xb1, 0xb7, 0xec,
	0x06, 0x43, 0xff, 0xc4, 0x1b, 0x3d, 0xa4, 0xeb, 0x98, 0xbc, 0x86, 0xa3, 0x48, 0x18, 0x6e, 0x16,
	0xab, 0x83, 0xef, 0xd9, 0xc1, 0x5d, 0x25, 0x72, 0x0a, 0x03, 0x87, 0xa7, 0x8a, 0xe5, 0x31, 0x2b,
	0x32, 0x93, 0x5c, 0x84, 0x7b, 0xb6, 0xbf, 0x5d, 0x20, 0x4f, 0x01, 0x1a, 0xb8, 0xc8, 0x31, 0xec,
	0xd9, 0xb6, 0x25, 0x42, 0x8e, 0xa1, 0x4f, 0x91, 0x69, 0x29, 0xc2, 0xbe, 0x5d, 0xb0, 0xf9, 0x35,
	0xfc, 0xe4, 0xc3, 0x60, 0x29, 0x3d, 0x45, 0x5d, 0xdc, 0xe0, 0x8e, 0x39, 0xf8, 0xe5, 0xc1, 0x7e,
	0xe3, 0x20, 0x11, 0x25, 0xcb, 0x78, 0xba, 0x63, 0x02, 0x3e, 0xfb, 0xf0, 0x78, 0x55, 0xc0, 0x4e,
	0xbe, 0x83, 0x6f, 0x3e, 0x1c, 0x4c, 0x2a, 0xd7, 0x78, 0xfb, 0x10, 0x4e, 0x61, 0x70, 0xce, 0x34,
	0xd6, 0xe3, 0xa3, 0x12, 0x85, 0xb1, 0x23, 0x9d, 0x82, 0x76, 0xa1, 0xf6, 0x75, 0x0b, 0xdf, 0x61,
	0x89, 0x8a, 0x9b, 0x85, 0x95, 0x10, 0xd0, 0x16, 0x27, 0xcf, 0x61, 0x3f, 0x12, 0x66, 0x2c, 0x85,
	0x61, 0x5c, 0x60, 0x9a, 0x88, 0x46, 0xc0, 0x1a, 0xed, 0xf2, 0xba, 0xb7, 0x91, 0xd7, 0xde, 0xdd,
	0x5e, 0x9f, 0x41, 0x70, 0xa5, 0xe4, 0x8c, 0xcd, 0x32, 0x1c, 0xb3, 0x42, 0xa3, 0x15, 0x12, 0xd0,
	0x55, 0x58, 0x3b, 0x70, 0x86, 0x2e, 0x50, 0xcf, 0x15, 0xcf, 0x0d, 0x97, 0x22, 0xbc, 0x6f, 0x77,
	0x68, 0x17, 0x6a, 0x07, 0x14, 0x33, 0x66, 0x78, 0x89, 0x14, 0xb5, 0x2c, 0xd4, 0x1c, 0xc3, 0x07,
	0xb6, 0xb9, 0xc5, 0x87, 0x5f, 0xfd, 0xfa, 0x9f, 0xe7, 0x36, 0x6b, 0x9e, 0xdc, 0x7f, 0xe1, 0x7f,
	0x53, 0xf8, 0x77, 0x0f, 0x0e, 0x27, 0xd5, 0x65, 0x6e, 0xdc, 0x4a, 0xdb, 0x7c, 0xec, 0x3a, 0x25,
	0xf5, 0xee, 0x90, 0x34, 0xfc, 0xe9, 0xc1, 0xf1, 0x7a, 0xf0, 0xad, 0x3e, 0x72, 0x9b, 0xc5, 0xff,
	0xe2, 0xc1, 0x93, 0x49, 0x45, 0xcf, 0xa6, 0xd1, 0x65, 0x3c, 0xa5, 0x67, 0x71, 0x9c, 0x8c, 0xb7,
	0x3a, 0xfd, 0x9f, 0x13, 0xde, 0x5b, 0x39, 0xe1, 0x5d, 0x39, 0xb9, 0xe6, 0xe2, 0xc3, 0xbf, 0x95,
	0x73, 0xd6, 0xb7, 0x9f, 0xb2, 0x6f, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x50, 0x58, 0x1a, 0x28,
	0xe1, 0x0a, 0x00, 0x00,
}
