// Code generated by protoc-gen-go. DO NOT EDIT.
// source: huawei-ospfv2.proto

package huawei_ospfv2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OspfNbrStateChange struct {
	AreaId               string   `protobuf:"bytes,1,opt,name=AreaId,proto3" json:"AreaId,omitempty"`
	IfName               string   `protobuf:"bytes,2,opt,name=IfName,proto3" json:"IfName,omitempty"`
	IfnetIndex           uint32   `protobuf:"varint,3,opt,name=IfnetIndex,proto3" json:"IfnetIndex,omitempty"`
	LocalIfIpAddress     string   `protobuf:"bytes,4,opt,name=LocalIfIpAddress,proto3" json:"LocalIfIpAddress,omitempty"`
	NbrAddressLessIndex  uint32   `protobuf:"varint,5,opt,name=NbrAddressLessIndex,proto3" json:"NbrAddressLessIndex,omitempty"`
	NbrIpAddress         string   `protobuf:"bytes,6,opt,name=NbrIpAddress,proto3" json:"NbrIpAddress,omitempty"`
	NbrRtrId             string   `protobuf:"bytes,7,opt,name=NbrRtrId,proto3" json:"NbrRtrId,omitempty"`
	NbrState             string   `protobuf:"bytes,8,opt,name=NbrState,proto3" json:"NbrState,omitempty"`
	ProcessId            uint32   `protobuf:"varint,10,opt,name=ProcessId,proto3" json:"ProcessId,omitempty"`
	RouterId             string   `protobuf:"bytes,11,opt,name=RouterId,proto3" json:"RouterId,omitempty"`
	SubReason            string   `protobuf:"bytes,12,opt,name=SubReason,proto3" json:"SubReason,omitempty"`
	VpnName              string   `protobuf:"bytes,13,opt,name=VpnName,proto3" json:"VpnName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OspfNbrStateChange) Reset()         { *m = OspfNbrStateChange{} }
func (m *OspfNbrStateChange) String() string { return proto.CompactTextString(m) }
func (*OspfNbrStateChange) ProtoMessage()    {}
func (*OspfNbrStateChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_276532a87781273f, []int{0}
}

func (m *OspfNbrStateChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OspfNbrStateChange.Unmarshal(m, b)
}
func (m *OspfNbrStateChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OspfNbrStateChange.Marshal(b, m, deterministic)
}
func (m *OspfNbrStateChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OspfNbrStateChange.Merge(m, src)
}
func (m *OspfNbrStateChange) XXX_Size() int {
	return xxx_messageInfo_OspfNbrStateChange.Size(m)
}
func (m *OspfNbrStateChange) XXX_DiscardUnknown() {
	xxx_messageInfo_OspfNbrStateChange.DiscardUnknown(m)
}

var xxx_messageInfo_OspfNbrStateChange proto.InternalMessageInfo

func (m *OspfNbrStateChange) GetAreaId() string {
	if m != nil {
		return m.AreaId
	}
	return ""
}

func (m *OspfNbrStateChange) GetIfName() string {
	if m != nil {
		return m.IfName
	}
	return ""
}

func (m *OspfNbrStateChange) GetIfnetIndex() uint32 {
	if m != nil {
		return m.IfnetIndex
	}
	return 0
}

func (m *OspfNbrStateChange) GetLocalIfIpAddress() string {
	if m != nil {
		return m.LocalIfIpAddress
	}
	return ""
}

func (m *OspfNbrStateChange) GetNbrAddressLessIndex() uint32 {
	if m != nil {
		return m.NbrAddressLessIndex
	}
	return 0
}

func (m *OspfNbrStateChange) GetNbrIpAddress() string {
	if m != nil {
		return m.NbrIpAddress
	}
	return ""
}

func (m *OspfNbrStateChange) GetNbrRtrId() string {
	if m != nil {
		return m.NbrRtrId
	}
	return ""
}

func (m *OspfNbrStateChange) GetNbrState() string {
	if m != nil {
		return m.NbrState
	}
	return ""
}

func (m *OspfNbrStateChange) GetProcessId() uint32 {
	if m != nil {
		return m.ProcessId
	}
	return 0
}

func (m *OspfNbrStateChange) GetRouterId() string {
	if m != nil {
		return m.RouterId
	}
	return ""
}

func (m *OspfNbrStateChange) GetSubReason() string {
	if m != nil {
		return m.SubReason
	}
	return ""
}

func (m *OspfNbrStateChange) GetVpnName() string {
	if m != nil {
		return m.VpnName
	}
	return ""
}

type OspfVirtNbrStateChange struct {
	InstanceName         string   `protobuf:"bytes,1,opt,name=InstanceName,proto3" json:"InstanceName,omitempty"`
	ProcessId            uint32   `protobuf:"varint,2,opt,name=ProcessId,proto3" json:"ProcessId,omitempty"`
	RouterId             string   `protobuf:"bytes,3,opt,name=RouterId,proto3" json:"RouterId,omitempty"`
	VirtNbrArea          string   `protobuf:"bytes,4,opt,name=VirtNbrArea,proto3" json:"VirtNbrArea,omitempty"`
	VirtNbrRtrId         string   `protobuf:"bytes,5,opt,name=VirtNbrRtrId,proto3" json:"VirtNbrRtrId,omitempty"`
	VirtNbrState         string   `protobuf:"bytes,6,opt,name=VirtNbrState,proto3" json:"VirtNbrState,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OspfVirtNbrStateChange) Reset()         { *m = OspfVirtNbrStateChange{} }
func (m *OspfVirtNbrStateChange) String() string { return proto.CompactTextString(m) }
func (*OspfVirtNbrStateChange) ProtoMessage()    {}
func (*OspfVirtNbrStateChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_276532a87781273f, []int{1}
}

func (m *OspfVirtNbrStateChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OspfVirtNbrStateChange.Unmarshal(m, b)
}
func (m *OspfVirtNbrStateChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OspfVirtNbrStateChange.Marshal(b, m, deterministic)
}
func (m *OspfVirtNbrStateChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OspfVirtNbrStateChange.Merge(m, src)
}
func (m *OspfVirtNbrStateChange) XXX_Size() int {
	return xxx_messageInfo_OspfVirtNbrStateChange.Size(m)
}
func (m *OspfVirtNbrStateChange) XXX_DiscardUnknown() {
	xxx_messageInfo_OspfVirtNbrStateChange.DiscardUnknown(m)
}

var xxx_messageInfo_OspfVirtNbrStateChange proto.InternalMessageInfo

func (m *OspfVirtNbrStateChange) GetInstanceName() string {
	if m != nil {
		return m.InstanceName
	}
	return ""
}

func (m *OspfVirtNbrStateChange) GetProcessId() uint32 {
	if m != nil {
		return m.ProcessId
	}
	return 0
}

func (m *OspfVirtNbrStateChange) GetRouterId() string {
	if m != nil {
		return m.RouterId
	}
	return ""
}

func (m *OspfVirtNbrStateChange) GetVirtNbrArea() string {
	if m != nil {
		return m.VirtNbrArea
	}
	return ""
}

func (m *OspfVirtNbrStateChange) GetVirtNbrRtrId() string {
	if m != nil {
		return m.VirtNbrRtrId
	}
	return ""
}

func (m *OspfVirtNbrStateChange) GetVirtNbrState() string {
	if m != nil {
		return m.VirtNbrState
	}
	return ""
}

func init() {
	proto.RegisterType((*OspfNbrStateChange)(nil), "huawei_ospfv2.OspfNbrStateChange")
	proto.RegisterType((*OspfVirtNbrStateChange)(nil), "huawei_ospfv2.OspfVirtNbrStateChange")
}

func init() { proto.RegisterFile("huawei-ospfv2.proto", fileDescriptor_276532a87781273f) }

var fileDescriptor_276532a87781273f = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xd1, 0x4a, 0xfb, 0x30,
	0x14, 0xc6, 0xe9, 0xf6, 0x5f, 0xb7, 0x9d, 0x6d, 0xf0, 0x27, 0x83, 0x11, 0x44, 0x64, 0xf4, 0x6a,
	0x08, 0x8a, 0xe8, 0x13, 0x0c, 0xaf, 0x02, 0xa3, 0x4a, 0x07, 0xbb, 0x95, 0x74, 0x4d, 0xdd, 0x40,
	0x93, 0x92, 0x64, 0xea, 0x63, 0xf8, 0x88, 0x3e, 0x8a, 0xe4, 0x24, 0xdb, 0xda, 0x29, 0x5e, 0x7e,
	0xbf, 0x2f, 0xe7, 0x3b, 0xa7, 0xe7, 0x14, 0xc6, 0x9b, 0x1d, 0x7f, 0x17, 0xdb, 0x2b, 0x65, 0xaa,
	0xf2, 0xed, 0xf6, 0xba, 0xd2, 0xca, 0x2a, 0x32, 0xf2, 0xf0, 0xc9, 0xc3, 0xe4, 0xb3, 0x0d, 0xe4,
	0xc1, 0x54, 0x65, 0x9a, 0xeb, 0xa5, 0xe5, 0x56, 0xdc, 0x6f, 0xb8, 0x7c, 0x16, 0x64, 0x02, 0xf1,
	0x5c, 0x0b, 0xce, 0x0a, 0x1a, 0x4d, 0xa3, 0x59, 0x3f, 0x0b, 0xca, 0x71, 0x56, 0xa6, 0xfc, 0x55,
	0xd0, 0x96, 0xe7, 0x5e, 0x91, 0x0b, 0x00, 0x56, 0x4a, 0x61, 0x99, 0x2c, 0xc4, 0x07, 0x6d, 0x4f,
	0xa3, 0xd9, 0x28, 0xab, 0x11, 0x72, 0x09, 0xff, 0x17, 0x6a, 0xcd, 0x5f, 0x58, 0xc9, 0xaa, 0x79,
	0x51, 0x68, 0x61, 0x0c, 0xfd, 0x87, 0x09, 0x3f, 0x38, 0xb9, 0x81, 0x71, 0x9a, 0xeb, 0xa0, 0x16,
	0xc2, 0x18, 0x1f, 0xda, 0xc1, 0xd0, 0xdf, 0x2c, 0x92, 0xc0, 0x30, 0xcd, 0xf5, 0x31, 0x39, 0xc6,
	0xe4, 0x06, 0x23, 0x67, 0xd0, 0x4b, 0x73, 0x9d, 0x59, 0xcd, 0x0a, 0xda, 0x45, 0xff, 0xa0, 0x83,
	0x87, 0xdf, 0x4f, 0x7b, 0x07, 0x0f, 0x35, 0x39, 0x87, 0xfe, 0xa3, 0x56, 0x6b, 0xd7, 0xab, 0xa0,
	0x80, 0x33, 0x1c, 0x81, 0xab, 0xcc, 0xd4, 0xce, 0x0a, 0x97, 0x3a, 0xf0, 0x95, 0x7b, 0xed, 0x2a,
	0x97, 0xbb, 0x3c, 0x13, 0xdc, 0x28, 0x49, 0x87, 0x68, 0x1e, 0x01, 0xa1, 0xd0, 0x5d, 0x55, 0x12,
	0x57, 0x39, 0x42, 0x6f, 0x2f, 0x93, 0xaf, 0x08, 0x26, 0xee, 0x24, 0xab, 0xad, 0xb6, 0x27, 0x67,
	0x49, 0x60, 0xc8, 0xa4, 0xb1, 0x5c, 0xae, 0x05, 0x56, 0xfa, 0xe3, 0x34, 0x58, 0x73, 0xe0, 0xd6,
	0x5f, 0x03, 0xb7, 0x4f, 0x06, 0x9e, 0xc2, 0x20, 0xf4, 0x74, 0xd7, 0x0e, 0xf7, 0xa9, 0x23, 0xd7,
	0x3f, 0x48, 0xbf, 0xc8, 0x8e, 0xef, 0x5f, 0x67, 0xb5, 0x37, 0x7e, 0xa1, 0x71, 0xe3, 0x0d, 0xb2,
	0x3c, 0xc6, 0x7f, 0xf1, 0xee, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x17, 0xf0, 0x6b, 0x45, 0xa2, 0x02,
	0x00, 0x00,
}
