// Code generated by protoc-gen-go. DO NOT EDIT.
// source: huawei-devm.proto

package huawei_devm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Devm struct {
	CpuInfos             *Devm_CpuInfos         `protobuf:"bytes,5,opt,name=cpuInfos,proto3" json:"cpuInfos,omitempty"`
	EthPortStaStss       *Devm_EthPortStaStss   `protobuf:"bytes,7,opt,name=ethPortStaStss,proto3" json:"ethPortStaStss,omitempty"`
	MemoryInfos          *Devm_MemoryInfos      `protobuf:"bytes,15,opt,name=memoryInfos,proto3" json:"memoryInfos,omitempty"`
	Ports                *Devm_Ports            `protobuf:"bytes,22,opt,name=ports,proto3" json:"ports,omitempty"`
	Fans                 *Devm_Fans             `protobuf:"bytes,24,opt,name=fans,proto3" json:"fans,omitempty"`
	TemperatureInfos     *Devm_TemperatureInfos `protobuf:"bytes,52,opt,name=temperatureInfos,proto3" json:"temperatureInfos,omitempty"`
	PowerSupplys         *Devm_PowerSupplys     `protobuf:"bytes,46,opt,name=powerSupplys,proto3" json:"powerSupplys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Devm) Reset()         { *m = Devm{} }
func (m *Devm) String() string { return proto.CompactTextString(m) }
func (*Devm) ProtoMessage()    {}
func (*Devm) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b727e00aa9f9628, []int{0}
}

func (m *Devm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devm.Unmarshal(m, b)
}
func (m *Devm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devm.Marshal(b, m, deterministic)
}
func (m *Devm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devm.Merge(m, src)
}
func (m *Devm) XXX_Size() int {
	return xxx_messageInfo_Devm.Size(m)
}
func (m *Devm) XXX_DiscardUnknown() {
	xxx_messageInfo_Devm.DiscardUnknown(m)
}

var xxx_messageInfo_Devm proto.InternalMessageInfo

func (m *Devm) GetCpuInfos() *Devm_CpuInfos {
	if m != nil {
		return m.CpuInfos
	}
	return nil
}

func (m *Devm) GetEthPortStaStss() *Devm_EthPortStaStss {
	if m != nil {
		return m.EthPortStaStss
	}
	return nil
}

func (m *Devm) GetMemoryInfos() *Devm_MemoryInfos {
	if m != nil {
		return m.MemoryInfos
	}
	return nil
}

func (m *Devm) GetPorts() *Devm_Ports {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *Devm) GetFans() *Devm_Fans {
	if m != nil {
		return m.Fans
	}
	return nil
}

func (m *Devm) GetTemperatureInfos() *Devm_TemperatureInfos {
	if m != nil {
		return m.TemperatureInfos
	}
	return nil
}

func (m *Devm) GetPowerSupplys() *Devm_PowerSupplys {
	if m != nil {
		return m.PowerSupplys
	}
	return nil
}

type Devm_CpuInfos struct {
	CpuInfo              []*Devm_CpuInfos_CpuInfo `protobuf:"bytes,1,rep,name=cpuInfo,proto3" json:"cpuInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Devm_CpuInfos) Reset()         { *m = Devm_CpuInfos{} }
func (m *Devm_CpuInfos) String() string { return proto.CompactTextString(m) }
func (*Devm_CpuInfos) ProtoMessage()    {}
func (*Devm_CpuInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b727e00aa9f9628, []int{0, 0}
}

func (m *Devm_CpuInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devm_CpuInfos.Unmarshal(m, b)
}
func (m *Devm_CpuInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devm_CpuInfos.Marshal(b, m, deterministic)
}
func (m *Devm_CpuInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devm_CpuInfos.Merge(m, src)
}
func (m *Devm_CpuInfos) XXX_Size() int {
	return xxx_messageInfo_Devm_CpuInfos.Size(m)
}
func (m *Devm_CpuInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_Devm_CpuInfos.DiscardUnknown(m)
}

var xxx_messageInfo_Devm_CpuInfos proto.InternalMessageInfo

func (m *Devm_CpuInfos) GetCpuInfo() []*Devm_CpuInfos_CpuInfo {
	if m != nil {
		return m.CpuInfo
	}
	return nil
}

type Devm_CpuInfos_CpuInfo struct {
	EntIndex             uint32   `protobuf:"varint,1,opt,name=entIndex,proto3" json:"entIndex,omitempty"`
	Interval             uint32   `protobuf:"varint,2,opt,name=interval,proto3" json:"interval,omitempty"`
	OvloadThreshold      uint32   `protobuf:"varint,3,opt,name=ovloadThreshold,proto3" json:"ovloadThreshold,omitempty"`
	Position             string   `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	SystemCpuUsage       uint32   `protobuf:"varint,5,opt,name=systemCpuUsage,proto3" json:"systemCpuUsage,omitempty"`
	UnovloadThreshold    uint32   `protobuf:"varint,6,opt,name=unovloadThreshold,proto3" json:"unovloadThreshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Devm_CpuInfos_CpuInfo) Reset()         { *m = Devm_CpuInfos_CpuInfo{} }
func (m *Devm_CpuInfos_CpuInfo) String() string { return proto.CompactTextString(m) }
func (*Devm_CpuInfos_CpuInfo) ProtoMessage()    {}
func (*Devm_CpuInfos_CpuInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b727e00aa9f9628, []int{0, 0, 0}
}

func (m *Devm_CpuInfos_CpuInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devm_CpuInfos_CpuInfo.Unmarshal(m, b)
}
func (m *Devm_CpuInfos_CpuInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devm_CpuInfos_CpuInfo.Marshal(b, m, deterministic)
}
func (m *Devm_CpuInfos_CpuInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devm_CpuInfos_CpuInfo.Merge(m, src)
}
func (m *Devm_CpuInfos_CpuInfo) XXX_Size() int {
	return xxx_messageInfo_Devm_CpuInfos_CpuInfo.Size(m)
}
func (m *Devm_CpuInfos_CpuInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Devm_CpuInfos_CpuInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Devm_CpuInfos_CpuInfo proto.InternalMessageInfo

func (m *Devm_CpuInfos_CpuInfo) GetEntIndex() uint32 {
	if m != nil {
		return m.EntIndex
	}
	return 0
}

func (m *Devm_CpuInfos_CpuInfo) GetInterval() uint32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *Devm_CpuInfos_CpuInfo) GetOvloadThreshold() uint32 {
	if m != nil {
		return m.OvloadThreshold
	}
	return 0
}

func (m *Devm_CpuInfos_CpuInfo) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *Devm_CpuInfos_CpuInfo) GetSystemCpuUsage() uint32 {
	if m != nil {
		return m.SystemCpuUsage
	}
	return 0
}

func (m *Devm_CpuInfos_CpuInfo) GetUnovloadThreshold() uint32 {
	if m != nil {
		return m.UnovloadThreshold
	}
	return 0
}

type Devm_EthPortStaStss struct {
	EthPortStaSts        []*Devm_EthPortStaStss_EthPortStaSts `protobuf:"bytes,1,rep,name=ethPortStaSts,proto3" json:"ethPortStaSts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *Devm_EthPortStaStss) Reset()         { *m = Devm_EthPortStaStss{} }
func (m *Devm_EthPortStaStss) String() string { return proto.CompactTextString(m) }
func (*Devm_EthPortStaStss) ProtoMessage()    {}
func (*Devm_EthPortStaStss) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b727e00aa9f9628, []int{0, 1}
}

func (m *Devm_EthPortStaStss) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devm_EthPortStaStss.Unmarshal(m, b)
}
func (m *Devm_EthPortStaStss) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devm_EthPortStaStss.Marshal(b, m, deterministic)
}
func (m *Devm_EthPortStaStss) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devm_EthPortStaStss.Merge(m, src)
}
func (m *Devm_EthPortStaStss) XXX_Size() int {
	return xxx_messageInfo_Devm_EthPortStaStss.Size(m)
}
func (m *Devm_EthPortStaStss) XXX_DiscardUnknown() {
	xxx_messageInfo_Devm_EthPortStaStss.DiscardUnknown(m)
}

var xxx_messageInfo_Devm_EthPortStaStss proto.InternalMessageInfo

func (m *Devm_EthPortStaStss) GetEthPortStaSts() []*Devm_EthPortStaStss_EthPortStaSts {
	if m != nil {
		return m.EthPortStaSts
	}
	return nil
}

type Devm_EthPortStaStss_EthPortStaSts struct {
	IfName               uint32   `protobuf:"varint,1,opt,name=ifName,proto3" json:"ifName,omitempty"`
	ReceiveByte          uint64   `protobuf:"varint,2,opt,name=receiveByte,proto3" json:"receiveByte,omitempty"`
	ReceivePacket        uint64   `protobuf:"varint,3,opt,name=receivePacket,proto3" json:"receivePacket,omitempty"`
	SendByte             uint64   `protobuf:"varint,4,opt,name=sendByte,proto3" json:"sendByte,omitempty"`
	SendPacket           uint64   `protobuf:"varint,5,opt,name=sendPacket,proto3" json:"sendPacket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Devm_EthPortStaStss_EthPortStaSts) Reset()         { *m = Devm_EthPortStaStss_EthPortStaSts{} }
func (m *Devm_EthPortStaStss_EthPortStaSts) String() string { return proto.CompactTextString(m) }
func (*Devm_EthPortStaStss_EthPortStaSts) ProtoMessage()    {}
func (*Devm_EthPortStaStss_EthPortStaSts) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b727e00aa9f9628, []int{0, 1, 0}
}

func (m *Devm_EthPortStaStss_EthPortStaSts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devm_EthPortStaStss_EthPortStaSts.Unmarshal(m, b)
}
func (m *Devm_EthPortStaStss_EthPortStaSts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devm_EthPortStaStss_EthPortStaSts.Marshal(b, m, deterministic)
}
func (m *Devm_EthPortStaStss_EthPortStaSts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devm_EthPortStaStss_EthPortStaSts.Merge(m, src)
}
func (m *Devm_EthPortStaStss_EthPortStaSts) XXX_Size() int {
	return xxx_messageInfo_Devm_EthPortStaStss_EthPortStaSts.Size(m)
}
func (m *Devm_EthPortStaStss_EthPortStaSts) XXX_DiscardUnknown() {
	xxx_messageInfo_Devm_EthPortStaStss_EthPortStaSts.DiscardUnknown(m)
}

var xxx_messageInfo_Devm_EthPortStaStss_EthPortStaSts proto.InternalMessageInfo

func (m *Devm_EthPortStaStss_EthPortStaSts) GetIfName() uint32 {
	if m != nil {
		return m.IfName
	}
	return 0
}

func (m *Devm_EthPortStaStss_EthPortStaSts) GetReceiveByte() uint64 {
	if m != nil {
		return m.ReceiveByte
	}
	return 0
}

func (m *Devm_EthPortStaStss_EthPortStaSts) GetReceivePacket() uint64 {
	if m != nil {
		return m.ReceivePacket
	}
	return 0
}

func (m *Devm_EthPortStaStss_EthPortStaSts) GetSendByte() uint64 {
	if m != nil {
		return m.SendByte
	}
	return 0
}

func (m *Devm_EthPortStaStss_EthPortStaSts) GetSendPacket() uint64 {
	if m != nil {
		return m.SendPacket
	}
	return 0
}

type Devm_MemoryInfos struct {
	MemoryInfo           []*Devm_MemoryInfos_MemoryInfo `protobuf:"bytes,1,rep,name=memoryInfo,proto3" json:"memoryInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *Devm_MemoryInfos) Reset()         { *m = Devm_MemoryInfos{} }
func (m *Devm_MemoryInfos) String() string { return proto.CompactTextString(m) }
func (*Devm_MemoryInfos) ProtoMessage()    {}
func (*Devm_MemoryInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b727e00aa9f9628, []int{0, 2}
}

func (m *Devm_MemoryInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devm_MemoryInfos.Unmarshal(m, b)
}
func (m *Devm_MemoryInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devm_MemoryInfos.Marshal(b, m, deterministic)
}
func (m *Devm_MemoryInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devm_MemoryInfos.Merge(m, src)
}
func (m *Devm_MemoryInfos) XXX_Size() int {
	return xxx_messageInfo_Devm_MemoryInfos.Size(m)
}
func (m *Devm_MemoryInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_Devm_MemoryInfos.DiscardUnknown(m)
}

var xxx_messageInfo_Devm_MemoryInfos proto.InternalMessageInfo

func (m *Devm_MemoryInfos) GetMemoryInfo() []*Devm_MemoryInfos_MemoryInfo {
	if m != nil {
		return m.MemoryInfo
	}
	return nil
}

type Devm_MemoryInfos_MemoryInfo struct {
	DoMemoryFree         uint32   `protobuf:"varint,1,opt,name=doMemoryFree,proto3" json:"doMemoryFree,omitempty"`
	DoMemoryTotal        uint32   `protobuf:"varint,2,opt,name=doMemoryTotal,proto3" json:"doMemoryTotal,omitempty"`
	DoMemoryUsage        uint32   `protobuf:"varint,3,opt,name=doMemoryUsage,proto3" json:"doMemoryUsage,omitempty"`
	DoMemoryUse          uint32   `protobuf:"varint,4,opt,name=doMemoryUse,proto3" json:"doMemoryUse,omitempty"`
	EntIndex             uint32   `protobuf:"varint,5,opt,name=entIndex,proto3" json:"entIndex,omitempty"`
	OsMemoryFree         uint32   `protobuf:"varint,6,opt,name=osMemoryFree,proto3" json:"osMemoryFree,omitempty"`
	OsMemoryTotal        uint32   `protobuf:"varint,7,opt,name=osMemoryTotal,proto3" json:"osMemoryTotal,omitempty"`
	OsMemoryUsage        uint32   `protobuf:"varint,8,opt,name=osMemoryUsage,proto3" json:"osMemoryUsage,omitempty"`
	OsMemoryUse          uint32   `protobuf:"varint,9,opt,name=osMemoryUse,proto3" json:"osMemoryUse,omitempty"`
	OvloadThreshold      uint32   `protobuf:"varint,10,opt,name=ovloadThreshold,proto3" json:"ovloadThreshold,omitempty"`
	Position             string   `protobuf:"bytes,11,opt,name=position,proto3" json:"position,omitempty"`
	SimpleMemoryFree     uint32   `protobuf:"varint,12,opt,name=simpleMemoryFree,proto3" json:"simpleMemoryFree,omitempty"`
	SimpleMemoryTotal    uint32   `protobuf:"varint,13,opt,name=simpleMemoryTotal,proto3" json:"simpleMemoryTotal,omitempty"`
	SimpleMemoryUsage    uint32   `protobuf:"varint,14,opt,name=simpleMemoryUsage,proto3" json:"simpleMemoryUsage,omitempty"`
	SimpleMemoryUse      uint32   `protobuf:"varint,15,opt,name=simpleMemoryUse,proto3" json:"simpleMemoryUse,omitempty"`
	UnovloadThreshold    uint32   `protobuf:"varint,16,opt,name=unovloadThreshold,proto3" json:"unovloadThreshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Devm_MemoryInfos_MemoryInfo) Reset()         { *m = Devm_MemoryInfos_MemoryInfo{} }
func (m *Devm_MemoryInfos_MemoryInfo) String() string { return proto.CompactTextString(m) }
func (*Devm_MemoryInfos_MemoryInfo) ProtoMessage()    {}
func (*Devm_MemoryInfos_MemoryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b727e00aa9f9628, []int{0, 2, 0}
}

func (m *Devm_MemoryInfos_MemoryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devm_MemoryInfos_MemoryInfo.Unmarshal(m, b)
}
func (m *Devm_MemoryInfos_MemoryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devm_MemoryInfos_MemoryInfo.Marshal(b, m, deterministic)
}
func (m *Devm_MemoryInfos_MemoryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devm_MemoryInfos_MemoryInfo.Merge(m, src)
}
func (m *Devm_MemoryInfos_MemoryInfo) XXX_Size() int {
	return xxx_messageInfo_Devm_MemoryInfos_MemoryInfo.Size(m)
}
func (m *Devm_MemoryInfos_MemoryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Devm_MemoryInfos_MemoryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Devm_MemoryInfos_MemoryInfo proto.InternalMessageInfo

func (m *Devm_MemoryInfos_MemoryInfo) GetDoMemoryFree() uint32 {
	if m != nil {
		return m.DoMemoryFree
	}
	return 0
}

func (m *Devm_MemoryInfos_MemoryInfo) GetDoMemoryTotal() uint32 {
	if m != nil {
		return m.DoMemoryTotal
	}
	return 0
}

func (m *Devm_MemoryInfos_MemoryInfo) GetDoMemoryUsage() uint32 {
	if m != nil {
		return m.DoMemoryUsage
	}
	return 0
}

func (m *Devm_MemoryInfos_MemoryInfo) GetDoMemoryUse() uint32 {
	if m != nil {
		return m.DoMemoryUse
	}
	return 0
}

func (m *Devm_MemoryInfos_MemoryInfo) GetEntIndex() uint32 {
	if m != nil {
		return m.EntIndex
	}
	return 0
}

func (m *Devm_MemoryInfos_MemoryInfo) GetOsMemoryFree() uint32 {
	if m != nil {
		return m.OsMemoryFree
	}
	return 0
}

func (m *Devm_MemoryInfos_MemoryInfo) GetOsMemoryTotal() uint32 {
	if m != nil {
		return m.OsMemoryTotal
	}
	return 0
}

func (m *Devm_MemoryInfos_MemoryInfo) GetOsMemoryUsage() uint32 {
	if m != nil {
		return m.OsMemoryUsage
	}
	return 0
}

func (m *Devm_MemoryInfos_MemoryInfo) GetOsMemoryUse() uint32 {
	if m != nil {
		return m.OsMemoryUse
	}
	return 0
}

func (m *Devm_MemoryInfos_MemoryInfo) GetOvloadThreshold() uint32 {
	if m != nil {
		return m.OvloadThreshold
	}
	return 0
}

func (m *Devm_MemoryInfos_MemoryInfo) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *Devm_MemoryInfos_MemoryInfo) GetSimpleMemoryFree() uint32 {
	if m != nil {
		return m.SimpleMemoryFree
	}
	return 0
}

func (m *Devm_MemoryInfos_MemoryInfo) GetSimpleMemoryTotal() uint32 {
	if m != nil {
		return m.SimpleMemoryTotal
	}
	return 0
}

func (m *Devm_MemoryInfos_MemoryInfo) GetSimpleMemoryUsage() uint32 {
	if m != nil {
		return m.SimpleMemoryUsage
	}
	return 0
}

func (m *Devm_MemoryInfos_MemoryInfo) GetSimpleMemoryUse() uint32 {
	if m != nil {
		return m.SimpleMemoryUse
	}
	return 0
}

func (m *Devm_MemoryInfos_MemoryInfo) GetUnovloadThreshold() uint32 {
	if m != nil {
		return m.UnovloadThreshold
	}
	return 0
}

type Devm_Ports struct {
	Port                 []*Devm_Ports_Port `protobuf:"bytes,1,rep,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Devm_Ports) Reset()         { *m = Devm_Ports{} }
func (m *Devm_Ports) String() string { return proto.CompactTextString(m) }
func (*Devm_Ports) ProtoMessage()    {}
func (*Devm_Ports) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b727e00aa9f9628, []int{0, 3}
}

func (m *Devm_Ports) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devm_Ports.Unmarshal(m, b)
}
func (m *Devm_Ports) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devm_Ports.Marshal(b, m, deterministic)
}
func (m *Devm_Ports) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devm_Ports.Merge(m, src)
}
func (m *Devm_Ports) XXX_Size() int {
	return xxx_messageInfo_Devm_Ports.Size(m)
}
func (m *Devm_Ports) XXX_DiscardUnknown() {
	xxx_messageInfo_Devm_Ports.DiscardUnknown(m)
}

var xxx_messageInfo_Devm_Ports proto.InternalMessageInfo

func (m *Devm_Ports) GetPort() []*Devm_Ports_Port {
	if m != nil {
		return m.Port
	}
	return nil
}

type Devm_Ports_Port struct {
	Position             string                       `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	EntIndex             uint32                       `protobuf:"varint,2,opt,name=entIndex,proto3" json:"entIndex,omitempty"`
	OpticalInfo          *Devm_Ports_Port_OpticalInfo `protobuf:"bytes,3,opt,name=opticalInfo,proto3" json:"opticalInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *Devm_Ports_Port) Reset()         { *m = Devm_Ports_Port{} }
func (m *Devm_Ports_Port) String() string { return proto.CompactTextString(m) }
func (*Devm_Ports_Port) ProtoMessage()    {}
func (*Devm_Ports_Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b727e00aa9f9628, []int{0, 3, 0}
}

func (m *Devm_Ports_Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devm_Ports_Port.Unmarshal(m, b)
}
func (m *Devm_Ports_Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devm_Ports_Port.Marshal(b, m, deterministic)
}
func (m *Devm_Ports_Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devm_Ports_Port.Merge(m, src)
}
func (m *Devm_Ports_Port) XXX_Size() int {
	return xxx_messageInfo_Devm_Ports_Port.Size(m)
}
func (m *Devm_Ports_Port) XXX_DiscardUnknown() {
	xxx_messageInfo_Devm_Ports_Port.DiscardUnknown(m)
}

var xxx_messageInfo_Devm_Ports_Port proto.InternalMessageInfo

func (m *Devm_Ports_Port) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *Devm_Ports_Port) GetEntIndex() uint32 {
	if m != nil {
		return m.EntIndex
	}
	return 0
}

func (m *Devm_Ports_Port) GetOpticalInfo() *Devm_Ports_Port_OpticalInfo {
	if m != nil {
		return m.OpticalInfo
	}
	return nil
}

type Devm_Ports_Port_OpticalInfo struct {
	TxPower              string   `protobuf:"bytes,1,opt,name=txPower,proto3" json:"txPower,omitempty"`
	RxPower              string   `protobuf:"bytes,2,opt,name=rxPower,proto3" json:"rxPower,omitempty"`
	OptBias              int32    `protobuf:"varint,3,opt,name=optBias,proto3" json:"optBias,omitempty"`
	OptVoltage           int32    `protobuf:"varint,4,opt,name=optVoltage,proto3" json:"optVoltage,omitempty"`
	OptTemperature       int32    `protobuf:"varint,5,opt,name=optTemperature,proto3" json:"optTemperature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Devm_Ports_Port_OpticalInfo) Reset()         { *m = Devm_Ports_Port_OpticalInfo{} }
func (m *Devm_Ports_Port_OpticalInfo) String() string { return proto.CompactTextString(m) }
func (*Devm_Ports_Port_OpticalInfo) ProtoMessage()    {}
func (*Devm_Ports_Port_OpticalInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b727e00aa9f9628, []int{0, 3, 0, 0}
}

func (m *Devm_Ports_Port_OpticalInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devm_Ports_Port_OpticalInfo.Unmarshal(m, b)
}
func (m *Devm_Ports_Port_OpticalInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devm_Ports_Port_OpticalInfo.Marshal(b, m, deterministic)
}
func (m *Devm_Ports_Port_OpticalInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devm_Ports_Port_OpticalInfo.Merge(m, src)
}
func (m *Devm_Ports_Port_OpticalInfo) XXX_Size() int {
	return xxx_messageInfo_Devm_Ports_Port_OpticalInfo.Size(m)
}
func (m *Devm_Ports_Port_OpticalInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Devm_Ports_Port_OpticalInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Devm_Ports_Port_OpticalInfo proto.InternalMessageInfo

func (m *Devm_Ports_Port_OpticalInfo) GetTxPower() string {
	if m != nil {
		return m.TxPower
	}
	return ""
}

func (m *Devm_Ports_Port_OpticalInfo) GetRxPower() string {
	if m != nil {
		return m.RxPower
	}
	return ""
}

func (m *Devm_Ports_Port_OpticalInfo) GetOptBias() int32 {
	if m != nil {
		return m.OptBias
	}
	return 0
}

func (m *Devm_Ports_Port_OpticalInfo) GetOptVoltage() int32 {
	if m != nil {
		return m.OptVoltage
	}
	return 0
}

func (m *Devm_Ports_Port_OpticalInfo) GetOptTemperature() int32 {
	if m != nil {
		return m.OptTemperature
	}
	return 0
}

type Devm_Fans struct {
	Fan                  []*Devm_Fans_Fan `protobuf:"bytes,1,rep,name=fan,proto3" json:"fan,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Devm_Fans) Reset()         { *m = Devm_Fans{} }
func (m *Devm_Fans) String() string { return proto.CompactTextString(m) }
func (*Devm_Fans) ProtoMessage()    {}
func (*Devm_Fans) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b727e00aa9f9628, []int{0, 4}
}

func (m *Devm_Fans) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devm_Fans.Unmarshal(m, b)
}
func (m *Devm_Fans) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devm_Fans.Marshal(b, m, deterministic)
}
func (m *Devm_Fans) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devm_Fans.Merge(m, src)
}
func (m *Devm_Fans) XXX_Size() int {
	return xxx_messageInfo_Devm_Fans.Size(m)
}
func (m *Devm_Fans) XXX_DiscardUnknown() {
	xxx_messageInfo_Devm_Fans.DiscardUnknown(m)
}

var xxx_messageInfo_Devm_Fans proto.InternalMessageInfo

func (m *Devm_Fans) GetFan() []*Devm_Fans_Fan {
	if m != nil {
		return m.Fan
	}
	return nil
}

type Devm_Fans_Fan struct {
	Position             string   `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Speed                uint32   `protobuf:"varint,2,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Devm_Fans_Fan) Reset()         { *m = Devm_Fans_Fan{} }
func (m *Devm_Fans_Fan) String() string { return proto.CompactTextString(m) }
func (*Devm_Fans_Fan) ProtoMessage()    {}
func (*Devm_Fans_Fan) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b727e00aa9f9628, []int{0, 4, 0}
}

func (m *Devm_Fans_Fan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devm_Fans_Fan.Unmarshal(m, b)
}
func (m *Devm_Fans_Fan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devm_Fans_Fan.Marshal(b, m, deterministic)
}
func (m *Devm_Fans_Fan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devm_Fans_Fan.Merge(m, src)
}
func (m *Devm_Fans_Fan) XXX_Size() int {
	return xxx_messageInfo_Devm_Fans_Fan.Size(m)
}
func (m *Devm_Fans_Fan) XXX_DiscardUnknown() {
	xxx_messageInfo_Devm_Fans_Fan.DiscardUnknown(m)
}

var xxx_messageInfo_Devm_Fans_Fan proto.InternalMessageInfo

func (m *Devm_Fans_Fan) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *Devm_Fans_Fan) GetSpeed() uint32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type Devm_TemperatureInfos struct {
	TemperatureInfo      []*Devm_TemperatureInfos_TemperatureInfo `protobuf:"bytes,1,rep,name=temperatureInfo,proto3" json:"temperatureInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *Devm_TemperatureInfos) Reset()         { *m = Devm_TemperatureInfos{} }
func (m *Devm_TemperatureInfos) String() string { return proto.CompactTextString(m) }
func (*Devm_TemperatureInfos) ProtoMessage()    {}
func (*Devm_TemperatureInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b727e00aa9f9628, []int{0, 5}
}

func (m *Devm_TemperatureInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devm_TemperatureInfos.Unmarshal(m, b)
}
func (m *Devm_TemperatureInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devm_TemperatureInfos.Marshal(b, m, deterministic)
}
func (m *Devm_TemperatureInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devm_TemperatureInfos.Merge(m, src)
}
func (m *Devm_TemperatureInfos) XXX_Size() int {
	return xxx_messageInfo_Devm_TemperatureInfos.Size(m)
}
func (m *Devm_TemperatureInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_Devm_TemperatureInfos.DiscardUnknown(m)
}

var xxx_messageInfo_Devm_TemperatureInfos proto.InternalMessageInfo

func (m *Devm_TemperatureInfos) GetTemperatureInfo() []*Devm_TemperatureInfos_TemperatureInfo {
	if m != nil {
		return m.TemperatureInfo
	}
	return nil
}

type Devm_TemperatureInfos_TemperatureInfo struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Channel              uint32   `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Position             string   `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	I2C                  uint32   `protobuf:"varint,4,opt,name=i2c,proto3" json:"i2c,omitempty"`
	CurrentTemperature   int32    `protobuf:"varint,5,opt,name=currentTemperature,proto3" json:"currentTemperature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Devm_TemperatureInfos_TemperatureInfo) Reset()         { *m = Devm_TemperatureInfos_TemperatureInfo{} }
func (m *Devm_TemperatureInfos_TemperatureInfo) String() string { return proto.CompactTextString(m) }
func (*Devm_TemperatureInfos_TemperatureInfo) ProtoMessage()    {}
func (*Devm_TemperatureInfos_TemperatureInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b727e00aa9f9628, []int{0, 5, 0}
}

func (m *Devm_TemperatureInfos_TemperatureInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devm_TemperatureInfos_TemperatureInfo.Unmarshal(m, b)
}
func (m *Devm_TemperatureInfos_TemperatureInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devm_TemperatureInfos_TemperatureInfo.Marshal(b, m, deterministic)
}
func (m *Devm_TemperatureInfos_TemperatureInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devm_TemperatureInfos_TemperatureInfo.Merge(m, src)
}
func (m *Devm_TemperatureInfos_TemperatureInfo) XXX_Size() int {
	return xxx_messageInfo_Devm_TemperatureInfos_TemperatureInfo.Size(m)
}
func (m *Devm_TemperatureInfos_TemperatureInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Devm_TemperatureInfos_TemperatureInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Devm_TemperatureInfos_TemperatureInfo proto.InternalMessageInfo

func (m *Devm_TemperatureInfos_TemperatureInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Devm_TemperatureInfos_TemperatureInfo) GetChannel() uint32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *Devm_TemperatureInfos_TemperatureInfo) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *Devm_TemperatureInfos_TemperatureInfo) GetI2C() uint32 {
	if m != nil {
		return m.I2C
	}
	return 0
}

func (m *Devm_TemperatureInfos_TemperatureInfo) GetCurrentTemperature() int32 {
	if m != nil {
		return m.CurrentTemperature
	}
	return 0
}

type Devm_PowerSupplys struct {
	PowerSupply          []*Devm_PowerSupplys_PowerSupply `protobuf:"bytes,1,rep,name=powerSupply,proto3" json:"powerSupply,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *Devm_PowerSupplys) Reset()         { *m = Devm_PowerSupplys{} }
func (m *Devm_PowerSupplys) String() string { return proto.CompactTextString(m) }
func (*Devm_PowerSupplys) ProtoMessage()    {}
func (*Devm_PowerSupplys) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b727e00aa9f9628, []int{0, 6}
}

func (m *Devm_PowerSupplys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devm_PowerSupplys.Unmarshal(m, b)
}
func (m *Devm_PowerSupplys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devm_PowerSupplys.Marshal(b, m, deterministic)
}
func (m *Devm_PowerSupplys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devm_PowerSupplys.Merge(m, src)
}
func (m *Devm_PowerSupplys) XXX_Size() int {
	return xxx_messageInfo_Devm_PowerSupplys.Size(m)
}
func (m *Devm_PowerSupplys) XXX_DiscardUnknown() {
	xxx_messageInfo_Devm_PowerSupplys.DiscardUnknown(m)
}

var xxx_messageInfo_Devm_PowerSupplys proto.InternalMessageInfo

func (m *Devm_PowerSupplys) GetPowerSupply() []*Devm_PowerSupplys_PowerSupply {
	if m != nil {
		return m.PowerSupply
	}
	return nil
}

type Devm_PowerSupplys_PowerSupply struct {
	Position             string                                           `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	PowerEnvironments    *Devm_PowerSupplys_PowerSupply_PowerEnvironments `protobuf:"bytes,7,opt,name=powerEnvironments,proto3" json:"powerEnvironments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                         `json:"-"`
	XXX_unrecognized     []byte                                           `json:"-"`
	XXX_sizecache        int32                                            `json:"-"`
}

func (m *Devm_PowerSupplys_PowerSupply) Reset()         { *m = Devm_PowerSupplys_PowerSupply{} }
func (m *Devm_PowerSupplys_PowerSupply) String() string { return proto.CompactTextString(m) }
func (*Devm_PowerSupplys_PowerSupply) ProtoMessage()    {}
func (*Devm_PowerSupplys_PowerSupply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b727e00aa9f9628, []int{0, 6, 0}
}

func (m *Devm_PowerSupplys_PowerSupply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devm_PowerSupplys_PowerSupply.Unmarshal(m, b)
}
func (m *Devm_PowerSupplys_PowerSupply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devm_PowerSupplys_PowerSupply.Marshal(b, m, deterministic)
}
func (m *Devm_PowerSupplys_PowerSupply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devm_PowerSupplys_PowerSupply.Merge(m, src)
}
func (m *Devm_PowerSupplys_PowerSupply) XXX_Size() int {
	return xxx_messageInfo_Devm_PowerSupplys_PowerSupply.Size(m)
}
func (m *Devm_PowerSupplys_PowerSupply) XXX_DiscardUnknown() {
	xxx_messageInfo_Devm_PowerSupplys_PowerSupply.DiscardUnknown(m)
}

var xxx_messageInfo_Devm_PowerSupplys_PowerSupply proto.InternalMessageInfo

func (m *Devm_PowerSupplys_PowerSupply) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *Devm_PowerSupplys_PowerSupply) GetPowerEnvironments() *Devm_PowerSupplys_PowerSupply_PowerEnvironments {
	if m != nil {
		return m.PowerEnvironments
	}
	return nil
}

type Devm_PowerSupplys_PowerSupply_PowerEnvironments struct {
	PowerEnvironment     []*Devm_PowerSupplys_PowerSupply_PowerEnvironments_PowerEnvironment `protobuf:"bytes,1,rep,name=powerEnvironment,proto3" json:"powerEnvironment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                            `json:"-"`
	XXX_unrecognized     []byte                                                              `json:"-"`
	XXX_sizecache        int32                                                               `json:"-"`
}

func (m *Devm_PowerSupplys_PowerSupply_PowerEnvironments) Reset() {
	*m = Devm_PowerSupplys_PowerSupply_PowerEnvironments{}
}
func (m *Devm_PowerSupplys_PowerSupply_PowerEnvironments) String() string {
	return proto.CompactTextString(m)
}
func (*Devm_PowerSupplys_PowerSupply_PowerEnvironments) ProtoMessage() {}
func (*Devm_PowerSupplys_PowerSupply_PowerEnvironments) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b727e00aa9f9628, []int{0, 6, 0, 0}
}

func (m *Devm_PowerSupplys_PowerSupply_PowerEnvironments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devm_PowerSupplys_PowerSupply_PowerEnvironments.Unmarshal(m, b)
}
func (m *Devm_PowerSupplys_PowerSupply_PowerEnvironments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devm_PowerSupplys_PowerSupply_PowerEnvironments.Marshal(b, m, deterministic)
}
func (m *Devm_PowerSupplys_PowerSupply_PowerEnvironments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devm_PowerSupplys_PowerSupply_PowerEnvironments.Merge(m, src)
}
func (m *Devm_PowerSupplys_PowerSupply_PowerEnvironments) XXX_Size() int {
	return xxx_messageInfo_Devm_PowerSupplys_PowerSupply_PowerEnvironments.Size(m)
}
func (m *Devm_PowerSupplys_PowerSupply_PowerEnvironments) XXX_DiscardUnknown() {
	xxx_messageInfo_Devm_PowerSupplys_PowerSupply_PowerEnvironments.DiscardUnknown(m)
}

var xxx_messageInfo_Devm_PowerSupplys_PowerSupply_PowerEnvironments proto.InternalMessageInfo

func (m *Devm_PowerSupplys_PowerSupply_PowerEnvironments) GetPowerEnvironment() []*Devm_PowerSupplys_PowerSupply_PowerEnvironments_PowerEnvironment {
	if m != nil {
		return m.PowerEnvironment
	}
	return nil
}

type Devm_PowerSupplys_PowerSupply_PowerEnvironments_PowerEnvironment struct {
	PemIndex             uint32   `protobuf:"varint,1,opt,name=pemIndex,proto3" json:"pemIndex,omitempty"`
	PowerValue           string   `protobuf:"bytes,2,opt,name=powerValue,proto3" json:"powerValue,omitempty"`
	VoltageValue         string   `protobuf:"bytes,3,opt,name=voltageValue,proto3" json:"voltageValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Devm_PowerSupplys_PowerSupply_PowerEnvironments_PowerEnvironment) Reset() {
	*m = Devm_PowerSupplys_PowerSupply_PowerEnvironments_PowerEnvironment{}
}
func (m *Devm_PowerSupplys_PowerSupply_PowerEnvironments_PowerEnvironment) String() string {
	return proto.CompactTextString(m)
}
func (*Devm_PowerSupplys_PowerSupply_PowerEnvironments_PowerEnvironment) ProtoMessage() {}
func (*Devm_PowerSupplys_PowerSupply_PowerEnvironments_PowerEnvironment) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b727e00aa9f9628, []int{0, 6, 0, 0, 0}
}

func (m *Devm_PowerSupplys_PowerSupply_PowerEnvironments_PowerEnvironment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devm_PowerSupplys_PowerSupply_PowerEnvironments_PowerEnvironment.Unmarshal(m, b)
}
func (m *Devm_PowerSupplys_PowerSupply_PowerEnvironments_PowerEnvironment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devm_PowerSupplys_PowerSupply_PowerEnvironments_PowerEnvironment.Marshal(b, m, deterministic)
}
func (m *Devm_PowerSupplys_PowerSupply_PowerEnvironments_PowerEnvironment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devm_PowerSupplys_PowerSupply_PowerEnvironments_PowerEnvironment.Merge(m, src)
}
func (m *Devm_PowerSupplys_PowerSupply_PowerEnvironments_PowerEnvironment) XXX_Size() int {
	return xxx_messageInfo_Devm_PowerSupplys_PowerSupply_PowerEnvironments_PowerEnvironment.Size(m)
}
func (m *Devm_PowerSupplys_PowerSupply_PowerEnvironments_PowerEnvironment) XXX_DiscardUnknown() {
	xxx_messageInfo_Devm_PowerSupplys_PowerSupply_PowerEnvironments_PowerEnvironment.DiscardUnknown(m)
}

var xxx_messageInfo_Devm_PowerSupplys_PowerSupply_PowerEnvironments_PowerEnvironment proto.InternalMessageInfo

func (m *Devm_PowerSupplys_PowerSupply_PowerEnvironments_PowerEnvironment) GetPemIndex() uint32 {
	if m != nil {
		return m.PemIndex
	}
	return 0
}

func (m *Devm_PowerSupplys_PowerSupply_PowerEnvironments_PowerEnvironment) GetPowerValue() string {
	if m != nil {
		return m.PowerValue
	}
	return ""
}

func (m *Devm_PowerSupplys_PowerSupply_PowerEnvironments_PowerEnvironment) GetVoltageValue() string {
	if m != nil {
		return m.VoltageValue
	}
	return ""
}

func init() {
	proto.RegisterType((*Devm)(nil), "huawei_devm.Devm")
	proto.RegisterType((*Devm_CpuInfos)(nil), "huawei_devm.Devm.CpuInfos")
	proto.RegisterType((*Devm_CpuInfos_CpuInfo)(nil), "huawei_devm.Devm.CpuInfos.CpuInfo")
	proto.RegisterType((*Devm_EthPortStaStss)(nil), "huawei_devm.Devm.EthPortStaStss")
	proto.RegisterType((*Devm_EthPortStaStss_EthPortStaSts)(nil), "huawei_devm.Devm.EthPortStaStss.EthPortStaSts")
	proto.RegisterType((*Devm_MemoryInfos)(nil), "huawei_devm.Devm.MemoryInfos")
	proto.RegisterType((*Devm_MemoryInfos_MemoryInfo)(nil), "huawei_devm.Devm.MemoryInfos.MemoryInfo")
	proto.RegisterType((*Devm_Ports)(nil), "huawei_devm.Devm.Ports")
	proto.RegisterType((*Devm_Ports_Port)(nil), "huawei_devm.Devm.Ports.Port")
	proto.RegisterType((*Devm_Ports_Port_OpticalInfo)(nil), "huawei_devm.Devm.Ports.Port.OpticalInfo")
	proto.RegisterType((*Devm_Fans)(nil), "huawei_devm.Devm.Fans")
	proto.RegisterType((*Devm_Fans_Fan)(nil), "huawei_devm.Devm.Fans.Fan")
	proto.RegisterType((*Devm_TemperatureInfos)(nil), "huawei_devm.Devm.TemperatureInfos")
	proto.RegisterType((*Devm_TemperatureInfos_TemperatureInfo)(nil), "huawei_devm.Devm.TemperatureInfos.TemperatureInfo")
	proto.RegisterType((*Devm_PowerSupplys)(nil), "huawei_devm.Devm.PowerSupplys")
	proto.RegisterType((*Devm_PowerSupplys_PowerSupply)(nil), "huawei_devm.Devm.PowerSupplys.PowerSupply")
	proto.RegisterType((*Devm_PowerSupplys_PowerSupply_PowerEnvironments)(nil), "huawei_devm.Devm.PowerSupplys.PowerSupply.PowerEnvironments")
	proto.RegisterType((*Devm_PowerSupplys_PowerSupply_PowerEnvironments_PowerEnvironment)(nil), "huawei_devm.Devm.PowerSupplys.PowerSupply.PowerEnvironments.PowerEnvironment")
}

func init() { proto.RegisterFile("huawei-devm.proto", fileDescriptor_7b727e00aa9f9628) }

var fileDescriptor_7b727e00aa9f9628 = []byte{
	// 1017 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcf, 0x8e, 0x1b, 0x45,
	0x13, 0x97, 0x3d, 0xe3, 0xf5, 0xa6, 0xc6, 0x5e, 0x7b, 0x5b, 0x9f, 0x36, 0xa3, 0xd6, 0x47, 0x64,
	0xad, 0x10, 0xb2, 0x56, 0x89, 0x85, 0x16, 0x04, 0x97, 0x48, 0x48, 0x1b, 0xb2, 0x4a, 0x10, 0x09,
	0x51, 0xef, 0x92, 0x13, 0x12, 0x1a, 0xec, 0x5e, 0x3c, 0xe0, 0x99, 0x1e, 0x75, 0xb7, 0x9d, 0xf8,
	0xca, 0x33, 0x20, 0x0e, 0x5c, 0xb9, 0x20, 0x71, 0xe1, 0x01, 0x78, 0x04, 0x5e, 0x81, 0x37, 0xe0,
	0xc4, 0x8d, 0x1b, 0xea, 0x3f, 0x63, 0x77, 0xf7, 0x38, 0x5e, 0x24, 0x2e, 0xa3, 0xa9, 0x5f, 0xfd,
	0xaa, 0xba, 0xba, 0xba, 0xaa, 0xab, 0xe1, 0x78, 0xbe, 0xcc, 0x5e, 0xd1, 0xfc, 0xc1, 0x8c, 0xae,
	0x8a, 0x49, 0xc5, 0x99, 0x64, 0x28, 0x31, 0xd0, 0x97, 0x0a, 0x3a, 0xfd, 0xed, 0x2e, 0xc4, 0x1f,
	0xd3, 0x55, 0x81, 0x3e, 0x80, 0xc3, 0x69, 0xb5, 0x7c, 0x5a, 0xde, 0x30, 0x91, 0x76, 0x46, 0xad,
	0x71, 0x72, 0x8e, 0x27, 0x0e, 0x71, 0xa2, 0x48, 0x93, 0x47, 0x96, 0x41, 0x36, 0x5c, 0xf4, 0x04,
	0x8e, 0xa8, 0x9c, 0xbf, 0x60, 0x5c, 0x5e, 0xc9, 0xec, 0x4a, 0x0a, 0x91, 0x76, 0xb5, 0xf5, 0xa8,
	0x69, 0xfd, 0xd8, 0xe3, 0x91, 0xc0, 0x0e, 0x7d, 0x04, 0x49, 0x41, 0x0b, 0xc6, 0xd7, 0x26, 0x88,
	0x81, 0x76, 0xf3, 0x56, 0xd3, 0xcd, 0xb3, 0x2d, 0x89, 0xb8, 0x16, 0xe8, 0x01, 0x74, 0x2a, 0xc6,
	0xa5, 0x48, 0x4f, 0xb4, 0xe9, 0xdd, 0xa6, 0xa9, 0x5a, 0x4e, 0x10, 0xc3, 0x42, 0x67, 0x10, 0xdf,
	0x64, 0xa5, 0x48, 0x53, 0xcd, 0x3e, 0x69, 0xb2, 0x2f, 0xb3, 0x52, 0x10, 0xcd, 0x41, 0xcf, 0x61,
	0x28, 0x69, 0x51, 0x51, 0x9e, 0xc9, 0x25, 0xa7, 0x26, 0xc0, 0xf7, 0xb5, 0xdd, 0x69, 0xd3, 0xee,
	0x3a, 0x60, 0x92, 0x86, 0x2d, 0xba, 0x80, 0x5e, 0xc5, 0x5e, 0x51, 0x7e, 0xb5, 0xac, 0xaa, 0xc5,
	0x5a, 0xa4, 0x13, 0xed, 0xeb, 0xde, 0xae, 0x88, 0xb7, 0x2c, 0xe2, 0xd9, 0xe0, 0x9f, 0xdb, 0x70,
	0x58, 0x1f, 0x08, 0x7a, 0x08, 0x5d, 0x7b, 0x24, 0x69, 0x6b, 0x14, 0xed, 0x8e, 0xab, 0x26, 0xd7,
	0x3f, 0xa4, 0x36, 0xc1, 0x7f, 0xb4, 0xa0, 0x6b, 0x41, 0x84, 0xe1, 0x90, 0x96, 0xf2, 0x69, 0x39,
	0xa3, 0xaf, 0xd3, 0xd6, 0xa8, 0x35, 0xee, 0x93, 0x8d, 0xac, 0x74, 0x79, 0x29, 0x29, 0x5f, 0x65,
	0x8b, 0xb4, 0x6d, 0x74, 0xb5, 0x8c, 0xc6, 0x30, 0x60, 0xab, 0x05, 0xcb, 0x66, 0xd7, 0x73, 0x4e,
	0xc5, 0x9c, 0x2d, 0x66, 0x69, 0xa4, 0x29, 0x21, 0xac, 0xbc, 0x54, 0x4c, 0xe4, 0x32, 0x67, 0x65,
	0x1a, 0x8f, 0x5a, 0xe3, 0x3b, 0x64, 0x23, 0xa3, 0x77, 0xe0, 0x48, 0xac, 0x85, 0xa4, 0xc5, 0xa3,
	0x6a, 0xf9, 0xb9, 0xc8, 0xbe, 0xa6, 0xba, 0x18, 0xfb, 0x24, 0x40, 0xd1, 0x7d, 0x38, 0x5e, 0x96,
	0xe1, 0x7a, 0x07, 0x9a, 0xda, 0x54, 0xe0, 0xef, 0xdb, 0x70, 0xe4, 0x57, 0x1f, 0xba, 0x86, 0xbe,
	0x57, 0x7f, 0x36, 0x6d, 0x93, 0xdb, 0xca, 0xd6, 0x17, 0x89, 0xef, 0x04, 0xff, 0xd2, 0x82, 0xbe,
	0x47, 0x40, 0x27, 0x70, 0x90, 0xdf, 0x3c, 0xcf, 0x0a, 0x6a, 0x93, 0x69, 0x25, 0x34, 0x82, 0x84,
	0xd3, 0x29, 0xcd, 0x57, 0xf4, 0x62, 0x2d, 0xa9, 0xce, 0x66, 0x4c, 0x5c, 0x08, 0xbd, 0x0d, 0x7d,
	0x2b, 0xbe, 0xc8, 0xa6, 0xdf, 0x52, 0xa9, 0xd3, 0x19, 0x13, 0x1f, 0x54, 0xc9, 0x14, 0xb4, 0x9c,
	0x69, 0x27, 0xb1, 0x26, 0x6c, 0x64, 0x74, 0x0f, 0x40, 0xfd, 0x5b, 0xf3, 0x8e, 0xd6, 0x3a, 0x08,
	0xfe, 0xbd, 0x03, 0x89, 0xd3, 0x4d, 0xe8, 0x09, 0xc0, 0xb6, 0x9f, 0x6c, 0x42, 0xc6, 0x7b, 0x1b,
	0xd0, 0xf9, 0x27, 0x8e, 0x2d, 0xfe, 0x2b, 0x06, 0xd8, 0xaa, 0xd0, 0x29, 0xf4, 0x66, 0xcc, 0xc8,
	0x97, 0x9c, 0xd6, 0xa9, 0xf0, 0x30, 0xb5, 0xdd, 0x5a, 0xbe, 0x66, 0x72, 0x53, 0x60, 0x3e, 0xe8,
	0xb2, 0x4c, 0x79, 0x44, 0x3e, 0xcb, 0x54, 0xc7, 0x08, 0x92, 0x2d, 0x60, 0xf2, 0xd2, 0x27, 0x2e,
	0xe4, 0x55, 0x79, 0x27, 0xa8, 0xf2, 0x53, 0xe8, 0x31, 0xe1, 0x44, 0x6b, 0xca, 0xca, 0xc3, 0x54,
	0x1c, 0xb5, 0x6c, 0xa2, 0xed, 0x9a, 0x38, 0x3c, 0xd0, 0x65, 0x99, 0x68, 0x0f, 0x7d, 0xd6, 0x26,
	0xda, 0x2d, 0x40, 0xd3, 0x3b, 0x26, 0x5a, 0x07, 0xda, 0xd5, 0x5b, 0x70, 0x7b, 0x6f, 0x25, 0x41,
	0x6f, 0x9d, 0xc1, 0x50, 0xe4, 0x45, 0xb5, 0xa0, 0xce, 0xde, 0x7a, 0xda, 0x4d, 0x03, 0x57, 0xfd,
	0xe5, 0x62, 0x66, 0x8f, 0x7d, 0xd3, 0x5f, 0x0d, 0x45, 0xc8, 0x36, 0x7b, 0x3d, 0x6a, 0xb2, 0xcd,
	0x7e, 0xc7, 0x30, 0xf0, 0x41, 0xaa, 0x2f, 0xfb, 0x3e, 0x09, 0xe1, 0xdd, 0x5d, 0x3e, 0x7c, 0x53,
	0x97, 0xff, 0xd9, 0x86, 0x8e, 0xbe, 0xe1, 0xd1, 0xbb, 0x10, 0xab, 0x3b, 0xde, 0x96, 0xf0, 0xff,
	0xdf, 0x30, 0x08, 0xf4, 0x97, 0x68, 0x26, 0xfe, 0xb5, 0x0d, 0xb1, 0x12, 0xbd, 0x04, 0xb6, 0x82,
	0x04, 0xba, 0x45, 0xd3, 0x0e, 0x8a, 0xe6, 0x13, 0x48, 0x58, 0x25, 0xf3, 0x69, 0xb6, 0xd0, 0xcd,
	0x13, 0xe9, 0x0b, 0x7d, 0xbc, 0x6f, 0xe5, 0xc9, 0x67, 0x5b, 0x3e, 0x71, 0x8d, 0xf1, 0x4f, 0x2d,
	0x48, 0x1c, 0x25, 0x4a, 0xa1, 0x2b, 0x5f, 0xeb, 0x49, 0x60, 0x43, 0xaa, 0x45, 0xa5, 0xe1, 0x56,
	0xd3, 0x36, 0x1a, 0xbe, 0xd5, 0xb0, 0x4a, 0x5e, 0xe4, 0x99, 0xd0, 0xb1, 0x74, 0x48, 0x2d, 0xaa,
	0x5b, 0x81, 0x55, 0xf2, 0x25, 0x5b, 0x48, 0x75, 0x4a, 0xb1, 0x56, 0x3a, 0x88, 0xba, 0x82, 0x59,
	0x25, 0x9d, 0x21, 0xa6, 0x1b, 0xa4, 0x43, 0x02, 0x14, 0x17, 0x10, 0xab, 0x09, 0x89, 0xee, 0x43,
	0x74, 0x93, 0x95, 0x36, 0xd7, 0x78, 0xf7, 0x18, 0x55, 0x1f, 0xa2, 0x68, 0xf8, 0x43, 0x88, 0x2e,
	0xb3, 0x72, 0x6f, 0x9a, 0xff, 0x07, 0x1d, 0x51, 0x51, 0x3a, 0xb3, 0x39, 0x36, 0x02, 0xfe, 0xa1,
	0x0d, 0xc3, 0x70, 0xb2, 0xa2, 0x2f, 0x60, 0x10, 0xcc, 0x56, 0x1b, 0xc7, 0xf9, 0xed, 0x63, 0x39,
	0x04, 0x48, 0xe8, 0x4a, 0x9d, 0xc3, 0x20, 0x20, 0xa9, 0xbc, 0x66, 0xb3, 0x19, 0xa7, 0x42, 0xd4,
	0x67, 0x61, 0x45, 0xa5, 0x99, 0xce, 0xb3, 0xb2, 0xa4, 0xf5, 0xd5, 0x55, 0x8b, 0xde, 0x66, 0xa3,
	0x60, 0xb3, 0x43, 0x88, 0xf2, 0xf3, 0xa9, 0xbd, 0xa2, 0xd4, 0x2f, 0x9a, 0x00, 0x9a, 0x2e, 0x39,
	0xa7, 0xe5, 0x8e, 0x33, 0xd8, 0xa1, 0xc1, 0x7f, 0x47, 0xd0, 0x73, 0x9f, 0x09, 0xe8, 0x53, 0x48,
	0x9c, 0x87, 0x82, 0x4d, 0xc8, 0xd9, 0xfe, 0xb7, 0x85, 0x2b, 0x10, 0xd7, 0x1c, 0xff, 0x18, 0x41,
	0xe2, 0x28, 0xf7, 0x9e, 0xdc, 0x37, 0x70, 0xac, 0x4d, 0x1f, 0x97, 0xab, 0x9c, 0xb3, 0xb2, 0xa0,
	0xa5, 0xac, 0xdf, 0x83, 0x0f, 0xff, 0xfd, 0xfa, 0xe6, 0xdf, 0xf5, 0x41, 0x9a, 0x6e, 0xf1, 0x77,
	0x6d, 0x38, 0x6e, 0x10, 0xd1, 0x1a, 0x86, 0x21, 0xd5, 0x26, 0xe0, 0xd9, 0x7f, 0x09, 0xa0, 0x81,
	0x90, 0xc6, 0x32, 0x98, 0xc3, 0x30, 0x64, 0xe9, 0x64, 0xd1, 0xc2, 0x7b, 0x4c, 0xd5, 0xb2, 0xea,
	0x43, 0xed, 0xe3, 0x65, 0xb6, 0x58, 0x52, 0xdb, 0xbe, 0x0e, 0xa2, 0xc6, 0xd0, 0xca, 0xb4, 0xa4,
	0x61, 0x98, 0xca, 0xf1, 0xb0, 0xaf, 0x0e, 0xf4, 0x93, 0xfe, 0xbd, 0x7f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xcc, 0x9f, 0xfe, 0xcb, 0xe7, 0x0b, 0x00, 0x00,
}
