// Code generated by protoc-gen-go. DO NOT EDIT.
// source: huawei-isis.proto

package huawei_isiscomm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResetIsisRequest struct {
	InstanceId           uint32   `protobuf:"varint,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetIsisRequest) Reset()         { *m = ResetIsisRequest{} }
func (m *ResetIsisRequest) String() string { return proto.CompactTextString(m) }
func (*ResetIsisRequest) ProtoMessage()    {}
func (*ResetIsisRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_36cfa8814ced46bb, []int{0}
}

func (m *ResetIsisRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetIsisRequest.Unmarshal(m, b)
}
func (m *ResetIsisRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetIsisRequest.Marshal(b, m, deterministic)
}
func (m *ResetIsisRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetIsisRequest.Merge(m, src)
}
func (m *ResetIsisRequest) XXX_Size() int {
	return xxx_messageInfo_ResetIsisRequest.Size(m)
}
func (m *ResetIsisRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetIsisRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetIsisRequest proto.InternalMessageInfo

func (m *ResetIsisRequest) GetInstanceId() uint32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

type ResetIsisPeerRequest struct {
	InstanceId           uint32   `protobuf:"varint,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	SystemId             string   `protobuf:"bytes,2,opt,name=systemId,proto3" json:"systemId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetIsisPeerRequest) Reset()         { *m = ResetIsisPeerRequest{} }
func (m *ResetIsisPeerRequest) String() string { return proto.CompactTextString(m) }
func (*ResetIsisPeerRequest) ProtoMessage()    {}
func (*ResetIsisPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_36cfa8814ced46bb, []int{1}
}

func (m *ResetIsisPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetIsisPeerRequest.Unmarshal(m, b)
}
func (m *ResetIsisPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetIsisPeerRequest.Marshal(b, m, deterministic)
}
func (m *ResetIsisPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetIsisPeerRequest.Merge(m, src)
}
func (m *ResetIsisPeerRequest) XXX_Size() int {
	return xxx_messageInfo_ResetIsisPeerRequest.Size(m)
}
func (m *ResetIsisPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetIsisPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetIsisPeerRequest proto.InternalMessageInfo

func (m *ResetIsisPeerRequest) GetInstanceId() uint32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

func (m *ResetIsisPeerRequest) GetSystemId() string {
	if m != nil {
		return m.SystemId
	}
	return ""
}

type ResetSuppressPeerRequest struct {
	IfName               string   `protobuf:"bytes,1,opt,name=ifName,proto3" json:"ifName,omitempty"`
	InstanceId           uint32   `protobuf:"varint,2,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	NotifyPeer           bool     `protobuf:"varint,3,opt,name=notifyPeer,proto3" json:"notifyPeer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetSuppressPeerRequest) Reset()         { *m = ResetSuppressPeerRequest{} }
func (m *ResetSuppressPeerRequest) String() string { return proto.CompactTextString(m) }
func (*ResetSuppressPeerRequest) ProtoMessage()    {}
func (*ResetSuppressPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_36cfa8814ced46bb, []int{2}
}

func (m *ResetSuppressPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetSuppressPeerRequest.Unmarshal(m, b)
}
func (m *ResetSuppressPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetSuppressPeerRequest.Marshal(b, m, deterministic)
}
func (m *ResetSuppressPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetSuppressPeerRequest.Merge(m, src)
}
func (m *ResetSuppressPeerRequest) XXX_Size() int {
	return xxx_messageInfo_ResetSuppressPeerRequest.Size(m)
}
func (m *ResetSuppressPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetSuppressPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetSuppressPeerRequest proto.InternalMessageInfo

func (m *ResetSuppressPeerRequest) GetIfName() string {
	if m != nil {
		return m.IfName
	}
	return ""
}

func (m *ResetSuppressPeerRequest) GetInstanceId() uint32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

func (m *ResetSuppressPeerRequest) GetNotifyPeer() bool {
	if m != nil {
		return m.NotifyPeer
	}
	return false
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_36cfa8814ced46bb, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type IsisAdjacencyChange struct {
	HwIsisAdjChgSubReason string   `protobuf:"bytes,2,opt,name=HwIsisAdjChgSubReason,proto3" json:"HwIsisAdjChgSubReason,omitempty"`
	IfIndex               int32    `protobuf:"varint,3,opt,name=IfIndex,proto3" json:"IfIndex,omitempty"`
	IfName                string   `protobuf:"bytes,4,opt,name=IfName,proto3" json:"IfName,omitempty"`
	IsisAdjState          int32    `protobuf:"varint,5,opt,name=IsisAdjState,proto3" json:"IsisAdjState,omitempty"`
	IsisCircIfIndex       int32    `protobuf:"varint,6,opt,name=IsisCircIfIndex,proto3" json:"IsisCircIfIndex,omitempty"`
	IsisCircIndex         int32    `protobuf:"varint,7,opt,name=IsisCircIndex,proto3" json:"IsisCircIndex,omitempty"`
	IsisPduLspId          string   `protobuf:"bytes,8,opt,name=IsisPduLspId,proto3" json:"IsisPduLspId,omitempty"`
	IsisSysInstance       uint32   `protobuf:"varint,9,opt,name=IsisSysInstance,proto3" json:"IsisSysInstance,omitempty"`
	IsisSysLevelIndex     int32    `protobuf:"varint,10,opt,name=IsisSysLevelIndex,proto3" json:"IsisSysLevelIndex,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *IsisAdjacencyChange) Reset()         { *m = IsisAdjacencyChange{} }
func (m *IsisAdjacencyChange) String() string { return proto.CompactTextString(m) }
func (*IsisAdjacencyChange) ProtoMessage()    {}
func (*IsisAdjacencyChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_36cfa8814ced46bb, []int{4}
}

func (m *IsisAdjacencyChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsisAdjacencyChange.Unmarshal(m, b)
}
func (m *IsisAdjacencyChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsisAdjacencyChange.Marshal(b, m, deterministic)
}
func (m *IsisAdjacencyChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsisAdjacencyChange.Merge(m, src)
}
func (m *IsisAdjacencyChange) XXX_Size() int {
	return xxx_messageInfo_IsisAdjacencyChange.Size(m)
}
func (m *IsisAdjacencyChange) XXX_DiscardUnknown() {
	xxx_messageInfo_IsisAdjacencyChange.DiscardUnknown(m)
}

var xxx_messageInfo_IsisAdjacencyChange proto.InternalMessageInfo

func (m *IsisAdjacencyChange) GetHwIsisAdjChgSubReason() string {
	if m != nil {
		return m.HwIsisAdjChgSubReason
	}
	return ""
}

func (m *IsisAdjacencyChange) GetIfIndex() int32 {
	if m != nil {
		return m.IfIndex
	}
	return 0
}

func (m *IsisAdjacencyChange) GetIfName() string {
	if m != nil {
		return m.IfName
	}
	return ""
}

func (m *IsisAdjacencyChange) GetIsisAdjState() int32 {
	if m != nil {
		return m.IsisAdjState
	}
	return 0
}

func (m *IsisAdjacencyChange) GetIsisCircIfIndex() int32 {
	if m != nil {
		return m.IsisCircIfIndex
	}
	return 0
}

func (m *IsisAdjacencyChange) GetIsisCircIndex() int32 {
	if m != nil {
		return m.IsisCircIndex
	}
	return 0
}

func (m *IsisAdjacencyChange) GetIsisPduLspId() string {
	if m != nil {
		return m.IsisPduLspId
	}
	return ""
}

func (m *IsisAdjacencyChange) GetIsisSysInstance() uint32 {
	if m != nil {
		return m.IsisSysInstance
	}
	return 0
}

func (m *IsisAdjacencyChange) GetIsisSysLevelIndex() int32 {
	if m != nil {
		return m.IsisSysLevelIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*ResetIsisRequest)(nil), "huawei_isiscomm.ResetIsisRequest")
	proto.RegisterType((*ResetIsisPeerRequest)(nil), "huawei_isiscomm.ResetIsisPeerRequest")
	proto.RegisterType((*ResetSuppressPeerRequest)(nil), "huawei_isiscomm.ResetSuppressPeerRequest")
	proto.RegisterType((*Empty)(nil), "huawei_isiscomm.Empty")
	proto.RegisterType((*IsisAdjacencyChange)(nil), "huawei_isiscomm.IsisAdjacencyChange")
}

func init() { proto.RegisterFile("huawei-isis.proto", fileDescriptor_36cfa8814ced46bb) }

var fileDescriptor_36cfa8814ced46bb = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xdd, 0xca, 0xd3, 0x40,
	0x10, 0x86, 0x49, 0xb4, 0x3f, 0x19, 0xac, 0x9f, 0x5d, 0xf5, 0x63, 0xf9, 0x0e, 0x4a, 0x0d, 0x0a,
	0x11, 0xb4, 0x07, 0xd5, 0x1b, 0x90, 0xa2, 0x74, 0xa1, 0x94, 0xb2, 0x01, 0x4f, 0x25, 0x4d, 0xa6,
	0xed, 0x8a, 0xf9, 0x31, 0xbb, 0xb1, 0xe6, 0xcc, 0x1b, 0xf6, 0x1e, 0x24, 0x9b, 0x1f, 0x9a, 0xa4,
	0x05, 0x0f, 0xe7, 0xd9, 0x99, 0xf7, 0xdd, 0xd9, 0xbc, 0x81, 0xe9, 0x29, 0xf3, 0xce, 0x28, 0xde,
	0x0b, 0x29, 0xe4, 0x22, 0x49, 0x63, 0x15, 0x93, 0xbb, 0x12, 0x7d, 0x2b, 0x90, 0x1f, 0x87, 0xa1,
	0xbd, 0x84, 0x67, 0x1c, 0x25, 0x2a, 0x26, 0x85, 0xe4, 0xf8, 0x33, 0x43, 0xa9, 0xc8, 0x0c, 0x40,
	0x44, 0x52, 0x79, 0x91, 0x8f, 0x2c, 0xa0, 0xc6, 0xdc, 0x70, 0x26, 0xfc, 0x82, 0xd8, 0x1c, 0x5e,
	0x34, 0x33, 0x3b, 0xc4, 0xf4, 0x3f, 0xe7, 0xc8, 0x03, 0x8c, 0x65, 0x2e, 0x15, 0x86, 0x2c, 0xa0,
	0xe6, 0xdc, 0x70, 0x2c, 0xde, 0xd4, 0x76, 0x0a, 0x54, 0x6b, 0xba, 0x59, 0x92, 0xa4, 0x28, 0x5b,
	0xba, 0xf7, 0x30, 0x14, 0x87, 0xad, 0x17, 0xa2, 0xd6, 0xb4, 0x78, 0x55, 0x75, 0xfc, 0xcc, 0x9e,
	0xdf, 0x0c, 0x20, 0x8a, 0x95, 0x38, 0xe4, 0x85, 0x18, 0x7d, 0x34, 0x37, 0x9c, 0x31, 0xbf, 0x20,
	0xf6, 0x08, 0x06, 0x9f, 0xc3, 0x44, 0xe5, 0xf6, 0x5f, 0x13, 0x9e, 0x17, 0xcb, 0x7c, 0x0a, 0xbe,
	0x7b, 0x3e, 0x46, 0x7e, 0xbe, 0x3a, 0x79, 0xd1, 0x11, 0xc9, 0x47, 0x78, 0xb9, 0x3e, 0x57, 0x07,
	0xab, 0xd3, 0xd1, 0xcd, 0xf6, 0x1c, 0x3d, 0x19, 0x47, 0xd5, 0xed, 0xaf, 0x1f, 0x12, 0x0a, 0x23,
	0x76, 0x60, 0x51, 0x80, 0xbf, 0xb5, 0xe7, 0x80, 0xd7, 0x65, 0xb1, 0x08, 0x2b, 0x17, 0x79, 0x5c,
	0x2e, 0x52, 0x56, 0xc4, 0x86, 0x27, 0x95, 0x90, 0xab, 0x3c, 0x85, 0x74, 0xa0, 0xc7, 0x5a, 0x8c,
	0x38, 0x70, 0x57, 0xd4, 0x2b, 0x91, 0xfa, 0xb5, 0xfa, 0x50, 0xb7, 0x75, 0x31, 0x79, 0x0d, 0x93,
	0x06, 0xe9, 0xbe, 0x91, 0xee, 0x6b, 0xc3, 0xda, 0x73, 0x17, 0x64, 0x1b, 0x99, 0xb0, 0x80, 0x8e,
	0xf5, 0x8d, 0x5a, 0xac, 0xf6, 0x74, 0x73, 0xc9, 0xaa, 0x57, 0xa5, 0x96, 0x7e, 0xe5, 0x2e, 0x26,
	0xef, 0x60, 0x5a, 0xa1, 0x0d, 0xfe, 0xc2, 0x1f, 0xa5, 0x2f, 0x68, 0xdf, 0xfe, 0xc1, 0xf2, 0x8f,
	0x09, 0x4f, 0xd7, 0x3a, 0x88, 0xac, 0xca, 0x21, 0xf9, 0x02, 0x56, 0x93, 0x29, 0xf2, 0x6a, 0xd1,
	0x89, 0xe9, 0xa2, 0x9b, 0xd1, 0x87, 0xfb, 0x5e, 0x8b, 0xfe, 0x94, 0x64, 0x0b, 0x93, 0x56, 0x36,
	0xc9, 0x9b, 0xdb, 0x5a, 0x17, 0x19, 0xbb, 0xa9, 0xf7, 0x15, 0xa6, 0xbd, 0x5c, 0x92, 0xb7, 0xd7,
	0x35, 0xaf, 0x64, 0xf7, 0x96, 0xee, 0x7e, 0xa8, 0xff, 0xc7, 0x0f, 0xff, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x23, 0x9e, 0xff, 0x3f, 0xa4, 0x03, 0x00, 0x00,
}
