// ---------------------------------------------------------------------------
// Protofilename : huawei-kpi.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: huaweiV8R12-kpi.proto

package huaweiV8R12_kpi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kpi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KpiDatas *Kpi_KpiDatas `protobuf:"bytes,1,opt,name=kpi_datas,json=kpi-datas,proto3" json:"kpi_datas,omitempty"`
}

func (x *Kpi) Reset() {
	*x = Kpi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_huaweiV8R12_kpi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kpi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kpi) ProtoMessage() {}

func (x *Kpi) ProtoReflect() protoreflect.Message {
	mi := &file_huaweiV8R12_kpi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kpi.ProtoReflect.Descriptor instead.
func (*Kpi) Descriptor() ([]byte, []int) {
	return file_huaweiV8R12_kpi_proto_rawDescGZIP(), []int{0}
}

func (x *Kpi) GetKpiDatas() *Kpi_KpiDatas {
	if x != nil {
		return x.KpiDatas
	}
	return nil
}

type Kpi_KpiDatas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KpiData []*Kpi_KpiDatas_KpiData `protobuf:"bytes,1,rep,name=kpi_data,json=kpi-data,proto3" json:"kpi_data,omitempty"`
}

func (x *Kpi_KpiDatas) Reset() {
	*x = Kpi_KpiDatas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_huaweiV8R12_kpi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kpi_KpiDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kpi_KpiDatas) ProtoMessage() {}

func (x *Kpi_KpiDatas) ProtoReflect() protoreflect.Message {
	mi := &file_huaweiV8R12_kpi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kpi_KpiDatas.ProtoReflect.Descriptor instead.
func (*Kpi_KpiDatas) Descriptor() ([]byte, []int) {
	return file_huaweiV8R12_kpi_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Kpi_KpiDatas) GetKpiData() []*Kpi_KpiDatas_KpiData {
	if x != nil {
		return x.KpiData
	}
	return nil
}

type Kpi_KpiDatas_KpiData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data       []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ModuleId   uint32 `protobuf:"varint,2,opt,name=module_id,json=module-id,proto3" json:"module_id,omitempty"`
	ModuleName string `protobuf:"bytes,3,opt,name=module_name,json=module-name,proto3" json:"module_name,omitempty"`
	SequenceId uint32 `protobuf:"varint,4,opt,name=sequence_id,json=sequence-id,proto3" json:"sequence_id,omitempty"`
}

func (x *Kpi_KpiDatas_KpiData) Reset() {
	*x = Kpi_KpiDatas_KpiData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_huaweiV8R12_kpi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kpi_KpiDatas_KpiData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kpi_KpiDatas_KpiData) ProtoMessage() {}

func (x *Kpi_KpiDatas_KpiData) ProtoReflect() protoreflect.Message {
	mi := &file_huaweiV8R12_kpi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kpi_KpiDatas_KpiData.ProtoReflect.Descriptor instead.
func (*Kpi_KpiDatas_KpiData) Descriptor() ([]byte, []int) {
	return file_huaweiV8R12_kpi_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Kpi_KpiDatas_KpiData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Kpi_KpiDatas_KpiData) GetModuleId() uint32 {
	if x != nil {
		return x.ModuleId
	}
	return 0
}

func (x *Kpi_KpiDatas_KpiData) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *Kpi_KpiDatas_KpiData) GetSequenceId() uint32 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

var File_huaweiV8R12_kpi_proto protoreflect.FileDescriptor

var file_huaweiV8R12_kpi_proto_rawDesc = []byte{
	0x0a, 0x15, 0x68, 0x75, 0x61, 0x77, 0x65, 0x69, 0x56, 0x38, 0x52, 0x31, 0x32, 0x2d, 0x6b, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x68, 0x75, 0x61, 0x77, 0x65, 0x69, 0x56,
	0x38, 0x52, 0x31, 0x32, 0x5f, 0x6b, 0x70, 0x69, 0x22, 0x93, 0x02, 0x0a, 0x03, 0x4b, 0x70, 0x69,
	0x12, 0x3b, 0x0a, 0x09, 0x6b, 0x70, 0x69, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x68, 0x75, 0x61, 0x77, 0x65, 0x69, 0x56, 0x38, 0x52, 0x31,
	0x32, 0x5f, 0x6b, 0x70, 0x69, 0x2e, 0x4b, 0x70, 0x69, 0x2e, 0x4b, 0x70, 0x69, 0x44, 0x61, 0x74,
	0x61, 0x73, 0x52, 0x09, 0x6b, 0x70, 0x69, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x73, 0x1a, 0xce, 0x01,
	0x0a, 0x08, 0x4b, 0x70, 0x69, 0x44, 0x61, 0x74, 0x61, 0x73, 0x12, 0x41, 0x0a, 0x08, 0x6b, 0x70,
	0x69, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x68,
	0x75, 0x61, 0x77, 0x65, 0x69, 0x56, 0x38, 0x52, 0x31, 0x32, 0x5f, 0x6b, 0x70, 0x69, 0x2e, 0x4b,
	0x70, 0x69, 0x2e, 0x4b, 0x70, 0x69, 0x44, 0x61, 0x74, 0x61, 0x73, 0x2e, 0x4b, 0x70, 0x69, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x08, 0x6b, 0x70, 0x69, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x7f, 0x0a,
	0x07, 0x4b, 0x70, 0x69, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2d, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2d, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0b, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x2d, 0x69, 0x64, 0x42, 0x13,
	0x5a, 0x11, 0x2e, 0x3b, 0x68, 0x75, 0x61, 0x77, 0x65, 0x69, 0x56, 0x38, 0x52, 0x31, 0x32, 0x5f,
	0x6b, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_huaweiV8R12_kpi_proto_rawDescOnce sync.Once
	file_huaweiV8R12_kpi_proto_rawDescData = file_huaweiV8R12_kpi_proto_rawDesc
)

func file_huaweiV8R12_kpi_proto_rawDescGZIP() []byte {
	file_huaweiV8R12_kpi_proto_rawDescOnce.Do(func() {
		file_huaweiV8R12_kpi_proto_rawDescData = protoimpl.X.CompressGZIP(file_huaweiV8R12_kpi_proto_rawDescData)
	})
	return file_huaweiV8R12_kpi_proto_rawDescData
}

var file_huaweiV8R12_kpi_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_huaweiV8R12_kpi_proto_goTypes = []interface{}{
	(*Kpi)(nil),                  // 0: huaweiV8R12_kpi.Kpi
	(*Kpi_KpiDatas)(nil),         // 1: huaweiV8R12_kpi.Kpi.KpiDatas
	(*Kpi_KpiDatas_KpiData)(nil), // 2: huaweiV8R12_kpi.Kpi.KpiDatas.KpiData
}
var file_huaweiV8R12_kpi_proto_depIdxs = []int32{
	1, // 0: huaweiV8R12_kpi.Kpi.kpi_datas:type_name -> huaweiV8R12_kpi.Kpi.KpiDatas
	2, // 1: huaweiV8R12_kpi.Kpi.KpiDatas.kpi_data:type_name -> huaweiV8R12_kpi.Kpi.KpiDatas.KpiData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_huaweiV8R12_kpi_proto_init() }
func file_huaweiV8R12_kpi_proto_init() {
	if File_huaweiV8R12_kpi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_huaweiV8R12_kpi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kpi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_huaweiV8R12_kpi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kpi_KpiDatas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_huaweiV8R12_kpi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kpi_KpiDatas_KpiData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_huaweiV8R12_kpi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_huaweiV8R12_kpi_proto_goTypes,
		DependencyIndexes: file_huaweiV8R12_kpi_proto_depIdxs,
		MessageInfos:      file_huaweiV8R12_kpi_proto_msgTypes,
	}.Build()
	File_huaweiV8R12_kpi_proto = out.File
	file_huaweiV8R12_kpi_proto_rawDesc = nil
	file_huaweiV8R12_kpi_proto_goTypes = nil
	file_huaweiV8R12_kpi_proto_depIdxs = nil
}
