// Code generated by protoc-gen-go. DO NOT EDIT.
// source: huawei-sem.proto

package huawei_sem

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HwCPUUtilizationResume struct {
	ChassisId            int32    `protobuf:"varint,1,opt,name=ChassisId,proto3" json:"ChassisId,omitempty"`
	CpuUsage             int32    `protobuf:"varint,2,opt,name=CpuUsage,proto3" json:"CpuUsage,omitempty"`
	CpuUsageThreshold    int32    `protobuf:"varint,3,opt,name=CpuUsageThreshold,proto3" json:"CpuUsageThreshold,omitempty"`
	EventType            int32    `protobuf:"varint,4,opt,name=EventType,proto3" json:"EventType,omitempty"`
	PhysicalIndex        int32    `protobuf:"varint,5,opt,name=PhysicalIndex,proto3" json:"PhysicalIndex,omitempty"`
	PhysicalName         string   `protobuf:"bytes,6,opt,name=PhysicalName,proto3" json:"PhysicalName,omitempty"`
	ProbableCause        int32    `protobuf:"varint,7,opt,name=ProbableCause,proto3" json:"ProbableCause,omitempty"`
	RelativeResource     string   `protobuf:"bytes,8,opt,name=RelativeResource,proto3" json:"RelativeResource,omitempty"`
	SlotId               int32    `protobuf:"varint,9,opt,name=SlotId,proto3" json:"SlotId,omitempty"`
	SubIndex             int32    `protobuf:"varint,10,opt,name=SubIndex,proto3" json:"SubIndex,omitempty"`
	TrapSeverity         int32    `protobuf:"varint,11,opt,name=TrapSeverity,proto3" json:"TrapSeverity,omitempty"`
	Unit                 int32    `protobuf:"varint,12,opt,name=Unit,proto3" json:"Unit,omitempty"`
	UsageType            int32    `protobuf:"varint,13,opt,name=UsageType,proto3" json:"UsageType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HwCPUUtilizationResume) Reset()         { *m = HwCPUUtilizationResume{} }
func (m *HwCPUUtilizationResume) String() string { return proto.CompactTextString(m) }
func (*HwCPUUtilizationResume) ProtoMessage()    {}
func (*HwCPUUtilizationResume) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e2abac877aed40, []int{0}
}

func (m *HwCPUUtilizationResume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HwCPUUtilizationResume.Unmarshal(m, b)
}
func (m *HwCPUUtilizationResume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HwCPUUtilizationResume.Marshal(b, m, deterministic)
}
func (m *HwCPUUtilizationResume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HwCPUUtilizationResume.Merge(m, src)
}
func (m *HwCPUUtilizationResume) XXX_Size() int {
	return xxx_messageInfo_HwCPUUtilizationResume.Size(m)
}
func (m *HwCPUUtilizationResume) XXX_DiscardUnknown() {
	xxx_messageInfo_HwCPUUtilizationResume.DiscardUnknown(m)
}

var xxx_messageInfo_HwCPUUtilizationResume proto.InternalMessageInfo

func (m *HwCPUUtilizationResume) GetChassisId() int32 {
	if m != nil {
		return m.ChassisId
	}
	return 0
}

func (m *HwCPUUtilizationResume) GetCpuUsage() int32 {
	if m != nil {
		return m.CpuUsage
	}
	return 0
}

func (m *HwCPUUtilizationResume) GetCpuUsageThreshold() int32 {
	if m != nil {
		return m.CpuUsageThreshold
	}
	return 0
}

func (m *HwCPUUtilizationResume) GetEventType() int32 {
	if m != nil {
		return m.EventType
	}
	return 0
}

func (m *HwCPUUtilizationResume) GetPhysicalIndex() int32 {
	if m != nil {
		return m.PhysicalIndex
	}
	return 0
}

func (m *HwCPUUtilizationResume) GetPhysicalName() string {
	if m != nil {
		return m.PhysicalName
	}
	return ""
}

func (m *HwCPUUtilizationResume) GetProbableCause() int32 {
	if m != nil {
		return m.ProbableCause
	}
	return 0
}

func (m *HwCPUUtilizationResume) GetRelativeResource() string {
	if m != nil {
		return m.RelativeResource
	}
	return ""
}

func (m *HwCPUUtilizationResume) GetSlotId() int32 {
	if m != nil {
		return m.SlotId
	}
	return 0
}

func (m *HwCPUUtilizationResume) GetSubIndex() int32 {
	if m != nil {
		return m.SubIndex
	}
	return 0
}

func (m *HwCPUUtilizationResume) GetTrapSeverity() int32 {
	if m != nil {
		return m.TrapSeverity
	}
	return 0
}

func (m *HwCPUUtilizationResume) GetUnit() int32 {
	if m != nil {
		return m.Unit
	}
	return 0
}

func (m *HwCPUUtilizationResume) GetUsageType() int32 {
	if m != nil {
		return m.UsageType
	}
	return 0
}

type HwCPUUtilizationRisingAlarm struct {
	ChassisId            int32    `protobuf:"varint,1,opt,name=ChassisId,proto3" json:"ChassisId,omitempty"`
	CpuUsage             int32    `protobuf:"varint,2,opt,name=CpuUsage,proto3" json:"CpuUsage,omitempty"`
	CpuUsageThreshold    int32    `protobuf:"varint,3,opt,name=CpuUsageThreshold,proto3" json:"CpuUsageThreshold,omitempty"`
	EventType            int32    `protobuf:"varint,4,opt,name=EventType,proto3" json:"EventType,omitempty"`
	PhysicalIndex        int32    `protobuf:"varint,5,opt,name=PhysicalIndex,proto3" json:"PhysicalIndex,omitempty"`
	PhysicalName         string   `protobuf:"bytes,6,opt,name=PhysicalName,proto3" json:"PhysicalName,omitempty"`
	ProbableCause        int32    `protobuf:"varint,7,opt,name=ProbableCause,proto3" json:"ProbableCause,omitempty"`
	RelativeResource     string   `protobuf:"bytes,8,opt,name=RelativeResource,proto3" json:"RelativeResource,omitempty"`
	SlotId               int32    `protobuf:"varint,9,opt,name=SlotId,proto3" json:"SlotId,omitempty"`
	SubIndex             int32    `protobuf:"varint,10,opt,name=SubIndex,proto3" json:"SubIndex,omitempty"`
	TrapSeverity         int32    `protobuf:"varint,11,opt,name=TrapSeverity,proto3" json:"TrapSeverity,omitempty"`
	Unit                 int32    `protobuf:"varint,12,opt,name=Unit,proto3" json:"Unit,omitempty"`
	UsageType            int32    `protobuf:"varint,13,opt,name=UsageType,proto3" json:"UsageType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HwCPUUtilizationRisingAlarm) Reset()         { *m = HwCPUUtilizationRisingAlarm{} }
func (m *HwCPUUtilizationRisingAlarm) String() string { return proto.CompactTextString(m) }
func (*HwCPUUtilizationRisingAlarm) ProtoMessage()    {}
func (*HwCPUUtilizationRisingAlarm) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e2abac877aed40, []int{1}
}

func (m *HwCPUUtilizationRisingAlarm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HwCPUUtilizationRisingAlarm.Unmarshal(m, b)
}
func (m *HwCPUUtilizationRisingAlarm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HwCPUUtilizationRisingAlarm.Marshal(b, m, deterministic)
}
func (m *HwCPUUtilizationRisingAlarm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HwCPUUtilizationRisingAlarm.Merge(m, src)
}
func (m *HwCPUUtilizationRisingAlarm) XXX_Size() int {
	return xxx_messageInfo_HwCPUUtilizationRisingAlarm.Size(m)
}
func (m *HwCPUUtilizationRisingAlarm) XXX_DiscardUnknown() {
	xxx_messageInfo_HwCPUUtilizationRisingAlarm.DiscardUnknown(m)
}

var xxx_messageInfo_HwCPUUtilizationRisingAlarm proto.InternalMessageInfo

func (m *HwCPUUtilizationRisingAlarm) GetChassisId() int32 {
	if m != nil {
		return m.ChassisId
	}
	return 0
}

func (m *HwCPUUtilizationRisingAlarm) GetCpuUsage() int32 {
	if m != nil {
		return m.CpuUsage
	}
	return 0
}

func (m *HwCPUUtilizationRisingAlarm) GetCpuUsageThreshold() int32 {
	if m != nil {
		return m.CpuUsageThreshold
	}
	return 0
}

func (m *HwCPUUtilizationRisingAlarm) GetEventType() int32 {
	if m != nil {
		return m.EventType
	}
	return 0
}

func (m *HwCPUUtilizationRisingAlarm) GetPhysicalIndex() int32 {
	if m != nil {
		return m.PhysicalIndex
	}
	return 0
}

func (m *HwCPUUtilizationRisingAlarm) GetPhysicalName() string {
	if m != nil {
		return m.PhysicalName
	}
	return ""
}

func (m *HwCPUUtilizationRisingAlarm) GetProbableCause() int32 {
	if m != nil {
		return m.ProbableCause
	}
	return 0
}

func (m *HwCPUUtilizationRisingAlarm) GetRelativeResource() string {
	if m != nil {
		return m.RelativeResource
	}
	return ""
}

func (m *HwCPUUtilizationRisingAlarm) GetSlotId() int32 {
	if m != nil {
		return m.SlotId
	}
	return 0
}

func (m *HwCPUUtilizationRisingAlarm) GetSubIndex() int32 {
	if m != nil {
		return m.SubIndex
	}
	return 0
}

func (m *HwCPUUtilizationRisingAlarm) GetTrapSeverity() int32 {
	if m != nil {
		return m.TrapSeverity
	}
	return 0
}

func (m *HwCPUUtilizationRisingAlarm) GetUnit() int32 {
	if m != nil {
		return m.Unit
	}
	return 0
}

func (m *HwCPUUtilizationRisingAlarm) GetUsageType() int32 {
	if m != nil {
		return m.UsageType
	}
	return 0
}

type HwStorageUtilizationResume struct {
	ChassisId            int32    `protobuf:"varint,1,opt,name=ChassisId,proto3" json:"ChassisId,omitempty"`
	EventType            int32    `protobuf:"varint,2,opt,name=EventType,proto3" json:"EventType,omitempty"`
	PhysicalIndex        int32    `protobuf:"varint,3,opt,name=PhysicalIndex,proto3" json:"PhysicalIndex,omitempty"`
	PhysicalName         string   `protobuf:"bytes,4,opt,name=PhysicalName,proto3" json:"PhysicalName,omitempty"`
	ProbableCause        int32    `protobuf:"varint,5,opt,name=ProbableCause,proto3" json:"ProbableCause,omitempty"`
	ReasonId             uint32   `protobuf:"varint,6,opt,name=ReasonId,proto3" json:"ReasonId,omitempty"`
	RelativeResource     string   `protobuf:"bytes,7,opt,name=RelativeResource,proto3" json:"RelativeResource,omitempty"`
	SlotId               int32    `protobuf:"varint,8,opt,name=SlotId,proto3" json:"SlotId,omitempty"`
	SubIndex             int32    `protobuf:"varint,9,opt,name=SubIndex,proto3" json:"SubIndex,omitempty"`
	TrapSeverity         int32    `protobuf:"varint,10,opt,name=TrapSeverity,proto3" json:"TrapSeverity,omitempty"`
	Unit                 int32    `protobuf:"varint,11,opt,name=Unit,proto3" json:"Unit,omitempty"`
	UsageThreshold       int32    `protobuf:"varint,12,opt,name=UsageThreshold,proto3" json:"UsageThreshold,omitempty"`
	UsageType            int32    `protobuf:"varint,13,opt,name=UsageType,proto3" json:"UsageType,omitempty"`
	UsageValue           int32    `protobuf:"varint,14,opt,name=UsageValue,proto3" json:"UsageValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HwStorageUtilizationResume) Reset()         { *m = HwStorageUtilizationResume{} }
func (m *HwStorageUtilizationResume) String() string { return proto.CompactTextString(m) }
func (*HwStorageUtilizationResume) ProtoMessage()    {}
func (*HwStorageUtilizationResume) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e2abac877aed40, []int{2}
}

func (m *HwStorageUtilizationResume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HwStorageUtilizationResume.Unmarshal(m, b)
}
func (m *HwStorageUtilizationResume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HwStorageUtilizationResume.Marshal(b, m, deterministic)
}
func (m *HwStorageUtilizationResume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HwStorageUtilizationResume.Merge(m, src)
}
func (m *HwStorageUtilizationResume) XXX_Size() int {
	return xxx_messageInfo_HwStorageUtilizationResume.Size(m)
}
func (m *HwStorageUtilizationResume) XXX_DiscardUnknown() {
	xxx_messageInfo_HwStorageUtilizationResume.DiscardUnknown(m)
}

var xxx_messageInfo_HwStorageUtilizationResume proto.InternalMessageInfo

func (m *HwStorageUtilizationResume) GetChassisId() int32 {
	if m != nil {
		return m.ChassisId
	}
	return 0
}

func (m *HwStorageUtilizationResume) GetEventType() int32 {
	if m != nil {
		return m.EventType
	}
	return 0
}

func (m *HwStorageUtilizationResume) GetPhysicalIndex() int32 {
	if m != nil {
		return m.PhysicalIndex
	}
	return 0
}

func (m *HwStorageUtilizationResume) GetPhysicalName() string {
	if m != nil {
		return m.PhysicalName
	}
	return ""
}

func (m *HwStorageUtilizationResume) GetProbableCause() int32 {
	if m != nil {
		return m.ProbableCause
	}
	return 0
}

func (m *HwStorageUtilizationResume) GetReasonId() uint32 {
	if m != nil {
		return m.ReasonId
	}
	return 0
}

func (m *HwStorageUtilizationResume) GetRelativeResource() string {
	if m != nil {
		return m.RelativeResource
	}
	return ""
}

func (m *HwStorageUtilizationResume) GetSlotId() int32 {
	if m != nil {
		return m.SlotId
	}
	return 0
}

func (m *HwStorageUtilizationResume) GetSubIndex() int32 {
	if m != nil {
		return m.SubIndex
	}
	return 0
}

func (m *HwStorageUtilizationResume) GetTrapSeverity() int32 {
	if m != nil {
		return m.TrapSeverity
	}
	return 0
}

func (m *HwStorageUtilizationResume) GetUnit() int32 {
	if m != nil {
		return m.Unit
	}
	return 0
}

func (m *HwStorageUtilizationResume) GetUsageThreshold() int32 {
	if m != nil {
		return m.UsageThreshold
	}
	return 0
}

func (m *HwStorageUtilizationResume) GetUsageType() int32 {
	if m != nil {
		return m.UsageType
	}
	return 0
}

func (m *HwStorageUtilizationResume) GetUsageValue() int32 {
	if m != nil {
		return m.UsageValue
	}
	return 0
}

type HwStorageUtilizationRisingAlarm struct {
	ChassisId            int32    `protobuf:"varint,1,opt,name=ChassisId,proto3" json:"ChassisId,omitempty"`
	EventType            int32    `protobuf:"varint,2,opt,name=EventType,proto3" json:"EventType,omitempty"`
	PhysicalIndex        int32    `protobuf:"varint,3,opt,name=PhysicalIndex,proto3" json:"PhysicalIndex,omitempty"`
	PhysicalName         string   `protobuf:"bytes,4,opt,name=PhysicalName,proto3" json:"PhysicalName,omitempty"`
	ProbableCause        int32    `protobuf:"varint,5,opt,name=ProbableCause,proto3" json:"ProbableCause,omitempty"`
	ReasonId             uint32   `protobuf:"varint,6,opt,name=ReasonId,proto3" json:"ReasonId,omitempty"`
	RelativeResource     string   `protobuf:"bytes,7,opt,name=RelativeResource,proto3" json:"RelativeResource,omitempty"`
	SlotId               int32    `protobuf:"varint,8,opt,name=SlotId,proto3" json:"SlotId,omitempty"`
	SubIndex             int32    `protobuf:"varint,9,opt,name=SubIndex,proto3" json:"SubIndex,omitempty"`
	TrapSeverity         int32    `protobuf:"varint,10,opt,name=TrapSeverity,proto3" json:"TrapSeverity,omitempty"`
	Unit                 int32    `protobuf:"varint,11,opt,name=Unit,proto3" json:"Unit,omitempty"`
	UsageThreshold       int32    `protobuf:"varint,12,opt,name=UsageThreshold,proto3" json:"UsageThreshold,omitempty"`
	UsageType            int32    `protobuf:"varint,13,opt,name=UsageType,proto3" json:"UsageType,omitempty"`
	UsageValue           int32    `protobuf:"varint,14,opt,name=UsageValue,proto3" json:"UsageValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HwStorageUtilizationRisingAlarm) Reset()         { *m = HwStorageUtilizationRisingAlarm{} }
func (m *HwStorageUtilizationRisingAlarm) String() string { return proto.CompactTextString(m) }
func (*HwStorageUtilizationRisingAlarm) ProtoMessage()    {}
func (*HwStorageUtilizationRisingAlarm) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e2abac877aed40, []int{3}
}

func (m *HwStorageUtilizationRisingAlarm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HwStorageUtilizationRisingAlarm.Unmarshal(m, b)
}
func (m *HwStorageUtilizationRisingAlarm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HwStorageUtilizationRisingAlarm.Marshal(b, m, deterministic)
}
func (m *HwStorageUtilizationRisingAlarm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HwStorageUtilizationRisingAlarm.Merge(m, src)
}
func (m *HwStorageUtilizationRisingAlarm) XXX_Size() int {
	return xxx_messageInfo_HwStorageUtilizationRisingAlarm.Size(m)
}
func (m *HwStorageUtilizationRisingAlarm) XXX_DiscardUnknown() {
	xxx_messageInfo_HwStorageUtilizationRisingAlarm.DiscardUnknown(m)
}

var xxx_messageInfo_HwStorageUtilizationRisingAlarm proto.InternalMessageInfo

func (m *HwStorageUtilizationRisingAlarm) GetChassisId() int32 {
	if m != nil {
		return m.ChassisId
	}
	return 0
}

func (m *HwStorageUtilizationRisingAlarm) GetEventType() int32 {
	if m != nil {
		return m.EventType
	}
	return 0
}

func (m *HwStorageUtilizationRisingAlarm) GetPhysicalIndex() int32 {
	if m != nil {
		return m.PhysicalIndex
	}
	return 0
}

func (m *HwStorageUtilizationRisingAlarm) GetPhysicalName() string {
	if m != nil {
		return m.PhysicalName
	}
	return ""
}

func (m *HwStorageUtilizationRisingAlarm) GetProbableCause() int32 {
	if m != nil {
		return m.ProbableCause
	}
	return 0
}

func (m *HwStorageUtilizationRisingAlarm) GetReasonId() uint32 {
	if m != nil {
		return m.ReasonId
	}
	return 0
}

func (m *HwStorageUtilizationRisingAlarm) GetRelativeResource() string {
	if m != nil {
		return m.RelativeResource
	}
	return ""
}

func (m *HwStorageUtilizationRisingAlarm) GetSlotId() int32 {
	if m != nil {
		return m.SlotId
	}
	return 0
}

func (m *HwStorageUtilizationRisingAlarm) GetSubIndex() int32 {
	if m != nil {
		return m.SubIndex
	}
	return 0
}

func (m *HwStorageUtilizationRisingAlarm) GetTrapSeverity() int32 {
	if m != nil {
		return m.TrapSeverity
	}
	return 0
}

func (m *HwStorageUtilizationRisingAlarm) GetUnit() int32 {
	if m != nil {
		return m.Unit
	}
	return 0
}

func (m *HwStorageUtilizationRisingAlarm) GetUsageThreshold() int32 {
	if m != nil {
		return m.UsageThreshold
	}
	return 0
}

func (m *HwStorageUtilizationRisingAlarm) GetUsageType() int32 {
	if m != nil {
		return m.UsageType
	}
	return 0
}

func (m *HwStorageUtilizationRisingAlarm) GetUsageValue() int32 {
	if m != nil {
		return m.UsageValue
	}
	return 0
}

type HwSystemConfigError struct {
	EntityTrapFaultID    int32    `protobuf:"varint,1,opt,name=EntityTrapFaultID,proto3" json:"EntityTrapFaultID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HwSystemConfigError) Reset()         { *m = HwSystemConfigError{} }
func (m *HwSystemConfigError) String() string { return proto.CompactTextString(m) }
func (*HwSystemConfigError) ProtoMessage()    {}
func (*HwSystemConfigError) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e2abac877aed40, []int{4}
}

func (m *HwSystemConfigError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HwSystemConfigError.Unmarshal(m, b)
}
func (m *HwSystemConfigError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HwSystemConfigError.Marshal(b, m, deterministic)
}
func (m *HwSystemConfigError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HwSystemConfigError.Merge(m, src)
}
func (m *HwSystemConfigError) XXX_Size() int {
	return xxx_messageInfo_HwSystemConfigError.Size(m)
}
func (m *HwSystemConfigError) XXX_DiscardUnknown() {
	xxx_messageInfo_HwSystemConfigError.DiscardUnknown(m)
}

var xxx_messageInfo_HwSystemConfigError proto.InternalMessageInfo

func (m *HwSystemConfigError) GetEntityTrapFaultID() int32 {
	if m != nil {
		return m.EntityTrapFaultID
	}
	return 0
}

type HwSystemConfigResume struct {
	EntityTrapFaultID    int32    `protobuf:"varint,1,opt,name=EntityTrapFaultID,proto3" json:"EntityTrapFaultID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HwSystemConfigResume) Reset()         { *m = HwSystemConfigResume{} }
func (m *HwSystemConfigResume) String() string { return proto.CompactTextString(m) }
func (*HwSystemConfigResume) ProtoMessage()    {}
func (*HwSystemConfigResume) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e2abac877aed40, []int{5}
}

func (m *HwSystemConfigResume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HwSystemConfigResume.Unmarshal(m, b)
}
func (m *HwSystemConfigResume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HwSystemConfigResume.Marshal(b, m, deterministic)
}
func (m *HwSystemConfigResume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HwSystemConfigResume.Merge(m, src)
}
func (m *HwSystemConfigResume) XXX_Size() int {
	return xxx_messageInfo_HwSystemConfigResume.Size(m)
}
func (m *HwSystemConfigResume) XXX_DiscardUnknown() {
	xxx_messageInfo_HwSystemConfigResume.DiscardUnknown(m)
}

var xxx_messageInfo_HwSystemConfigResume proto.InternalMessageInfo

func (m *HwSystemConfigResume) GetEntityTrapFaultID() int32 {
	if m != nil {
		return m.EntityTrapFaultID
	}
	return 0
}

type Sem struct {
	OsGrpInfos           *Sem_OsGrpInfos `protobuf:"bytes,1,opt,name=osGrpInfos,proto3" json:"osGrpInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Sem) Reset()         { *m = Sem{} }
func (m *Sem) String() string { return proto.CompactTextString(m) }
func (*Sem) ProtoMessage()    {}
func (*Sem) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e2abac877aed40, []int{6}
}

func (m *Sem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sem.Unmarshal(m, b)
}
func (m *Sem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sem.Marshal(b, m, deterministic)
}
func (m *Sem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sem.Merge(m, src)
}
func (m *Sem) XXX_Size() int {
	return xxx_messageInfo_Sem.Size(m)
}
func (m *Sem) XXX_DiscardUnknown() {
	xxx_messageInfo_Sem.DiscardUnknown(m)
}

var xxx_messageInfo_Sem proto.InternalMessageInfo

func (m *Sem) GetOsGrpInfos() *Sem_OsGrpInfos {
	if m != nil {
		return m.OsGrpInfos
	}
	return nil
}

type Sem_OsGrpInfos struct {
	OsGrpInfo            []*Sem_OsGrpInfos_OsGrpInfo `protobuf:"bytes,1,rep,name=osGrpInfo,proto3" json:"osGrpInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Sem_OsGrpInfos) Reset()         { *m = Sem_OsGrpInfos{} }
func (m *Sem_OsGrpInfos) String() string { return proto.CompactTextString(m) }
func (*Sem_OsGrpInfos) ProtoMessage()    {}
func (*Sem_OsGrpInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e2abac877aed40, []int{6, 0}
}

func (m *Sem_OsGrpInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sem_OsGrpInfos.Unmarshal(m, b)
}
func (m *Sem_OsGrpInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sem_OsGrpInfos.Marshal(b, m, deterministic)
}
func (m *Sem_OsGrpInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sem_OsGrpInfos.Merge(m, src)
}
func (m *Sem_OsGrpInfos) XXX_Size() int {
	return xxx_messageInfo_Sem_OsGrpInfos.Size(m)
}
func (m *Sem_OsGrpInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_Sem_OsGrpInfos.DiscardUnknown(m)
}

var xxx_messageInfo_Sem_OsGrpInfos proto.InternalMessageInfo

func (m *Sem_OsGrpInfos) GetOsGrpInfo() []*Sem_OsGrpInfos_OsGrpInfo {
	if m != nil {
		return m.OsGrpInfo
	}
	return nil
}

type Sem_OsGrpInfos_OsGrpInfo struct {
	BoardID              string   `protobuf:"bytes,1,opt,name=boardID,proto3" json:"boardID,omitempty"`
	OsGrpName            string   `protobuf:"bytes,2,opt,name=osGrpName,proto3" json:"osGrpName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sem_OsGrpInfos_OsGrpInfo) Reset()         { *m = Sem_OsGrpInfos_OsGrpInfo{} }
func (m *Sem_OsGrpInfos_OsGrpInfo) String() string { return proto.CompactTextString(m) }
func (*Sem_OsGrpInfos_OsGrpInfo) ProtoMessage()    {}
func (*Sem_OsGrpInfos_OsGrpInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e2abac877aed40, []int{6, 0, 0}
}

func (m *Sem_OsGrpInfos_OsGrpInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sem_OsGrpInfos_OsGrpInfo.Unmarshal(m, b)
}
func (m *Sem_OsGrpInfos_OsGrpInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sem_OsGrpInfos_OsGrpInfo.Marshal(b, m, deterministic)
}
func (m *Sem_OsGrpInfos_OsGrpInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sem_OsGrpInfos_OsGrpInfo.Merge(m, src)
}
func (m *Sem_OsGrpInfos_OsGrpInfo) XXX_Size() int {
	return xxx_messageInfo_Sem_OsGrpInfos_OsGrpInfo.Size(m)
}
func (m *Sem_OsGrpInfos_OsGrpInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Sem_OsGrpInfos_OsGrpInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Sem_OsGrpInfos_OsGrpInfo proto.InternalMessageInfo

func (m *Sem_OsGrpInfos_OsGrpInfo) GetBoardID() string {
	if m != nil {
		return m.BoardID
	}
	return ""
}

func (m *Sem_OsGrpInfos_OsGrpInfo) GetOsGrpName() string {
	if m != nil {
		return m.OsGrpName
	}
	return ""
}

func init() {
	proto.RegisterType((*HwCPUUtilizationResume)(nil), "huawei_sem.HwCPUUtilizationResume")
	proto.RegisterType((*HwCPUUtilizationRisingAlarm)(nil), "huawei_sem.HwCPUUtilizationRisingAlarm")
	proto.RegisterType((*HwStorageUtilizationResume)(nil), "huawei_sem.HwStorageUtilizationResume")
	proto.RegisterType((*HwStorageUtilizationRisingAlarm)(nil), "huawei_sem.HwStorageUtilizationRisingAlarm")
	proto.RegisterType((*HwSystemConfigError)(nil), "huawei_sem.HwSystemConfigError")
	proto.RegisterType((*HwSystemConfigResume)(nil), "huawei_sem.HwSystemConfigResume")
	proto.RegisterType((*Sem)(nil), "huawei_sem.Sem")
	proto.RegisterType((*Sem_OsGrpInfos)(nil), "huawei_sem.Sem.OsGrpInfos")
	proto.RegisterType((*Sem_OsGrpInfos_OsGrpInfo)(nil), "huawei_sem.Sem.OsGrpInfos.OsGrpInfo")
}

func init() { proto.RegisterFile("huawei-sem.proto", fileDescriptor_44e2abac877aed40) }

var fileDescriptor_44e2abac877aed40 = []byte{
	// 576 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x96, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x95, 0x65, 0x3f, 0x9a, 0xd7, 0x6d, 0x1a, 0x06, 0x4d, 0x56, 0x40, 0x30, 0x55, 0x13,
	0x9a, 0x10, 0xf4, 0x30, 0x6e, 0xdc, 0x20, 0x1b, 0x34, 0x17, 0x98, 0x92, 0x96, 0x2b, 0x72, 0x97,
	0xb7, 0xd6, 0x52, 0x12, 0x57, 0xb6, 0xd3, 0x52, 0xfe, 0x0f, 0xfe, 0x23, 0x2e, 0xfc, 0x09, 0x5c,
	0xb9, 0xf0, 0x6f, 0xa0, 0x38, 0x6d, 0xd2, 0xd2, 0x96, 0x76, 0xc7, 0x49, 0xbb, 0xf9, 0x7d, 0xbf,
	0x2f, 0xcf, 0xce, 0xfb, 0xd8, 0x96, 0xe1, 0xa8, 0x9f, 0xb1, 0x11, 0xf2, 0x57, 0x0a, 0x93, 0xe6,
	0x40, 0x0a, 0x2d, 0x08, 0x14, 0xca, 0x17, 0x85, 0x49, 0xe3, 0x87, 0x0d, 0xc7, 0xad, 0x91, 0x77,
	0xd5, 0xe9, 0x68, 0x1e, 0xf3, 0x6f, 0x4c, 0x73, 0x91, 0x06, 0xa8, 0xb2, 0x04, 0xc9, 0x13, 0x70,
	0xbc, 0x3e, 0x53, 0x8a, 0x2b, 0x3f, 0xa2, 0xd6, 0x89, 0x75, 0xb6, 0x13, 0x54, 0x02, 0x71, 0xa1,
	0xe6, 0x0d, 0xb2, 0x8e, 0x62, 0x3d, 0xa4, 0x5b, 0xc6, 0x2c, 0x63, 0xf2, 0x12, 0x1e, 0x4c, 0xc7,
	0xed, 0xbe, 0x44, 0xd5, 0x17, 0x71, 0x44, 0x6d, 0x93, 0xb4, 0x68, 0xe4, 0xf3, 0x5c, 0x0e, 0x31,
	0xd5, 0xed, 0xf1, 0x00, 0xe9, 0x76, 0x31, 0x4f, 0x29, 0x90, 0x53, 0x38, 0xb8, 0xea, 0x8f, 0x15,
	0xbf, 0x66, 0xb1, 0x9f, 0x46, 0xf8, 0x95, 0xee, 0x98, 0x8c, 0x79, 0x91, 0x34, 0x60, 0x7f, 0x2a,
	0x7c, 0x64, 0x09, 0xd2, 0xdd, 0x13, 0xeb, 0xcc, 0x09, 0xe6, 0x34, 0x53, 0x49, 0x8a, 0x2e, 0xeb,
	0xc6, 0xe8, 0xb1, 0x4c, 0x21, 0xdd, 0x9b, 0x54, 0x9a, 0x15, 0xc9, 0x0b, 0x38, 0x0a, 0x30, 0x66,
	0x9a, 0x0f, 0x31, 0x40, 0x25, 0x32, 0x79, 0x8d, 0xb4, 0x66, 0xaa, 0x2d, 0xe8, 0xe4, 0x18, 0x76,
	0xc3, 0x58, 0x68, 0x3f, 0xa2, 0x8e, 0x29, 0x35, 0x89, 0xf2, 0xde, 0x84, 0x59, 0xb7, 0x58, 0x2e,
	0x14, 0xbd, 0x99, 0xc6, 0xf9, 0x4a, 0xdb, 0x92, 0x0d, 0x42, 0x1c, 0xa2, 0xe4, 0x7a, 0x4c, 0xeb,
	0xc6, 0x9f, 0xd3, 0x08, 0x81, 0xed, 0x4e, 0xca, 0x35, 0xdd, 0x37, 0x9e, 0x19, 0xe7, 0x5d, 0x2a,
	0xfa, 0x96, 0x77, 0xe9, 0xa0, 0xe8, 0x52, 0x29, 0x34, 0x7e, 0xda, 0xf0, 0x78, 0x01, 0x23, 0x57,
	0x3c, 0xed, 0xbd, 0x8d, 0x99, 0x4c, 0xee, 0x59, 0xde, 0x21, 0x96, 0xbf, 0x6d, 0x70, 0x5b, 0xa3,
	0x50, 0x0b, 0xc9, 0x7a, 0x78, 0xdb, 0x63, 0x39, 0x07, 0x60, 0x6b, 0x2d, 0x00, 0x7b, 0x13, 0x00,
	0xdb, 0x9b, 0x00, 0xd8, 0x59, 0x06, 0xc0, 0x85, 0x5a, 0x80, 0x4c, 0x89, 0xd4, 0x8f, 0x0c, 0xc6,
	0x83, 0xa0, 0x8c, 0x97, 0xc2, 0xd9, 0x5b, 0x0b, 0xa7, 0xb6, 0x12, 0x8e, 0xb3, 0x06, 0x0e, 0xfc,
	0x07, 0x4e, 0x7d, 0x06, 0xce, 0x73, 0x38, 0xfc, 0x67, 0xb7, 0x17, 0xe8, 0x0e, 0x17, 0xb7, 0xfa,
	0x6a, 0x88, 0xe4, 0x29, 0x80, 0x09, 0x3e, 0xb3, 0x38, 0x43, 0x7a, 0x68, 0xec, 0x19, 0xa5, 0xf1,
	0xc7, 0x86, 0x67, 0x4b, 0x21, 0x6f, 0x7c, 0x68, 0xef, 0x49, 0xdf, 0x0d, 0xd2, 0x1e, 0x3c, 0x6c,
	0x8d, 0xc2, 0xb1, 0xd2, 0x98, 0x78, 0x22, 0xbd, 0xe1, 0xbd, 0x4b, 0x29, 0x85, 0xcc, 0xef, 0xd5,
	0xcb, 0x54, 0x73, 0x3d, 0xce, 0x97, 0xf9, 0x9e, 0x65, 0xb1, 0xf6, 0x2f, 0x26, 0x90, 0x17, 0x8d,
	0xc6, 0x05, 0x3c, 0x9a, 0x2f, 0x32, 0xb9, 0x0c, 0x6e, 0x57, 0xe5, 0x97, 0x05, 0x76, 0x88, 0x09,
	0x79, 0x03, 0x20, 0xd4, 0x07, 0x39, 0xf0, 0xd3, 0x1b, 0xa1, 0x4c, 0x7a, 0xfd, 0xdc, 0x6d, 0x56,
	0xaf, 0x82, 0x66, 0x88, 0x49, 0xf3, 0x53, 0x99, 0x11, 0xcc, 0x64, 0xbb, 0xdf, 0x2d, 0x80, 0xca,
	0x22, 0xef, 0xc0, 0x29, 0x4d, 0x6a, 0x9d, 0xd8, 0x67, 0xf5, 0xf3, 0xd3, 0xd5, 0x95, 0xaa, 0x61,
	0x50, 0x7d, 0xe6, 0x7a, 0xe0, 0x94, 0x3a, 0xa1, 0xb0, 0xd7, 0x15, 0x4c, 0x46, 0x93, 0xff, 0x70,
	0x82, 0x69, 0x98, 0x63, 0x30, 0xdf, 0x98, 0x9d, 0xba, 0x65, 0xbc, 0x4a, 0xe8, 0xee, 0x9a, 0xb7,
	0xcd, 0xeb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x28, 0xf0, 0x42, 0x28, 0xef, 0x08, 0x00, 0x00,
}
