// Code generated by protoc-gen-go. DO NOT EDIT.
// source: huawei-ospfv3.proto

package huawei_ospfv3

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ospfv3NbrStateChange struct {
	IfName               string   `protobuf:"bytes,1,opt,name=IfName,proto3" json:"IfName,omitempty"`
	NbrIfIndex           uint32   `protobuf:"varint,2,opt,name=NbrIfIndex,proto3" json:"NbrIfIndex,omitempty"`
	NbrIfInstId          uint32   `protobuf:"varint,3,opt,name=NbrIfInstId,proto3" json:"NbrIfInstId,omitempty"`
	NbrRtrId             string   `protobuf:"bytes,4,opt,name=NbrRtrId,proto3" json:"NbrRtrId,omitempty"`
	NbrState             string   `protobuf:"bytes,5,opt,name=NbrState,proto3" json:"NbrState,omitempty"`
	RouterId             string   `protobuf:"bytes,7,opt,name=RouterId,proto3" json:"RouterId,omitempty"`
	SubReason            string   `protobuf:"bytes,8,opt,name=SubReason,proto3" json:"SubReason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ospfv3NbrStateChange) Reset()         { *m = Ospfv3NbrStateChange{} }
func (m *Ospfv3NbrStateChange) String() string { return proto.CompactTextString(m) }
func (*Ospfv3NbrStateChange) ProtoMessage()    {}
func (*Ospfv3NbrStateChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_792c9a3198780268, []int{0}
}

func (m *Ospfv3NbrStateChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ospfv3NbrStateChange.Unmarshal(m, b)
}
func (m *Ospfv3NbrStateChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ospfv3NbrStateChange.Marshal(b, m, deterministic)
}
func (m *Ospfv3NbrStateChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ospfv3NbrStateChange.Merge(m, src)
}
func (m *Ospfv3NbrStateChange) XXX_Size() int {
	return xxx_messageInfo_Ospfv3NbrStateChange.Size(m)
}
func (m *Ospfv3NbrStateChange) XXX_DiscardUnknown() {
	xxx_messageInfo_Ospfv3NbrStateChange.DiscardUnknown(m)
}

var xxx_messageInfo_Ospfv3NbrStateChange proto.InternalMessageInfo

func (m *Ospfv3NbrStateChange) GetIfName() string {
	if m != nil {
		return m.IfName
	}
	return ""
}

func (m *Ospfv3NbrStateChange) GetNbrIfIndex() uint32 {
	if m != nil {
		return m.NbrIfIndex
	}
	return 0
}

func (m *Ospfv3NbrStateChange) GetNbrIfInstId() uint32 {
	if m != nil {
		return m.NbrIfInstId
	}
	return 0
}

func (m *Ospfv3NbrStateChange) GetNbrRtrId() string {
	if m != nil {
		return m.NbrRtrId
	}
	return ""
}

func (m *Ospfv3NbrStateChange) GetNbrState() string {
	if m != nil {
		return m.NbrState
	}
	return ""
}

func (m *Ospfv3NbrStateChange) GetRouterId() string {
	if m != nil {
		return m.RouterId
	}
	return ""
}

func (m *Ospfv3NbrStateChange) GetSubReason() string {
	if m != nil {
		return m.SubReason
	}
	return ""
}

func init() {
	proto.RegisterType((*Ospfv3NbrStateChange)(nil), "huawei_ospfv3.Ospfv3NbrStateChange")
}

func init() { proto.RegisterFile("huawei-ospfv3.proto", fileDescriptor_792c9a3198780268) }

var fileDescriptor_792c9a3198780268 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x3d, 0x0e, 0x82, 0x30,
	0x14, 0x80, 0x53, 0x7f, 0x10, 0x9e, 0x61, 0xa9, 0xc6, 0x34, 0xc6, 0x18, 0xe2, 0xc4, 0xa2, 0x0b,
	0x47, 0x70, 0xea, 0x52, 0x93, 0x72, 0x00, 0xd3, 0x86, 0x22, 0x0e, 0x52, 0x52, 0x8a, 0x7a, 0x5e,
	0x4f, 0x62, 0x28, 0x88, 0x6c, 0xfd, 0xbe, 0xaf, 0x6d, 0xde, 0x83, 0x55, 0xd1, 0x88, 0x97, 0xba,
	0x1f, 0x75, 0x5d, 0xe5, 0xcf, 0xe4, 0x54, 0x19, 0x6d, 0x35, 0x0e, 0x3b, 0x79, 0xed, 0xe4, 0xe1,
	0x83, 0x60, 0x7d, 0x71, 0x47, 0x26, 0x4d, 0x6a, 0x85, 0x55, 0xe7, 0x42, 0x94, 0x37, 0x85, 0x37,
	0xe0, 0xd1, 0x9c, 0x89, 0x87, 0x22, 0x28, 0x42, 0x71, 0xc0, 0x7b, 0xc2, 0x7b, 0x00, 0x26, 0x0d,
	0xcd, 0x69, 0x99, 0xa9, 0x37, 0x99, 0x44, 0x28, 0x0e, 0xf9, 0xc8, 0xe0, 0x08, 0x96, 0x3d, 0xd5,
	0x96, 0x66, 0x64, 0xea, 0x2e, 0x8c, 0x15, 0xde, 0x82, 0xcf, 0xa4, 0xe1, 0xd6, 0xd0, 0x8c, 0xcc,
	0xdc, 0xdf, 0x03, 0xf7, 0xcd, 0xcd, 0x41, 0xe6, 0x43, 0x73, 0xdc, 0x36, 0xae, 0x1b, 0xab, 0xda,
	0x77, 0x8b, 0xae, 0xfd, 0x18, 0xef, 0x20, 0x48, 0x1b, 0xc9, 0x95, 0xa8, 0x75, 0x49, 0x7c, 0x17,
	0xff, 0x42, 0x7a, 0x6e, 0xf5, 0xe4, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x7e, 0xb8, 0x7d, 0x9e, 0x11,
	0x01, 0x00, 0x00,
}
