// Code generated by protoc-gen-go. DO NOT EDIT.
// source: huawei-mpls.proto

package huawei_mpls

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_eadb0282bee3f804, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Session_Down_MIB struct {
	IfIndex              uint32   `protobuf:"varint,1,opt,name=IfIndex,proto3" json:"IfIndex,omitempty"`
	IfName               string   `protobuf:"bytes,2,opt,name=IfName,proto3" json:"IfName,omitempty"`
	LdpEntityIndex       uint32   `protobuf:"varint,3,opt,name=LdpEntityIndex,proto3" json:"LdpEntityIndex,omitempty"`
	LocalLsrId           string   `protobuf:"bytes,4,opt,name=LocalLsrId,proto3" json:"LocalLsrId,omitempty"`
	PeerLsrId            string   `protobuf:"bytes,5,opt,name=PeerLsrId,proto3" json:"PeerLsrId,omitempty"`
	Reason               string   `protobuf:"bytes,6,opt,name=Reason,proto3" json:"Reason,omitempty"`
	ReasonValue          uint32   `protobuf:"varint,7,opt,name=ReasonValue,proto3" json:"ReasonValue,omitempty"`
	SessionType          string   `protobuf:"bytes,8,opt,name=SessionType,proto3" json:"SessionType,omitempty"`
	SsnDiscoTime         uint32   `protobuf:"varint,9,opt,name=SsnDiscoTime,proto3" json:"SsnDiscoTime,omitempty"`
	SsnRecUnknownMsgErrs uint32   `protobuf:"varint,10,opt,name=SsnRecUnknownMsgErrs,proto3" json:"SsnRecUnknownMsgErrs,omitempty"`
	SsnRecUnknownTlvErrs uint32   `protobuf:"varint,11,opt,name=SsnRecUnknownTlvErrs,proto3" json:"SsnRecUnknownTlvErrs,omitempty"`
	SsnState             uint32   `protobuf:"varint,12,opt,name=SsnState,proto3" json:"SsnState,omitempty"`
	SubReason            uint32   `protobuf:"varint,13,opt,name=SubReason,proto3" json:"SubReason,omitempty"`
	VrfName              string   `protobuf:"bytes,14,opt,name=VrfName,proto3" json:"VrfName,omitempty"`
	AdjIfIndex           uint32   `protobuf:"varint,15,opt,name=adjIfIndex,proto3" json:"adjIfIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session_Down_MIB) Reset()         { *m = Session_Down_MIB{} }
func (m *Session_Down_MIB) String() string { return proto.CompactTextString(m) }
func (*Session_Down_MIB) ProtoMessage()    {}
func (*Session_Down_MIB) Descriptor() ([]byte, []int) {
	return fileDescriptor_eadb0282bee3f804, []int{1}
}

func (m *Session_Down_MIB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session_Down_MIB.Unmarshal(m, b)
}
func (m *Session_Down_MIB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session_Down_MIB.Marshal(b, m, deterministic)
}
func (m *Session_Down_MIB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session_Down_MIB.Merge(m, src)
}
func (m *Session_Down_MIB) XXX_Size() int {
	return xxx_messageInfo_Session_Down_MIB.Size(m)
}
func (m *Session_Down_MIB) XXX_DiscardUnknown() {
	xxx_messageInfo_Session_Down_MIB.DiscardUnknown(m)
}

var xxx_messageInfo_Session_Down_MIB proto.InternalMessageInfo

func (m *Session_Down_MIB) GetIfIndex() uint32 {
	if m != nil {
		return m.IfIndex
	}
	return 0
}

func (m *Session_Down_MIB) GetIfName() string {
	if m != nil {
		return m.IfName
	}
	return ""
}

func (m *Session_Down_MIB) GetLdpEntityIndex() uint32 {
	if m != nil {
		return m.LdpEntityIndex
	}
	return 0
}

func (m *Session_Down_MIB) GetLocalLsrId() string {
	if m != nil {
		return m.LocalLsrId
	}
	return ""
}

func (m *Session_Down_MIB) GetPeerLsrId() string {
	if m != nil {
		return m.PeerLsrId
	}
	return ""
}

func (m *Session_Down_MIB) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Session_Down_MIB) GetReasonValue() uint32 {
	if m != nil {
		return m.ReasonValue
	}
	return 0
}

func (m *Session_Down_MIB) GetSessionType() string {
	if m != nil {
		return m.SessionType
	}
	return ""
}

func (m *Session_Down_MIB) GetSsnDiscoTime() uint32 {
	if m != nil {
		return m.SsnDiscoTime
	}
	return 0
}

func (m *Session_Down_MIB) GetSsnRecUnknownMsgErrs() uint32 {
	if m != nil {
		return m.SsnRecUnknownMsgErrs
	}
	return 0
}

func (m *Session_Down_MIB) GetSsnRecUnknownTlvErrs() uint32 {
	if m != nil {
		return m.SsnRecUnknownTlvErrs
	}
	return 0
}

func (m *Session_Down_MIB) GetSsnState() uint32 {
	if m != nil {
		return m.SsnState
	}
	return 0
}

func (m *Session_Down_MIB) GetSubReason() uint32 {
	if m != nil {
		return m.SubReason
	}
	return 0
}

func (m *Session_Down_MIB) GetVrfName() string {
	if m != nil {
		return m.VrfName
	}
	return ""
}

func (m *Session_Down_MIB) GetAdjIfIndex() uint32 {
	if m != nil {
		return m.AdjIfIndex
	}
	return 0
}

type Session_Up_MIB struct {
	IfIndex              uint32   `protobuf:"varint,1,opt,name=IfIndex,proto3" json:"IfIndex,omitempty"`
	IfName               string   `protobuf:"bytes,2,opt,name=IfName,proto3" json:"IfName,omitempty"`
	LdpEntityIndex       uint32   `protobuf:"varint,3,opt,name=LdpEntityIndex,proto3" json:"LdpEntityIndex,omitempty"`
	LocalLsrId           string   `protobuf:"bytes,4,opt,name=LocalLsrId,proto3" json:"LocalLsrId,omitempty"`
	PeerLsrId            string   `protobuf:"bytes,5,opt,name=PeerLsrId,proto3" json:"PeerLsrId,omitempty"`
	Reason               string   `protobuf:"bytes,6,opt,name=Reason,proto3" json:"Reason,omitempty"`
	ReasonValue          uint32   `protobuf:"varint,7,opt,name=ReasonValue,proto3" json:"ReasonValue,omitempty"`
	SessionType          string   `protobuf:"bytes,8,opt,name=SessionType,proto3" json:"SessionType,omitempty"`
	SsnDiscoTime         uint32   `protobuf:"varint,9,opt,name=SsnDiscoTime,proto3" json:"SsnDiscoTime,omitempty"`
	SsnRecUnknownMsgErrs uint32   `protobuf:"varint,10,opt,name=SsnRecUnknownMsgErrs,proto3" json:"SsnRecUnknownMsgErrs,omitempty"`
	SsnRecUnknownTlvErrs uint32   `protobuf:"varint,11,opt,name=SsnRecUnknownTlvErrs,proto3" json:"SsnRecUnknownTlvErrs,omitempty"`
	SsnState             uint32   `protobuf:"varint,12,opt,name=SsnState,proto3" json:"SsnState,omitempty"`
	SubReason            uint32   `protobuf:"varint,13,opt,name=SubReason,proto3" json:"SubReason,omitempty"`
	VrfName              string   `protobuf:"bytes,14,opt,name=VrfName,proto3" json:"VrfName,omitempty"`
	AdjIfIndex           uint32   `protobuf:"varint,15,opt,name=adjIfIndex,proto3" json:"adjIfIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session_Up_MIB) Reset()         { *m = Session_Up_MIB{} }
func (m *Session_Up_MIB) String() string { return proto.CompactTextString(m) }
func (*Session_Up_MIB) ProtoMessage()    {}
func (*Session_Up_MIB) Descriptor() ([]byte, []int) {
	return fileDescriptor_eadb0282bee3f804, []int{2}
}

func (m *Session_Up_MIB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session_Up_MIB.Unmarshal(m, b)
}
func (m *Session_Up_MIB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session_Up_MIB.Marshal(b, m, deterministic)
}
func (m *Session_Up_MIB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session_Up_MIB.Merge(m, src)
}
func (m *Session_Up_MIB) XXX_Size() int {
	return xxx_messageInfo_Session_Up_MIB.Size(m)
}
func (m *Session_Up_MIB) XXX_DiscardUnknown() {
	xxx_messageInfo_Session_Up_MIB.DiscardUnknown(m)
}

var xxx_messageInfo_Session_Up_MIB proto.InternalMessageInfo

func (m *Session_Up_MIB) GetIfIndex() uint32 {
	if m != nil {
		return m.IfIndex
	}
	return 0
}

func (m *Session_Up_MIB) GetIfName() string {
	if m != nil {
		return m.IfName
	}
	return ""
}

func (m *Session_Up_MIB) GetLdpEntityIndex() uint32 {
	if m != nil {
		return m.LdpEntityIndex
	}
	return 0
}

func (m *Session_Up_MIB) GetLocalLsrId() string {
	if m != nil {
		return m.LocalLsrId
	}
	return ""
}

func (m *Session_Up_MIB) GetPeerLsrId() string {
	if m != nil {
		return m.PeerLsrId
	}
	return ""
}

func (m *Session_Up_MIB) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Session_Up_MIB) GetReasonValue() uint32 {
	if m != nil {
		return m.ReasonValue
	}
	return 0
}

func (m *Session_Up_MIB) GetSessionType() string {
	if m != nil {
		return m.SessionType
	}
	return ""
}

func (m *Session_Up_MIB) GetSsnDiscoTime() uint32 {
	if m != nil {
		return m.SsnDiscoTime
	}
	return 0
}

func (m *Session_Up_MIB) GetSsnRecUnknownMsgErrs() uint32 {
	if m != nil {
		return m.SsnRecUnknownMsgErrs
	}
	return 0
}

func (m *Session_Up_MIB) GetSsnRecUnknownTlvErrs() uint32 {
	if m != nil {
		return m.SsnRecUnknownTlvErrs
	}
	return 0
}

func (m *Session_Up_MIB) GetSsnState() uint32 {
	if m != nil {
		return m.SsnState
	}
	return 0
}

func (m *Session_Up_MIB) GetSubReason() uint32 {
	if m != nil {
		return m.SubReason
	}
	return 0
}

func (m *Session_Up_MIB) GetVrfName() string {
	if m != nil {
		return m.VrfName
	}
	return ""
}

func (m *Session_Up_MIB) GetAdjIfIndex() uint32 {
	if m != nil {
		return m.AdjIfIndex
	}
	return 0
}

type Mpls struct {
	MplsTe               *Mpls_MplsTe `protobuf:"bytes,3,opt,name=mplsTe,proto3" json:"mplsTe,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Mpls) Reset()         { *m = Mpls{} }
func (m *Mpls) String() string { return proto.CompactTextString(m) }
func (*Mpls) ProtoMessage()    {}
func (*Mpls) Descriptor() ([]byte, []int) {
	return fileDescriptor_eadb0282bee3f804, []int{3}
}

func (m *Mpls) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mpls.Unmarshal(m, b)
}
func (m *Mpls) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mpls.Marshal(b, m, deterministic)
}
func (m *Mpls) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mpls.Merge(m, src)
}
func (m *Mpls) XXX_Size() int {
	return xxx_messageInfo_Mpls.Size(m)
}
func (m *Mpls) XXX_DiscardUnknown() {
	xxx_messageInfo_Mpls.DiscardUnknown(m)
}

var xxx_messageInfo_Mpls proto.InternalMessageInfo

func (m *Mpls) GetMplsTe() *Mpls_MplsTe {
	if m != nil {
		return m.MplsTe
	}
	return nil
}

type Mpls_MplsTe struct {
	RsvpTeTunnels        *Mpls_MplsTe_RsvpTeTunnels `protobuf:"bytes,27,opt,name=rsvpTeTunnels,proto3" json:"rsvpTeTunnels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Mpls_MplsTe) Reset()         { *m = Mpls_MplsTe{} }
func (m *Mpls_MplsTe) String() string { return proto.CompactTextString(m) }
func (*Mpls_MplsTe) ProtoMessage()    {}
func (*Mpls_MplsTe) Descriptor() ([]byte, []int) {
	return fileDescriptor_eadb0282bee3f804, []int{3, 0}
}

func (m *Mpls_MplsTe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mpls_MplsTe.Unmarshal(m, b)
}
func (m *Mpls_MplsTe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mpls_MplsTe.Marshal(b, m, deterministic)
}
func (m *Mpls_MplsTe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mpls_MplsTe.Merge(m, src)
}
func (m *Mpls_MplsTe) XXX_Size() int {
	return xxx_messageInfo_Mpls_MplsTe.Size(m)
}
func (m *Mpls_MplsTe) XXX_DiscardUnknown() {
	xxx_messageInfo_Mpls_MplsTe.DiscardUnknown(m)
}

var xxx_messageInfo_Mpls_MplsTe proto.InternalMessageInfo

func (m *Mpls_MplsTe) GetRsvpTeTunnels() *Mpls_MplsTe_RsvpTeTunnels {
	if m != nil {
		return m.RsvpTeTunnels
	}
	return nil
}

type Mpls_MplsTe_RsvpTeTunnels struct {
	RsvpTeTunnel         []*Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel `protobuf:"bytes,1,rep,name=rsvpTeTunnel,proto3" json:"rsvpTeTunnel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *Mpls_MplsTe_RsvpTeTunnels) Reset()         { *m = Mpls_MplsTe_RsvpTeTunnels{} }
func (m *Mpls_MplsTe_RsvpTeTunnels) String() string { return proto.CompactTextString(m) }
func (*Mpls_MplsTe_RsvpTeTunnels) ProtoMessage()    {}
func (*Mpls_MplsTe_RsvpTeTunnels) Descriptor() ([]byte, []int) {
	return fileDescriptor_eadb0282bee3f804, []int{3, 0, 0}
}

func (m *Mpls_MplsTe_RsvpTeTunnels) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels.Unmarshal(m, b)
}
func (m *Mpls_MplsTe_RsvpTeTunnels) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels.Marshal(b, m, deterministic)
}
func (m *Mpls_MplsTe_RsvpTeTunnels) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels.Merge(m, src)
}
func (m *Mpls_MplsTe_RsvpTeTunnels) XXX_Size() int {
	return xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels.Size(m)
}
func (m *Mpls_MplsTe_RsvpTeTunnels) XXX_DiscardUnknown() {
	xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels.DiscardUnknown(m)
}

var xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels proto.InternalMessageInfo

func (m *Mpls_MplsTe_RsvpTeTunnels) GetRsvpTeTunnel() []*Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel {
	if m != nil {
		return m.RsvpTeTunnel
	}
	return nil
}

type Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel struct {
	TunnelName           string                                              `protobuf:"bytes,48,opt,name=tunnelName,proto3" json:"tunnelName,omitempty"`
	TunnelPaths          *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths `protobuf:"bytes,49,opt,name=tunnelPaths,proto3" json:"tunnelPaths,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                            `json:"-"`
	XXX_unrecognized     []byte                                              `json:"-"`
	XXX_sizecache        int32                                               `json:"-"`
}

func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel) Reset() {
	*m = Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel{}
}
func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel) String() string { return proto.CompactTextString(m) }
func (*Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel) ProtoMessage()    {}
func (*Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel) Descriptor() ([]byte, []int) {
	return fileDescriptor_eadb0282bee3f804, []int{3, 0, 0, 0}
}

func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel.Unmarshal(m, b)
}
func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel.Marshal(b, m, deterministic)
}
func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel.Merge(m, src)
}
func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel) XXX_Size() int {
	return xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel.Size(m)
}
func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel) XXX_DiscardUnknown() {
	xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel.DiscardUnknown(m)
}

var xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel proto.InternalMessageInfo

func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel) GetTunnelName() string {
	if m != nil {
		return m.TunnelName
	}
	return ""
}

func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel) GetTunnelPaths() *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths {
	if m != nil {
		return m.TunnelPaths
	}
	return nil
}

type Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths struct {
	TunnelPath           []*Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths_TunnelPath `protobuf:"bytes,1,rep,name=tunnelPath,proto3" json:"tunnelPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                         `json:"-"`
	XXX_unrecognized     []byte                                                           `json:"-"`
	XXX_sizecache        int32                                                            `json:"-"`
}

func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths) Reset() {
	*m = Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths{}
}
func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths) String() string {
	return proto.CompactTextString(m)
}
func (*Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths) ProtoMessage() {}
func (*Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths) Descriptor() ([]byte, []int) {
	return fileDescriptor_eadb0282bee3f804, []int{3, 0, 0, 0, 0}
}

func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths.Unmarshal(m, b)
}
func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths.Marshal(b, m, deterministic)
}
func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths.Merge(m, src)
}
func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths) XXX_Size() int {
	return xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths.Size(m)
}
func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths) XXX_DiscardUnknown() {
	xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths.DiscardUnknown(m)
}

var xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths proto.InternalMessageInfo

func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths) GetTunnelPath() []*Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths_TunnelPath {
	if m != nil {
		return m.TunnelPath
	}
	return nil
}

type Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths_TunnelPath struct {
	ExplicitPathName     string   `protobuf:"bytes,3,opt,name=explicitPathName,proto3" json:"explicitPathName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths_TunnelPath) Reset() {
	*m = Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths_TunnelPath{}
}
func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths_TunnelPath) String() string {
	return proto.CompactTextString(m)
}
func (*Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths_TunnelPath) ProtoMessage() {}
func (*Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths_TunnelPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_eadb0282bee3f804, []int{3, 0, 0, 0, 0, 0}
}

func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths_TunnelPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths_TunnelPath.Unmarshal(m, b)
}
func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths_TunnelPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths_TunnelPath.Marshal(b, m, deterministic)
}
func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths_TunnelPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths_TunnelPath.Merge(m, src)
}
func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths_TunnelPath) XXX_Size() int {
	return xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths_TunnelPath.Size(m)
}
func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths_TunnelPath) XXX_DiscardUnknown() {
	xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths_TunnelPath.DiscardUnknown(m)
}

var xxx_messageInfo_Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths_TunnelPath proto.InternalMessageInfo

func (m *Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths_TunnelPath) GetExplicitPathName() string {
	if m != nil {
		return m.ExplicitPathName
	}
	return ""
}

type TNLREROUTED struct {
	EgressLsrId          string   `protobuf:"bytes,1,opt,name=EgressLsrId,proto3" json:"EgressLsrId,omitempty"`
	IngressLsrId         string   `protobuf:"bytes,2,opt,name=IngressLsrId,proto3" json:"IngressLsrId,omitempty"`
	LocalLspId           int32    `protobuf:"varint,3,opt,name=LocalLspId,proto3" json:"LocalLspId,omitempty"`
	TunnelAdminStatus    string   `protobuf:"bytes,4,opt,name=TunnelAdminStatus,proto3" json:"TunnelAdminStatus,omitempty"`
	TunnelId             int32    `protobuf:"varint,5,opt,name=TunnelId,proto3" json:"TunnelId,omitempty"`
	TunnelOperStatus     string   `protobuf:"bytes,6,opt,name=TunnelOperStatus,proto3" json:"TunnelOperStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TNLREROUTED) Reset()         { *m = TNLREROUTED{} }
func (m *TNLREROUTED) String() string { return proto.CompactTextString(m) }
func (*TNLREROUTED) ProtoMessage()    {}
func (*TNLREROUTED) Descriptor() ([]byte, []int) {
	return fileDescriptor_eadb0282bee3f804, []int{4}
}

func (m *TNLREROUTED) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TNLREROUTED.Unmarshal(m, b)
}
func (m *TNLREROUTED) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TNLREROUTED.Marshal(b, m, deterministic)
}
func (m *TNLREROUTED) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TNLREROUTED.Merge(m, src)
}
func (m *TNLREROUTED) XXX_Size() int {
	return xxx_messageInfo_TNLREROUTED.Size(m)
}
func (m *TNLREROUTED) XXX_DiscardUnknown() {
	xxx_messageInfo_TNLREROUTED.DiscardUnknown(m)
}

var xxx_messageInfo_TNLREROUTED proto.InternalMessageInfo

func (m *TNLREROUTED) GetEgressLsrId() string {
	if m != nil {
		return m.EgressLsrId
	}
	return ""
}

func (m *TNLREROUTED) GetIngressLsrId() string {
	if m != nil {
		return m.IngressLsrId
	}
	return ""
}

func (m *TNLREROUTED) GetLocalLspId() int32 {
	if m != nil {
		return m.LocalLspId
	}
	return 0
}

func (m *TNLREROUTED) GetTunnelAdminStatus() string {
	if m != nil {
		return m.TunnelAdminStatus
	}
	return ""
}

func (m *TNLREROUTED) GetTunnelId() int32 {
	if m != nil {
		return m.TunnelId
	}
	return 0
}

func (m *TNLREROUTED) GetTunnelOperStatus() string {
	if m != nil {
		return m.TunnelOperStatus
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "huawei_mpls.Empty")
	proto.RegisterType((*Session_Down_MIB)(nil), "huawei_mpls.Session_Down_MIB")
	proto.RegisterType((*Session_Up_MIB)(nil), "huawei_mpls.Session_Up_MIB")
	proto.RegisterType((*Mpls)(nil), "huawei_mpls.Mpls")
	proto.RegisterType((*Mpls_MplsTe)(nil), "huawei_mpls.Mpls.MplsTe")
	proto.RegisterType((*Mpls_MplsTe_RsvpTeTunnels)(nil), "huawei_mpls.Mpls.MplsTe.RsvpTeTunnels")
	proto.RegisterType((*Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel)(nil), "huawei_mpls.Mpls.MplsTe.RsvpTeTunnels.RsvpTeTunnel")
	proto.RegisterType((*Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths)(nil), "huawei_mpls.Mpls.MplsTe.RsvpTeTunnels.RsvpTeTunnel.TunnelPaths")
	proto.RegisterType((*Mpls_MplsTe_RsvpTeTunnels_RsvpTeTunnel_TunnelPaths_TunnelPath)(nil), "huawei_mpls.Mpls.MplsTe.RsvpTeTunnels.RsvpTeTunnel.TunnelPaths.TunnelPath")
	proto.RegisterType((*TNLREROUTED)(nil), "huawei_mpls.TNLREROUTED")
}

func init() { proto.RegisterFile("huawei-mpls.proto", fileDescriptor_eadb0282bee3f804) }

var fileDescriptor_eadb0282bee3f804 = []byte{
	// 614 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x55, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0x96, 0x1b, 0x27, 0x6d, 0xc7, 0x49, 0xfe, 0x76, 0xf5, 0x0b, 0xad, 0x0c, 0x42, 0x51, 0x0e,
	0x55, 0x84, 0x20, 0x2a, 0xe9, 0x85, 0x1b, 0x02, 0xc5, 0x07, 0xa3, 0xa4, 0xad, 0xd6, 0x4e, 0x39,
	0x46, 0x6e, 0xbc, 0x6d, 0x5d, 0x9c, 0xb5, 0xe5, 0x75, 0x9a, 0xe6, 0x8e, 0xb8, 0xf0, 0x36, 0xf0,
	0x0e, 0xf0, 0x2c, 0xbc, 0x05, 0xda, 0x5d, 0xbb, 0x59, 0x93, 0x22, 0x21, 0x38, 0xc2, 0xc5, 0xda,
	0xef, 0x9b, 0x99, 0x6f, 0x77, 0x66, 0x77, 0xc6, 0xb0, 0x7f, 0xb5, 0x08, 0x96, 0x34, 0x7a, 0x36,
	0x4f, 0x63, 0xde, 0x4f, 0xb3, 0x24, 0x4f, 0x90, 0xa5, 0xa8, 0xa9, 0xa0, 0xba, 0xdb, 0x50, 0x77,
	0xe6, 0x69, 0xbe, 0xea, 0x7e, 0x30, 0x61, 0xcf, 0xa3, 0x9c, 0x47, 0x09, 0x9b, 0x0e, 0x93, 0x25,
	0x9b, 0x8e, 0xdd, 0xd7, 0x08, 0xc3, 0xb6, 0x7b, 0xe1, 0xb2, 0x90, 0xde, 0x62, 0xa3, 0x63, 0xf4,
	0x5a, 0xa4, 0x84, 0xe8, 0x01, 0x34, 0xdc, 0x8b, 0xe3, 0x60, 0x4e, 0xf1, 0x56, 0xc7, 0xe8, 0xed,
	0x92, 0x02, 0xa1, 0x03, 0x68, 0x8f, 0xc2, 0xd4, 0x61, 0x79, 0x94, 0xaf, 0x54, 0x60, 0x4d, 0x06,
	0xfe, 0xc0, 0xa2, 0xc7, 0x00, 0xa3, 0x64, 0x16, 0xc4, 0x23, 0x9e, 0xb9, 0x21, 0x36, 0xa5, 0x86,
	0xc6, 0xa0, 0x47, 0xb0, 0x7b, 0x4a, 0x69, 0xa6, 0xcc, 0x75, 0x69, 0x5e, 0x13, 0x62, 0x77, 0x42,
	0x03, 0x9e, 0x30, 0xdc, 0x50, 0xbb, 0x2b, 0x84, 0x3a, 0x60, 0xa9, 0xd5, 0x59, 0x10, 0x2f, 0x28,
	0xde, 0x96, 0x5b, 0xeb, 0x94, 0xf0, 0x28, 0xb2, 0xf4, 0x57, 0x29, 0xc5, 0x3b, 0x32, 0x5c, 0xa7,
	0x50, 0x17, 0x9a, 0x1e, 0x67, 0xc3, 0x88, 0xcf, 0x12, 0x3f, 0x9a, 0x53, 0xbc, 0x2b, 0x45, 0x2a,
	0x1c, 0x1a, 0xc0, 0xff, 0x1e, 0x67, 0x84, 0xce, 0x26, 0xec, 0x1d, 0x4b, 0x96, 0x6c, 0xcc, 0x2f,
	0x9d, 0x2c, 0xe3, 0x18, 0xa4, 0xef, 0xbd, 0xb6, 0x8d, 0x18, 0x3f, 0xbe, 0x91, 0x31, 0xd6, 0x3d,
	0x31, 0x85, 0x0d, 0xd9, 0xb0, 0xe3, 0x71, 0xe6, 0xe5, 0x41, 0x4e, 0x71, 0x53, 0xfa, 0xdd, 0x61,
	0x51, 0x21, 0x6f, 0x71, 0x5e, 0x94, 0xa1, 0x25, 0x8d, 0x6b, 0x42, 0xdc, 0xdc, 0x59, 0xa6, 0x2e,
	0xa8, 0x2d, 0x73, 0x2c, 0xa1, 0xa8, 0x7c, 0x10, 0x5e, 0x97, 0xd7, 0xfa, 0x9f, 0x0c, 0xd4, 0x98,
	0xee, 0x7b, 0x13, 0xda, 0xe5, 0x43, 0x98, 0xa4, 0xff, 0x9e, 0xc1, 0x5f, 0xfa, 0x0c, 0xbe, 0x98,
	0x60, 0x8e, 0xd3, 0x98, 0xa3, 0x43, 0x68, 0x88, 0x49, 0xe1, 0x53, 0x79, 0x85, 0xd6, 0x00, 0xf7,
	0xb5, 0xf9, 0xd1, 0x1f, 0x97, 0x1f, 0x9f, 0x92, 0xc2, 0xcf, 0xfe, 0x68, 0x42, 0x43, 0x51, 0x68,
	0x04, 0xad, 0x8c, 0xdf, 0xa4, 0x3e, 0xf5, 0x17, 0x8c, 0xd1, 0x98, 0xe3, 0x87, 0x52, 0xe3, 0xe0,
	0x67, 0x1a, 0x7d, 0xa2, 0x7b, 0x93, 0x6a, 0xb0, 0xfd, 0xa9, 0x06, 0xad, 0x8a, 0x03, 0x7a, 0x0b,
	0x4d, 0xdd, 0x05, 0x1b, 0x9d, 0x5a, 0xcf, 0x1a, 0x1c, 0xfd, 0x9a, 0x7c, 0x05, 0x91, 0x8a, 0x90,
	0xfd, 0x75, 0x0b, 0x9a, 0xba, 0x59, 0xd4, 0x2b, 0x97, 0x2b, 0x59, 0xcc, 0x43, 0xf5, 0x52, 0xd7,
	0x0c, 0x0a, 0xc0, 0x52, 0xe8, 0x34, 0xc8, 0xaf, 0x38, 0x7e, 0x2e, 0xf3, 0x7c, 0xf9, 0x1b, 0x07,
	0xe9, 0xfb, 0x6b, 0x19, 0xa2, 0x6b, 0xda, 0x9f, 0x0d, 0xb0, 0x34, 0x23, 0xba, 0x2e, 0x8f, 0x24,
	0x60, 0x91, 0xfa, 0x9b, 0x3f, 0xdc, 0x51, 0x5b, 0x13, 0x4d, 0xdd, 0x7e, 0x01, 0xb0, 0xb6, 0xa0,
	0x27, 0xb0, 0x47, 0x6f, 0xd3, 0x38, 0x9a, 0x45, 0xb9, 0xc0, 0xb2, 0x24, 0x35, 0x59, 0x92, 0x0d,
	0xbe, 0xfb, 0x4d, 0x9c, 0xfa, 0x78, 0x44, 0x1c, 0x72, 0x32, 0xf1, 0x9d, 0xa1, 0x68, 0x3d, 0xe7,
	0x32, 0xa3, 0x9c, 0xab, 0xa6, 0x36, 0x54, 0xeb, 0x69, 0x94, 0x68, 0x3d, 0x97, 0x69, 0x2e, 0x6a,
	0xb4, 0x54, 0x38, 0x6d, 0x70, 0xa4, 0x6e, 0x28, 0xf7, 0xae, 0x13, 0x8d, 0x41, 0x4f, 0x61, 0x5f,
	0x9d, 0xf7, 0x55, 0x38, 0x8f, 0x64, 0xab, 0x2c, 0x78, 0x31, 0x5f, 0x36, 0x0d, 0xa2, 0xc1, 0x14,
	0x59, 0x4c, 0x99, 0x3a, 0xb9, 0xc3, 0x22, 0x57, 0xb5, 0x3e, 0x49, 0x69, 0x56, 0x08, 0xa9, 0x71,
	0xb3, 0xc1, 0x9f, 0x37, 0xe4, 0x1f, 0xf6, 0xe8, 0x7b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x38, 0x20,
	0x78, 0x03, 0x76, 0x07, 0x00, 0x00,
}
