// Code generated by protoc-gen-go. DO NOT EDIT.
// source: huawei-telemetry.proto

package telemetry

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Telemetry_Encoding int32

const (
	Telemetry_Encoding_GPB  Telemetry_Encoding = 0
	Telemetry_Encoding_JSON Telemetry_Encoding = 1
)

var Telemetry_Encoding_name = map[int32]string{
	0: "Encoding_GPB",
	1: "Encoding_JSON",
}

var Telemetry_Encoding_value = map[string]int32{
	"Encoding_GPB":  0,
	"Encoding_JSON": 1,
}

func (x Telemetry_Encoding) String() string {
	return proto.EnumName(Telemetry_Encoding_name, int32(x))
}

func (Telemetry_Encoding) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4f1dbed6c6cbe291, []int{0, 0}
}

type TelemetrySelfDefinedEvent_ThresholdRelation int32

const (
	TelemetrySelfDefinedEvent_ThresholdRelation_INVALID TelemetrySelfDefinedEvent_ThresholdRelation = 0
	TelemetrySelfDefinedEvent_ThresholdRelation_AND     TelemetrySelfDefinedEvent_ThresholdRelation = 1
	TelemetrySelfDefinedEvent_ThresholdRelation_OR      TelemetrySelfDefinedEvent_ThresholdRelation = 2
)

var TelemetrySelfDefinedEvent_ThresholdRelation_name = map[int32]string{
	0: "ThresholdRelation_INVALID",
	1: "ThresholdRelation_AND",
	2: "ThresholdRelation_OR",
}

var TelemetrySelfDefinedEvent_ThresholdRelation_value = map[string]int32{
	"ThresholdRelation_INVALID": 0,
	"ThresholdRelation_AND":     1,
	"ThresholdRelation_OR":      2,
}

func (x TelemetrySelfDefinedEvent_ThresholdRelation) String() string {
	return proto.EnumName(TelemetrySelfDefinedEvent_ThresholdRelation_name, int32(x))
}

func (TelemetrySelfDefinedEvent_ThresholdRelation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4f1dbed6c6cbe291, []int{3, 0}
}

type TelemetryThreshold_ThresholdOpType int32

const (
	TelemetryThreshold_ThresholdOpType_EQ TelemetryThreshold_ThresholdOpType = 0
	TelemetryThreshold_ThresholdOpType_GT TelemetryThreshold_ThresholdOpType = 1
	TelemetryThreshold_ThresholdOpType_GE TelemetryThreshold_ThresholdOpType = 2
	TelemetryThreshold_ThresholdOpType_LT TelemetryThreshold_ThresholdOpType = 3
	TelemetryThreshold_ThresholdOpType_LE TelemetryThreshold_ThresholdOpType = 4
)

var TelemetryThreshold_ThresholdOpType_name = map[int32]string{
	0: "ThresholdOpType_EQ",
	1: "ThresholdOpType_GT",
	2: "ThresholdOpType_GE",
	3: "ThresholdOpType_LT",
	4: "ThresholdOpType_LE",
}

var TelemetryThreshold_ThresholdOpType_value = map[string]int32{
	"ThresholdOpType_EQ": 0,
	"ThresholdOpType_GT": 1,
	"ThresholdOpType_GE": 2,
	"ThresholdOpType_LT": 3,
	"ThresholdOpType_LE": 4,
}

func (x TelemetryThreshold_ThresholdOpType) String() string {
	return proto.EnumName(TelemetryThreshold_ThresholdOpType_name, int32(x))
}

func (TelemetryThreshold_ThresholdOpType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4f1dbed6c6cbe291, []int{5, 0}
}

type Telemetry struct {
	NodeIdStr            string             `protobuf:"bytes,1,opt,name=node_id_str,json=nodeIdStr,proto3" json:"node_id_str,omitempty"`
	SubscriptionIdStr    string             `protobuf:"bytes,2,opt,name=subscription_id_str,json=subscriptionIdStr,proto3" json:"subscription_id_str,omitempty"`
	SensorPath           string             `protobuf:"bytes,3,opt,name=sensor_path,json=sensorPath,proto3" json:"sensor_path,omitempty"`
	CollectionId         uint64             `protobuf:"varint,4,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	CollectionStartTime  uint64             `protobuf:"varint,5,opt,name=collection_start_time,json=collectionStartTime,proto3" json:"collection_start_time,omitempty"`
	MsgTimestamp         uint64             `protobuf:"varint,6,opt,name=msg_timestamp,json=msgTimestamp,proto3" json:"msg_timestamp,omitempty"`
	DataGpb              *TelemetryGPBTable `protobuf:"bytes,7,opt,name=data_gpb,json=dataGpb,proto3" json:"data_gpb,omitempty"`
	CollectionEndTime    uint64             `protobuf:"varint,8,opt,name=collection_end_time,json=collectionEndTime,proto3" json:"collection_end_time,omitempty"`
	CurrentPeriod        uint32             `protobuf:"varint,9,opt,name=current_period,json=currentPeriod,proto3" json:"current_period,omitempty"`
	ExceptDesc           string             `protobuf:"bytes,10,opt,name=except_desc,json=exceptDesc,proto3" json:"except_desc,omitempty"`
	ProductName          string             `protobuf:"bytes,11,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Encoding             Telemetry_Encoding `protobuf:"varint,12,opt,name=encoding,proto3,enum=telemetry.Telemetry_Encoding" json:"encoding,omitempty"`
	DataStr              string             `protobuf:"bytes,14,opt,name=data_str,json=dataStr,proto3" json:"data_str,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Telemetry) Reset()         { *m = Telemetry{} }
func (m *Telemetry) String() string { return proto.CompactTextString(m) }
func (*Telemetry) ProtoMessage()    {}
func (*Telemetry) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f1dbed6c6cbe291, []int{0}
}

func (m *Telemetry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Telemetry.Unmarshal(m, b)
}
func (m *Telemetry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Telemetry.Marshal(b, m, deterministic)
}
func (m *Telemetry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Telemetry.Merge(m, src)
}
func (m *Telemetry) XXX_Size() int {
	return xxx_messageInfo_Telemetry.Size(m)
}
func (m *Telemetry) XXX_DiscardUnknown() {
	xxx_messageInfo_Telemetry.DiscardUnknown(m)
}

var xxx_messageInfo_Telemetry proto.InternalMessageInfo

func (m *Telemetry) GetNodeIdStr() string {
	if m != nil {
		return m.NodeIdStr
	}
	return ""
}

func (m *Telemetry) GetSubscriptionIdStr() string {
	if m != nil {
		return m.SubscriptionIdStr
	}
	return ""
}

func (m *Telemetry) GetSensorPath() string {
	if m != nil {
		return m.SensorPath
	}
	return ""
}

func (m *Telemetry) GetCollectionId() uint64 {
	if m != nil {
		return m.CollectionId
	}
	return 0
}

func (m *Telemetry) GetCollectionStartTime() uint64 {
	if m != nil {
		return m.CollectionStartTime
	}
	return 0
}

func (m *Telemetry) GetMsgTimestamp() uint64 {
	if m != nil {
		return m.MsgTimestamp
	}
	return 0
}

func (m *Telemetry) GetDataGpb() *TelemetryGPBTable {
	if m != nil {
		return m.DataGpb
	}
	return nil
}

func (m *Telemetry) GetCollectionEndTime() uint64 {
	if m != nil {
		return m.CollectionEndTime
	}
	return 0
}

func (m *Telemetry) GetCurrentPeriod() uint32 {
	if m != nil {
		return m.CurrentPeriod
	}
	return 0
}

func (m *Telemetry) GetExceptDesc() string {
	if m != nil {
		return m.ExceptDesc
	}
	return ""
}

func (m *Telemetry) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *Telemetry) GetEncoding() Telemetry_Encoding {
	if m != nil {
		return m.Encoding
	}
	return Telemetry_Encoding_GPB
}

func (m *Telemetry) GetDataStr() string {
	if m != nil {
		return m.DataStr
	}
	return ""
}

type TelemetryGPBTable struct {
	Row                  []*TelemetryRowGPB `protobuf:"bytes,1,rep,name=row,proto3" json:"row,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TelemetryGPBTable) Reset()         { *m = TelemetryGPBTable{} }
func (m *TelemetryGPBTable) String() string { return proto.CompactTextString(m) }
func (*TelemetryGPBTable) ProtoMessage()    {}
func (*TelemetryGPBTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f1dbed6c6cbe291, []int{1}
}

func (m *TelemetryGPBTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetryGPBTable.Unmarshal(m, b)
}
func (m *TelemetryGPBTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetryGPBTable.Marshal(b, m, deterministic)
}
func (m *TelemetryGPBTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetryGPBTable.Merge(m, src)
}
func (m *TelemetryGPBTable) XXX_Size() int {
	return xxx_messageInfo_TelemetryGPBTable.Size(m)
}
func (m *TelemetryGPBTable) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetryGPBTable.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetryGPBTable proto.InternalMessageInfo

func (m *TelemetryGPBTable) GetRow() []*TelemetryRowGPB {
	if m != nil {
		return m.Row
	}
	return nil
}

type TelemetryRowGPB struct {
	Timestamp            uint64   `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Content              []byte   `protobuf:"bytes,11,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TelemetryRowGPB) Reset()         { *m = TelemetryRowGPB{} }
func (m *TelemetryRowGPB) String() string { return proto.CompactTextString(m) }
func (*TelemetryRowGPB) ProtoMessage()    {}
func (*TelemetryRowGPB) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f1dbed6c6cbe291, []int{2}
}

func (m *TelemetryRowGPB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetryRowGPB.Unmarshal(m, b)
}
func (m *TelemetryRowGPB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetryRowGPB.Marshal(b, m, deterministic)
}
func (m *TelemetryRowGPB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetryRowGPB.Merge(m, src)
}
func (m *TelemetryRowGPB) XXX_Size() int {
	return xxx_messageInfo_TelemetryRowGPB.Size(m)
}
func (m *TelemetryRowGPB) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetryRowGPB.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetryRowGPB proto.InternalMessageInfo

func (m *TelemetryRowGPB) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TelemetryRowGPB) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type TelemetrySelfDefinedEvent struct {
	Path                 string                                      `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Level                uint32                                      `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Description          string                                      `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	FieldName            string                                      `protobuf:"bytes,4,opt,name=fieldName,proto3" json:"fieldName,omitempty"`
	FieldValue           uint32                                      `protobuf:"varint,5,opt,name=fieldValue,proto3" json:"fieldValue,omitempty"`
	DataThreshold        *TelemetrySelfDefineThresTable              `protobuf:"bytes,6,opt,name=data_threshold,json=dataThreshold,proto3" json:"data_threshold,omitempty"`
	ThresholdRelation    TelemetrySelfDefinedEvent_ThresholdRelation `protobuf:"varint,7,opt,name=thresholdRelation,proto3,enum=telemetry.TelemetrySelfDefinedEvent_ThresholdRelation" json:"thresholdRelation,omitempty"`
	Content              []byte                                      `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *TelemetrySelfDefinedEvent) Reset()         { *m = TelemetrySelfDefinedEvent{} }
func (m *TelemetrySelfDefinedEvent) String() string { return proto.CompactTextString(m) }
func (*TelemetrySelfDefinedEvent) ProtoMessage()    {}
func (*TelemetrySelfDefinedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f1dbed6c6cbe291, []int{3}
}

func (m *TelemetrySelfDefinedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetrySelfDefinedEvent.Unmarshal(m, b)
}
func (m *TelemetrySelfDefinedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetrySelfDefinedEvent.Marshal(b, m, deterministic)
}
func (m *TelemetrySelfDefinedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetrySelfDefinedEvent.Merge(m, src)
}
func (m *TelemetrySelfDefinedEvent) XXX_Size() int {
	return xxx_messageInfo_TelemetrySelfDefinedEvent.Size(m)
}
func (m *TelemetrySelfDefinedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetrySelfDefinedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetrySelfDefinedEvent proto.InternalMessageInfo

func (m *TelemetrySelfDefinedEvent) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *TelemetrySelfDefinedEvent) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *TelemetrySelfDefinedEvent) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TelemetrySelfDefinedEvent) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *TelemetrySelfDefinedEvent) GetFieldValue() uint32 {
	if m != nil {
		return m.FieldValue
	}
	return 0
}

func (m *TelemetrySelfDefinedEvent) GetDataThreshold() *TelemetrySelfDefineThresTable {
	if m != nil {
		return m.DataThreshold
	}
	return nil
}

func (m *TelemetrySelfDefinedEvent) GetThresholdRelation() TelemetrySelfDefinedEvent_ThresholdRelation {
	if m != nil {
		return m.ThresholdRelation
	}
	return TelemetrySelfDefinedEvent_ThresholdRelation_INVALID
}

func (m *TelemetrySelfDefinedEvent) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type TelemetrySelfDefineThresTable struct {
	Row                  []*TelemetryThreshold `protobuf:"bytes,1,rep,name=row,proto3" json:"row,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TelemetrySelfDefineThresTable) Reset()         { *m = TelemetrySelfDefineThresTable{} }
func (m *TelemetrySelfDefineThresTable) String() string { return proto.CompactTextString(m) }
func (*TelemetrySelfDefineThresTable) ProtoMessage()    {}
func (*TelemetrySelfDefineThresTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f1dbed6c6cbe291, []int{4}
}

func (m *TelemetrySelfDefineThresTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetrySelfDefineThresTable.Unmarshal(m, b)
}
func (m *TelemetrySelfDefineThresTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetrySelfDefineThresTable.Marshal(b, m, deterministic)
}
func (m *TelemetrySelfDefineThresTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetrySelfDefineThresTable.Merge(m, src)
}
func (m *TelemetrySelfDefineThresTable) XXX_Size() int {
	return xxx_messageInfo_TelemetrySelfDefineThresTable.Size(m)
}
func (m *TelemetrySelfDefineThresTable) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetrySelfDefineThresTable.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetrySelfDefineThresTable proto.InternalMessageInfo

func (m *TelemetrySelfDefineThresTable) GetRow() []*TelemetryThreshold {
	if m != nil {
		return m.Row
	}
	return nil
}

type TelemetryThreshold struct {
	ThresholdValue       uint32                             `protobuf:"varint,1,opt,name=thresholdValue,proto3" json:"thresholdValue,omitempty"`
	ThresholdOpType      TelemetryThreshold_ThresholdOpType `protobuf:"varint,2,opt,name=thresholdOpType,proto3,enum=telemetry.TelemetryThreshold_ThresholdOpType" json:"thresholdOpType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *TelemetryThreshold) Reset()         { *m = TelemetryThreshold{} }
func (m *TelemetryThreshold) String() string { return proto.CompactTextString(m) }
func (*TelemetryThreshold) ProtoMessage()    {}
func (*TelemetryThreshold) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f1dbed6c6cbe291, []int{5}
}

func (m *TelemetryThreshold) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetryThreshold.Unmarshal(m, b)
}
func (m *TelemetryThreshold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetryThreshold.Marshal(b, m, deterministic)
}
func (m *TelemetryThreshold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetryThreshold.Merge(m, src)
}
func (m *TelemetryThreshold) XXX_Size() int {
	return xxx_messageInfo_TelemetryThreshold.Size(m)
}
func (m *TelemetryThreshold) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetryThreshold.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetryThreshold proto.InternalMessageInfo

func (m *TelemetryThreshold) GetThresholdValue() uint32 {
	if m != nil {
		return m.ThresholdValue
	}
	return 0
}

func (m *TelemetryThreshold) GetThresholdOpType() TelemetryThreshold_ThresholdOpType {
	if m != nil {
		return m.ThresholdOpType
	}
	return TelemetryThreshold_ThresholdOpType_EQ
}

func init() {
	proto.RegisterEnum("telemetry.Telemetry_Encoding", Telemetry_Encoding_name, Telemetry_Encoding_value)
	proto.RegisterEnum("telemetry.TelemetrySelfDefinedEvent_ThresholdRelation", TelemetrySelfDefinedEvent_ThresholdRelation_name, TelemetrySelfDefinedEvent_ThresholdRelation_value)
	proto.RegisterEnum("telemetry.TelemetryThreshold_ThresholdOpType", TelemetryThreshold_ThresholdOpType_name, TelemetryThreshold_ThresholdOpType_value)
	proto.RegisterType((*Telemetry)(nil), "telemetry.Telemetry")
	proto.RegisterType((*TelemetryGPBTable)(nil), "telemetry.TelemetryGPBTable")
	proto.RegisterType((*TelemetryRowGPB)(nil), "telemetry.TelemetryRowGPB")
	proto.RegisterType((*TelemetrySelfDefinedEvent)(nil), "telemetry.TelemetrySelfDefinedEvent")
	proto.RegisterType((*TelemetrySelfDefineThresTable)(nil), "telemetry.TelemetrySelfDefineThresTable")
	proto.RegisterType((*TelemetryThreshold)(nil), "telemetry.TelemetryThreshold")
}

func init() { proto.RegisterFile("huawei-telemetry.proto", fileDescriptor_4f1dbed6c6cbe291) }

var fileDescriptor_4f1dbed6c6cbe291 = []byte{
	// 733 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x95, 0xdf, 0x6e, 0xda, 0x58,
	0x10, 0xc6, 0x63, 0x20, 0x01, 0xc6, 0x40, 0xcc, 0xe4, 0x8f, 0xcc, 0x2a, 0xc9, 0xb2, 0xac, 0x76,
	0xc5, 0xc5, 0x86, 0x48, 0xac, 0xb4, 0xab, 0x5e, 0x26, 0x02, 0x21, 0xaa, 0x08, 0xa8, 0xb1, 0xd2,
	0x4b, 0xcb, 0xf8, 0x4c, 0xc0, 0x92, 0xff, 0xc9, 0x3e, 0x24, 0xcd, 0x23, 0xf4, 0x31, 0xfa, 0x50,
	0xbd, 0xee, 0xab, 0x54, 0x3e, 0x06, 0x9b, 0x82, 0x95, 0x3b, 0x9f, 0xdf, 0x7c, 0x67, 0x3c, 0xfe,
	0xe6, 0x43, 0xc0, 0xe5, 0x6a, 0x6d, 0xbe, 0x92, 0x7d, 0xcb, 0xc9, 0x21, 0x97, 0x78, 0xf8, 0xd6,
	0x0b, 0x42, 0x9f, 0xfb, 0x58, 0x4d, 0x41, 0xe7, 0x7b, 0x09, 0xaa, 0xfa, 0xf6, 0x84, 0x37, 0x20,
	0x7b, 0x3e, 0x23, 0xc3, 0x66, 0x46, 0xc4, 0x43, 0x55, 0x6a, 0x4b, 0xdd, 0xaa, 0x56, 0x8d, 0xd1,
	0x98, 0xcd, 0x79, 0x88, 0x3d, 0x38, 0x8b, 0xd6, 0x8b, 0xc8, 0x0a, 0xed, 0x80, 0xdb, 0xbe, 0xb7,
	0xd5, 0x15, 0x84, 0xae, 0xb9, 0x5b, 0x4a, 0xf4, 0xbf, 0x83, 0x1c, 0x91, 0x17, 0xf9, 0xa1, 0x11,
	0x98, 0x7c, 0xa5, 0x16, 0x85, 0x0e, 0x12, 0x34, 0x33, 0xf9, 0x0a, 0xff, 0x84, 0xba, 0xe5, 0x3b,
	0x0e, 0x59, 0x9b, 0x76, 0x6a, 0xa9, 0x2d, 0x75, 0x4b, 0x5a, 0x2d, 0x83, 0x63, 0x86, 0x7d, 0xb8,
	0xd8, 0x11, 0x45, 0xdc, 0x0c, 0xb9, 0xc1, 0x6d, 0x97, 0xd4, 0x63, 0x21, 0x3e, 0xcb, 0x8a, 0xf3,
	0xb8, 0xa6, 0xdb, 0x2e, 0xc5, 0x8d, 0xdd, 0x68, 0x29, 0x64, 0x11, 0x37, 0xdd, 0x40, 0x3d, 0x49,
	0x1a, 0xbb, 0xd1, 0x52, 0xdf, 0x32, 0xfc, 0x1f, 0x2a, 0xcc, 0xe4, 0xa6, 0xb1, 0x0c, 0x16, 0x6a,
	0xb9, 0x2d, 0x75, 0xe5, 0xfe, 0x55, 0x2f, 0xf3, 0x2a, 0xb5, 0x65, 0x34, 0x7b, 0xd0, 0xcd, 0x85,
	0x43, 0x5a, 0x39, 0x56, 0x8f, 0x82, 0x45, 0xec, 0xc3, 0xce, 0x44, 0xe4, 0xb1, 0x64, 0x9e, 0x8a,
	0x78, 0x47, 0x33, 0x2b, 0x0d, 0x3d, 0x26, 0xa6, 0xf9, 0x0b, 0x1a, 0xd6, 0x3a, 0x0c, 0xc9, 0xe3,
	0x46, 0x40, 0xa1, 0xed, 0x33, 0xb5, 0xda, 0x96, 0xba, 0x75, 0xad, 0xbe, 0xa1, 0x33, 0x01, 0x63,
	0xbb, 0xe8, 0x8b, 0x45, 0x01, 0x37, 0x18, 0x45, 0x96, 0x0a, 0x89, 0x5d, 0x09, 0x1a, 0x50, 0x64,
	0xe1, 0x1f, 0x50, 0x0b, 0x42, 0x9f, 0xad, 0x2d, 0x6e, 0x78, 0xa6, 0x4b, 0xaa, 0x2c, 0x14, 0xf2,
	0x86, 0x4d, 0x4c, 0x97, 0xf0, 0x03, 0x54, 0xc8, 0xb3, 0x7c, 0x66, 0x7b, 0x4b, 0xb5, 0xd6, 0x96,
	0xba, 0x8d, 0xfe, 0x75, 0xde, 0x37, 0xf5, 0x86, 0x1b, 0x91, 0x96, 0xca, 0xb1, 0xb5, 0xb1, 0x23,
	0x5e, 0x69, 0x43, 0x74, 0x16, 0x1f, 0x3c, 0xe7, 0x61, 0xe7, 0x0e, 0x2a, 0xdb, 0x0b, 0xa8, 0x40,
	0x6d, 0xfb, 0x6c, 0x8c, 0x66, 0x0f, 0xca, 0x11, 0x36, 0xa1, 0x9e, 0x92, 0x8f, 0xf3, 0xe9, 0x44,
	0x91, 0x3a, 0xf7, 0xd0, 0x3c, 0xf0, 0x0f, 0xff, 0x81, 0x62, 0xe8, 0xbf, 0xaa, 0x52, 0xbb, 0xd8,
	0x95, 0xfb, 0xbf, 0xe5, 0x8d, 0xa5, 0xf9, 0xaf, 0xa3, 0xd9, 0x83, 0x16, 0xcb, 0x3a, 0x63, 0x38,
	0xdd, 0xe3, 0x78, 0x05, 0xd5, 0x6c, 0xa3, 0x92, 0x70, 0x3b, 0x03, 0xa8, 0x42, 0xd9, 0xf2, 0x3d,
	0x4e, 0x1e, 0x17, 0xc6, 0xd4, 0xb4, 0xed, 0xb1, 0xf3, 0xa3, 0x08, 0xad, 0xb4, 0xd7, 0x9c, 0x9c,
	0xe7, 0x01, 0x3d, 0xdb, 0x1e, 0xb1, 0xe1, 0x0b, 0x79, 0x1c, 0x11, 0x4a, 0x22, 0x9e, 0x49, 0xdc,
	0xc5, 0x33, 0x9e, 0xc3, 0xb1, 0x43, 0x2f, 0xe4, 0x88, 0x6c, 0xd7, 0xb5, 0xe4, 0x80, 0x6d, 0x90,
	0xe3, 0xcd, 0x6c, 0x32, 0xbe, 0xc9, 0xf3, 0x2e, 0x8a, 0x27, 0x7c, 0xb6, 0xc9, 0x61, 0xf1, 0x2e,
	0x44, 0x98, 0xab, 0x5a, 0x06, 0xf0, 0x06, 0x40, 0x1c, 0x9e, 0x4c, 0x67, 0x9d, 0xc4, 0xb7, 0xae,
	0xed, 0x10, 0x9c, 0x42, 0x43, 0x6c, 0x80, 0xaf, 0x42, 0x8a, 0x56, 0xbe, 0xc3, 0x44, 0x6c, 0xe5,
	0x7e, 0x37, 0xcf, 0xab, 0xec, 0x3b, 0xf4, 0x58, 0x9e, 0x44, 0xb4, 0x1e, 0xdf, 0xd7, 0xb7, 0xd7,
	0x91, 0x41, 0x33, 0xed, 0xa5, 0x91, 0x63, 0x8a, 0xb1, 0xcb, 0x22, 0x16, 0xff, 0xbd, 0xdf, 0x33,
	0xf1, 0xa6, 0xa7, 0xef, 0xdf, 0xd6, 0x0e, 0x1b, 0xee, 0x1a, 0x5f, 0xf9, 0xd5, 0xf8, 0x25, 0x34,
	0x0f, 0x3a, 0xe0, 0x35, 0xb4, 0x0e, 0xa0, 0x31, 0x9e, 0x3c, 0xdd, 0x3f, 0x8e, 0x07, 0xca, 0x11,
	0xb6, 0xe0, 0xe2, 0xb0, 0x7c, 0x3f, 0x19, 0x28, 0x12, 0xaa, 0x70, 0x7e, 0x58, 0x9a, 0x6a, 0x4a,
	0xa1, 0x33, 0x83, 0xeb, 0x77, 0x8d, 0xc1, 0xbb, 0xdd, 0xec, 0xe5, 0xfe, 0x24, 0xb2, 0xce, 0x22,
	0x7e, 0xdf, 0x0a, 0x80, 0x87, 0x35, 0xfc, 0x1b, 0x1a, 0xa9, 0x01, 0xc9, 0x1a, 0x25, 0xb1, 0xc6,
	0x3d, 0x8a, 0x9f, 0xe1, 0x34, 0x25, 0xd3, 0x40, 0x7f, 0x0b, 0x48, 0x44, 0xa9, 0xd1, 0xbf, 0x7d,
	0xf7, 0xdd, 0x99, 0xe1, 0xc9, 0x25, 0x6d, 0xbf, 0x4b, 0xe7, 0xab, 0x04, 0xa7, 0x7b, 0x22, 0xbc,
	0x04, 0xdc, 0x43, 0xc6, 0xf0, 0x93, 0x72, 0x94, 0xc7, 0x47, 0xba, 0x22, 0xe5, 0xf2, 0xa1, 0x52,
	0xc8, 0xe3, 0x8f, 0xba, 0x52, 0xcc, 0xe5, 0x43, 0xa5, 0xb4, 0x38, 0x11, 0xff, 0x27, 0xff, 0xfe,
	0x0c, 0x00, 0x00, 0xff, 0xff, 0x12, 0x7d, 0xb3, 0x6f, 0x69, 0x06, 0x00, 0x00,
}
